export const tables = {
  users: ['id','email','name','role','account_role','account_status','auth_provider','created_at','updated_at','department_id','phase_id','university_id','college_id','section_id','password_hash','password_salt','password_iterations','last_login_at'],
  universities: ['id','name','sort_order','created_at'],
  colleges: ['id','university_id','name','sort_order','created_at'],
  sections: ['id','phase_id','name','sort_order','created_at'],
  tests: ['id','title','subject','lecture','duration_minutes','pass_percentage','shuffle_questions','shuffle_options','status','created_by','created_at','updated_at','exam_mode','available_from','available_until','max_attempts','certificate_enabled'],
  questions: ['id','test_id','text','options_json','correct_option','explanation','position','question_type','accepted_answers_json','image_id','points'],
  attempts: ['id','user_id','test_id','status','score','max_score','percentage','question_order_json','option_orders_json','started_at','last_saved_at','finished_at'],
  attemptAnswers: ['attempt_id','question_id','selected_option','answer_text','is_correct','answered_at'],
  auditLogs: ['id','entity','entity_id','action','by_user_id','at','details_json'],
  apiRateLimits: ['bucket_key','window_start','count'],
  authSessions: ['id','user_id','token_hash','created_at','expires_at','last_used_at','revoked_at','user_agent_hash'],
  userIdentities: ['provider','provider_user_id','user_id','email','created_at'],
  userGrants: ['id','user_id','grant_role','scope_type','scope_id','permissions_json','granted_by','created_at','updated_at'],
  mediaAssets: ['id','object_key','original_name','content_type','byte_size','sha256','alt_text','uploaded_by','created_at','deleted_at'],
  importBatches: ['id','source_type','original_name','object_key','target_lecture_id','target_test_id','status','total_rows','valid_rows','error_rows','conflicts_json','created_by','created_at','committed_at'],
  certificates: ['id','attempt_id','user_id','test_id','verification_code','issued_at','revoked_at'],
} as const;
