import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Bell,BookOpen,CheckCircle2,ChevronLeft,ClipboardList,Clock3,FileQuestion,HeartPulse,History,LayoutDashboard,LogOut,Menu,Plus,Save,Search,Settings2,ShieldCheck,Trash2,Users,X} from 'lucide-react';
import './real.css';

type User={id:string;email:string;name:string;role:'student'|'admin'};
type Test={id:string;title:string;subject:string;lecture:string;durationMinutes:number;passPercentage:number;questionCount:number;status?:string;updatedAt?:string};
type Question={id?:string;text:string;options:string[];correctOption?:number;explanation?:string;position?:number};
type TestDetail=Test&{questions:Question[]};
type HistoryItem={id:string;title:string;subject:string;score:number;maxScore:number;percentage:number;finishedAt:string;passed:number};
type FormTest={id?:string;title:string;subject:string;lecture:string;durationMinutes:number;passPercentage:number;status:string;questions:(Required<Pick<Question,'text'|'options'|'correctOption'>>&Partial<Question>)[]};

async function api<T>(path:string,options:RequestInit={}):Promise<T>{
 const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});
 if(response.status===204)return undefined as T;
 const data=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');
 return data;
}
const emptyQuestion=()=>({text:'',options:['','','',''],correctOption:0,explanation:''});
const emptyForm=():FormTest=>({title:'',subject:'التخدير العام',lecture:'المحاضرة الأولى',durationMinutes:20,passPercentage:60,status:'published',questions:[emptyQuestion()]});

function AuthScreen(){
 return <main className="authPage"><section className="authCard"><div className="authBrand"><span><HeartPulse/></span><div><b>MedExam</b><small>MEDICAL LEARNING</small></div></div><div className="authVisual"><ShieldCheck/></div><h1>منصة الاختبارات الطبية</h1><p>سجّل الدخول للوصول إلى اختباراتك، حفظ تقدمك ومتابعة نتائجك من أي جهاز.</p><a className="signinButton" href="/signin-with-chatgpt?return_to=/">تسجيل الدخول أو إنشاء حساب <ChevronLeft/></a><div className="authNote"><CheckCircle2/> دخول آمن عبر ChatGPT — لا نخزّن كلمة مرورك داخل المنصة</div></section></main>
}
function Stat({icon,value,label,tone='mint'}:{icon:React.ReactNode;value:string|number;label:string;tone?:string}){return <article className="stat"><span className={'statIcon '+tone}>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>}
function Title({title,subtitle}:{title:string;subtitle:string}){return <div className="pageTitle"><div><h1>{title}</h1><p>{subtitle}</p></div><span className="dateChip">{new Intl.DateTimeFormat('ar-IQ',{dateStyle:'long'}).format(new Date())}</span></div>}

function ExamRunner({test,attemptId,onClose,onDone,notify}:{test:TestDetail;attemptId:string;onClose:()=>void;onDone:()=>void;notify:(m:string)=>void}){
 const [current,setCurrent]=useState(0);const [answers,setAnswers]=useState<Record<string,number>>({});const [seconds,setSeconds]=useState(test.durationMinutes*60);const [result,setResult]=useState<{score:number;maxScore:number;percentage:number}|null>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{if(result)return;const timer=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(timer)},[result]);
 useEffect(()=>{if(seconds===0&&!result)void submit()},[seconds]);
 const q=test.questions[current];
 const choose=async(index:number)=>{setAnswers(a=>({...a,[q.id!]:index}));try{await api(`/api/attempts/${attemptId}/answers`,{method:'PATCH',body:JSON.stringify({questionId:q.id,selectedOption:index})})}catch(error){notify((error as Error).message)}};
 const submit=async()=>{if(busy)return;setBusy(true);try{const data=await api<{score:number;maxScore:number;percentage:number}>(`/api/attempts/${attemptId}/submit`,{method:'POST'});setResult(data);onDone()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
 return <div className="modal"><section className="modalCard examModal"><header><div><small>{test.subject}</small><h3>{test.title}</h3></div><span className="timer"><Clock3/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span><button onClick={onClose}><X/></button></header>{result?<div className="result"><span><CheckCircle2/></span><h2>تم تسليم الاختبار</h2><strong>{result.percentage}%</strong><p>أجبت إجابة صحيحة عن {result.score} من {result.maxScore}.</p><button className="solid" onClick={onClose}>العودة إلى المنصة</button></div>:<div className="modalBody"><div className="questionProgress"><span>السؤال {current+1} من {test.questions.length}</span><div className="bar"><i style={{width:(current+1)/test.questions.length*100+'%'}}/></div></div><h2>{q.text}</h2><div className="options">{q.options.map((option,index)=><button key={index} className={answers[q.id!]===index?'selected':''} onClick={()=>void choose(index)}><i/>{option}</button>)}</div><footer><button className="secondary" onClick={onClose}>حفظ وخروج</button><button className="secondary" disabled={current===0} onClick={()=>setCurrent(c=>c-1)}>السابق</button><button className="solid" disabled={answers[q.id!]===undefined||busy} onClick={()=>current===test.questions.length-1?void submit():setCurrent(c=>c+1)}>{current===test.questions.length-1?'إنهاء وتسليم':'التالي'}</button></footer></div>}</section></div>
}

function TestForm({initial,onClose,onSaved,notify}:{initial?:FormTest;onClose:()=>void;onSaved:()=>void;notify:(m:string)=>void}){
 const [form,setForm]=useState<FormTest>(initial||emptyForm());const [busy,setBusy]=useState(false);
 const patchQuestion=(index:number,patch:Partial<FormTest['questions'][number]>)=>setForm(f=>({...f,questions:f.questions.map((q,i)=>i===index?{...q,...patch}:q)}));
 const setOption=(qi:number,oi:number,value:string)=>patchQuestion(qi,{options:form.questions[qi]!.options.map((o,i)=>i===oi?value:o)});
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api(initial?.id?`/api/admin/tests/${initial.id}`:'/api/admin/tests',{method:initial?.id?'PUT':'POST',body:JSON.stringify(form)});notify(initial?'تم تحديث الاختبار':'تم إنشاء الاختبار ونشره');onSaved()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
 return <div className="modal formModal"><form className="modalCard editor" onSubmit={e=>void save(e)}><header><div><small>لوحة المشرف</small><h3>{initial?'تعديل الاختبار':'إنشاء اختبار جديد'}</h3></div><button type="button" onClick={onClose}><X/></button></header><div className="editorBody"><div className="formGrid"><label><span>عنوان الاختبار</span><input required minLength={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>المادة</span><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label><span>المحاضرة</span><input required value={form.lecture} onChange={e=>setForm({...form,lecture:e.target.value})}/></label><label><span>المدة بالدقائق</span><input type="number" min="1" max="360" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:Number(e.target.value)})}/></label><label><span>نسبة النجاح</span><input type="number" min="0" max="100" value={form.passPercentage} onChange={e=>setForm({...form,passPercentage:Number(e.target.value)})}/></label><label><span>الحالة</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="published">منشور</option><option value="draft">مسودة</option></select></label></div><div className="questionEditorHead"><div><h3>أسئلة الاختبار</h3><p>اختر الإجابة الصحيحة لكل سؤال.</p></div><button type="button" className="outline" onClick={()=>setForm(f=>({...f,questions:[...f.questions,emptyQuestion()]}))}><Plus/> إضافة سؤال</button></div><div className="questionEditors">{form.questions.map((question,qi)=><article className="questionEditor" key={qi}><div className="questionNumber"><b>{qi+1}</b><button type="button" disabled={form.questions.length===1} onClick={()=>setForm(f=>({...f,questions:f.questions.filter((_,i)=>i!==qi)}))}><Trash2/></button></div><label><span>نص السؤال</span><textarea required value={question.text} onChange={e=>patchQuestion(qi,{text:e.target.value})}/></label><div className="optionEditor">{question.options.map((option,oi)=><label key={oi} className={question.correctOption===oi?'correct':''}><input type="radio" name={'correct-'+qi} checked={question.correctOption===oi} onChange={()=>patchQuestion(qi,{correctOption:oi})}/><input required placeholder={'الخيار '+(oi+1)} value={option} onChange={e=>setOption(qi,oi,e.target.value)}/></label>)}</div><label><span>شرح الإجابة (اختياري)</span><textarea value={question.explanation||''} onChange={e=>patchQuestion(qi,{explanation:e.target.value})}/></label></article>)}</div></div><footer className="editorFooter"><button type="button" className="secondary" onClick={onClose}>إلغاء</button><button className="solid" disabled={busy}><Save/>{busy?'جارٍ الحفظ...':'حفظ الاختبار'}</button></footer></form></div>
}

export default function RealApp(){
 const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [view,setView]=useState<'home'|'tests'|'history'|'admin'>('home');const [menu,setMenu]=useState(false);const [tests,setTests]=useState<Test[]>([]);const [history,setHistory]=useState<HistoryItem[]>([]);const [summary,setSummary]=useState({attempts:0,averagePercentage:0});const [metrics,setMetrics]=useState<any>(null);const [audit,setAudit]=useState<any[]>([]);const [runner,setRunner]=useState<{test:TestDetail;attemptId:string}|null>(null);const [editor,setEditor]=useState<FormTest|null|undefined>(undefined);const [toast,setToast]=useState('');
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2800)};
 const loadTests=async()=>{const data=await api<{data:Test[]}>('/api/tests');setTests(data.data)};
 const loadHistory=async()=>{const data=await api<{data:HistoryItem[];summary:{attempts:number;averagePercentage:number}}>('/api/me/history');setHistory(data.data);setSummary(data.summary)};
 const loadAdmin=async()=>{if(user?.role!=='admin')return;const [t,m,a]=await Promise.all([api<{data:Test[]}>('/api/admin/tests'),api<any>('/api/admin/metrics'),api<{data:any[]}>('/api/admin/audit')]);setTests(t.data);setMetrics(m);setAudit(a.data)};
 useEffect(()=>{api<{user:User}>('/api/me').then(data=>setUser(data.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!user)return;void Promise.all([loadTests(),loadHistory()]).catch(e=>notify(e.message));},[user]);
 useEffect(()=>{if(view==='admin'&&user?.role==='admin')void loadAdmin().catch(e=>notify(e.message));},[view]);
 const start=async(id:string)=>{try{const [test,attempt]=await Promise.all([api<TestDetail>('/api/tests/'+id),api<{attempt:{id:string}}>('/api/attempts',{method:'POST',body:JSON.stringify({testId:id})})]);setRunner({test,attemptId:attempt.attempt.id})}catch(error){notify((error as Error).message)}};
 const edit=async(id:string)=>{try{const data=await api<any>('/api/admin/tests/'+id);setEditor({...data,questions:data.questions.map((q:any)=>({...q,correctOption:Number(q.correctOption)}))})}catch(error){notify((error as Error).message)}};
 const remove=async(id:string)=>{if(!confirm('أرشفة هذا الاختبار؟ لن يظهر للطلاب بعد ذلك.'))return;try{await api('/api/admin/tests/'+id,{method:'DELETE'});notify('تمت أرشفة الاختبار');await loadAdmin()}catch(error){notify((error as Error).message)}};
 const completed=summary.attempts;const passed=history.filter(h=>h.passed).length;
 if(loading)return <div className="loadingPage"><HeartPulse/><p>جارٍ تحميل المنصة...</p></div>;
 if(!user)return <AuthScreen/>;
 const links=[['home',LayoutDashboard,'نظرة عامة'],['tests',ClipboardList,'الاختبارات'],['history',History,'سجل النتائج']] as const;
 return <div className="app"><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span><HeartPulse/></span><div>MedExam<small>MEDICAL LEARNING</small></div></div><p className="navLabel">القائمة الرئيسية</p><nav>{links.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMenu(false)}}><Icon/>{label}{id==='tests'&&<b>{tests.length}</b>}</button>)}</nav>{user.role==='admin'&&<><p className="navLabel adminLabel">الإدارة</p><nav><button className={view==='admin'?'active':''} onClick={()=>{setView('admin');setMenu(false)}}><Settings2/>لوحة المشرف</button></nav></>}<div className="miniProfile"><span>{user.name.slice(0,2)}</span><div><b>{user.name}</b><small>{user.role==='admin'?'مشرف المنصة':'طالب'}</small></div><a href="/signout-with-chatgpt?return_to=/" aria-label="تسجيل الخروج"><LogOut/></a></div></aside><main><header className="topbar"><button className="menuBtn" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search/><input placeholder="ابحث عن اختبار أو محاضرة..." aria-label="بحث"/></div><button className="bell"><Bell/><i/></button><span className="avatar">{user.name.slice(0,2)}</span></header>
 {view==='home'&&<><Title title={'أهلًا '+user.name} subtitle="تابع تقدمك وابدأ اختبارك القادم بثقة."/><section className="hero"><div className="heroCopy"><span className="eyebrow"><HeartPulse/> منصة تعلم طبية</span><h2>{tests[0]?.title||'لا توجد اختبارات منشورة بعد'}</h2><p>{tests[0]?`${tests[0].subject} • ${tests[0].lecture} • ${tests[0].questionCount} أسئلة`:'سيظهر هنا أول اختبار ينشره المشرف.'}</p>{tests[0]&&<button className="heroButton" onClick={()=>void start(tests[0].id)}>ابدأ الاختبار الآن <ChevronLeft/></button>}</div><div className="heroArt"><HeartPulse/></div></section><div className="stats"><Stat icon={<CheckCircle2/>} value={completed} label="اختبارًا مكتملًا"/><Stat icon={<BarChart3/>} value={summary.averagePercentage+'%'} label="متوسط الدرجات" tone="amber"/><Stat icon={<ShieldCheck/>} value={passed} label="اختبارات ناجحة" tone="blue"/><Stat icon={<BookOpen/>} value={tests.length} label="اختبارات متاحة" tone="coral"/></div><section className="panel"><div className="panelHead"><h3>أحدث الاختبارات</h3><button onClick={()=>setView('tests')}>عرض الكل</button></div><div className="examList">{tests.slice(0,3).map((test,index)=><article className="exam" key={test.id}><span className={'examMark m'+index}><FileQuestion/></span><div><h4>{test.title}</h4><p>{test.subject} • {test.questionCount} أسئلة • {test.durationMinutes} دقيقة</p></div><button className="outline" onClick={()=>void start(test.id)}>ابدأ الآن</button></article>)}</div></section></>}
 {view==='tests'&&<><Title title="الاختبارات المتاحة" subtitle="اختر اختبارًا وابدأ المحاولة؛ تُحفظ إجاباتك تلقائيًا."/><div className="cards">{tests.map(test=><article className="testCard" key={test.id}><span className="tag">{test.subject}</span><h3>{test.title}</h3><p>{test.lecture}</p><div className="meta"><span><Clock3/>{test.durationMinutes} دقيقة</span><span><ClipboardList/>{test.questionCount} أسئلة</span></div><button className="solid full" onClick={()=>void start(test.id)}>بدء الاختبار</button></article>)}</div>{!tests.length&&<div className="empty"><BookOpen/><h3>لا توجد اختبارات منشورة</h3><p>سيظهر الاختبار هنا فور نشره من المشرف.</p></div>}</>}
 {view==='history'&&<><Title title="سجل النتائج" subtitle="كل محاولاتك ودرجاتك محفوظة في حسابك."/><div className="stats"><Stat icon={<ClipboardList/>} value={completed} label="إجمالي المحاولات"/><Stat icon={<CheckCircle2/>} value={passed} label="اختبارات ناجحة" tone="amber"/><Stat icon={<BarChart3/>} value={summary.averagePercentage+'%'} label="المتوسط العام" tone="blue"/><Stat icon={<ShieldCheck/>} value={completed?Math.round(passed/completed*100)+'%':'0%'} label="نسبة النجاح" tone="coral"/></div><section className="panel tableWrap"><table><thead><tr><th>الاختبار</th><th>المادة</th><th>التاريخ</th><th>النتيجة</th><th>الحالة</th></tr></thead><tbody>{history.map(item=><tr key={item.id}><td>{item.title}</td><td>{item.subject}</td><td>{new Intl.DateTimeFormat('ar-IQ').format(new Date(item.finishedAt))}</td><td className={item.passed?'good':'low'}>{item.percentage}%</td><td><span className={item.passed?'success':'retry'}>{item.passed?'ناجح':'إعادة مطلوبة'}</span></td></tr>)}</tbody></table>{!history.length&&<div className="empty small"><History/><p>لم تُكمل أي اختبار بعد.</p></div>}</section></>}
 {view==='admin'&&user.role==='admin'&&<><Title title="لوحة المشرف" subtitle="إنشاء الاختبارات وإدارتها ومتابعة نشاط الطلاب."/><div className="stats"><Stat icon={<ClipboardList/>} value={metrics?.tests||0} label="اختبارات فعالة"/><Stat icon={<Users/>} value={metrics?.students||0} label="طلاب مسجلون" tone="amber"/><Stat icon={<CheckCircle2/>} value={metrics?.attempts||0} label="إجمالي المحاولات" tone="blue"/><Stat icon={<BarChart3/>} value={(metrics?.averagePercentage||0)+'%'} label="متوسط الدرجات" tone="coral"/></div><div className="contentGrid"><section className="panel tableWrap"><div className="adminHead"><div><h3>إدارة الاختبارات</h3><small>تُنشر التغييرات للطلاب مباشرة</small></div><button className="solid" onClick={()=>setEditor(null)}><Plus/>اختبار جديد</button></div><table><thead><tr><th>العنوان</th><th>المادة</th><th>الأسئلة</th><th>الحالة</th><th/></tr></thead><tbody>{tests.map(test=><tr key={test.id}><td>{test.title}</td><td>{test.subject}</td><td>{test.questionCount}</td><td><span className={test.status==='published'?'success':'draft'}>{test.status==='published'?'منشور':'مسودة'}</span></td><td className="actions"><button onClick={()=>void edit(test.id)}>تعديل</button><button className="trash" onClick={()=>void remove(test.id)}><Trash2/></button></td></tr>)}</tbody></table></section><aside className="panel"><div className="panelHead"><h3>سجل التدقيق</h3></div>{audit.slice(0,8).map(log=><div className="audit" key={log.id}><b>{log.action==='create'?'إنشاء اختبار':log.action==='update'?'تعديل اختبار':'أرشفة اختبار'}</b><small>{log.actorName||'النظام'} • {new Intl.DateTimeFormat('ar-IQ',{dateStyle:'short',timeStyle:'short'}).format(new Date(log.at+'Z'))}</small></div>)}{!audit.length&&<p className="muted">لا توجد عمليات بعد.</p>}</aside></div></>}
 </main>{menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="إغلاق القائمة"/>}{runner&&<ExamRunner {...runner} onClose={()=>setRunner(null)} onDone={()=>void loadHistory()} notify={notify}/>} {editor!==undefined&&<TestForm initial={editor||undefined} onClose={()=>setEditor(undefined)} notify={notify} onSaved={()=>{setEditor(undefined);void loadAdmin()}}/>}<div className={toast?'toast show':'toast'}>{toast}</div></div>
}
