import {readFile} from 'node:fs/promises';
export {sqlite,env,firebase,call};
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker/site-worker.js';
import {createFirebaseAuthMock} from './firebase-auth-mock.mjs';
import {createPasswordRecord,revokeUserSessions} from '../worker/password-auth.js';
import {firebaseSendVerification,firebaseSignUp} from '../worker/firebase-auth.js';

class Statement{constructor(database,sql){this.statement=database.prepare(sql)}bind(...values){this.values=values;return this}async first(){return this.statement.get(...(this.values||[]))||null}async all(){return {results:this.statement.all(...(this.values||[]))}}async run(){const result=this.statement.run(...(this.values||[]));return {meta:{changes:Number(result.changes)}}}}
class D1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(statements){this.database.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());this.database.exec('COMMIT');return results}catch(error){this.database.exec('ROLLBACK');throw error}}}
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const file of ['drizzle/0000_medexam.sql','drizzle/0001_academic_hierarchy.sql','drizzle/0002_backfill_existing_tests.sql','drizzle/0003_scale_indexes.sql','drizzle/0004_attempt_shuffle.sql','drizzle/0005_security_hardening.sql','drizzle/0006_accounts_organizations_permissions.sql','drizzle/0007_exam_modes_question_types_files.sql','drizzle/0008_staff_titles_and_college_copy.sql','drizzle/0009_clinical_glimpses_library_logs.sql','drizzle/0010_student_bans.sql','drizzle/0011_security_hardening.sql','drizzle/0012_firebase_auth.sql','drizzle/0013_academic_trash_and_notifications.sql','drizzle/0014_media_access_indexes.sql','drizzle/0015_google_auth_flows.sql','drizzle/0016_auth_session_epoch.sql'])sqlite.exec(await readFile(file,'utf8'));
const firebase=createFirebaseAuthMock();const env={DB:new D1(sqlite),OWNER_USER_IDS:'owner-auth',PASSWORD_PEPPER:'test-password-pepper-32-characters-long',DEVICE_HASH_PEPPER:'test-device-pepper-32-characters-long',FIREBASE_AUTH:firebase.api};const base='https://example.test';
function headers(extra={}){return {'content-type':'application/json','origin':base,'sec-fetch-site':'same-origin',...extra}}
async function call(path,{method='GET',body,extraHeaders={}}={}){const response=await worker.fetch(new Request(base+path,{method,headers:headers(extraHeaders),body:body===undefined?undefined:JSON.stringify(body)}),env);let data=null;if(response.status!==204)data=await response.json();return {response,data}}

await call('/api/me',{extraHeaders:{'oai-authenticated-user-id':'owner-auth','oai-authenticated-user-email':'owner@example.com'}});env.OWNER_PASSWORD_SETUP_TOKEN='owner-recovery-token-at-least-32-characters';
const ownerRecovery=await call('/api/auth/recover-owner-password',{method:'POST',extraHeaders:{'x-kiur-owner-setup-token':env.OWNER_PASSWORD_SETUP_TOKEN},body:{email:'owner@example.com',password:'OwnerSecurePass20262026!'}});if(ownerRecovery.response.status!==200)throw new Error(`Owner password recovery failed: ${JSON.stringify(ownerRecovery.data)}`);
const repeatedRecovery=await call('/api/auth/recover-owner-password',{method:'POST',extraHeaders:{'x-kiur-owner-setup-token':env.OWNER_PASSWORD_SETUP_TOKEN},body:{email:'owner@example.com',password:'OwnerSecurePass20262026!'}});if(repeatedRecovery.response.status!==410)throw new Error('Owner recovery operation was not single-use');
sqlite.prepare(`DELETE FROM api_rate_limits`).run();env.OWNER_PASSWORD_SETUP_TOKEN='owner-recovery-failure-token-at-least-32-characters';const failedRecovery=await call('/api/auth/recover-owner-password',{method:'POST',extraHeaders:{'x-kiur-owner-setup-token':env.OWNER_PASSWORD_SETUP_TOKEN},body:{email:'owner@example.com',password:'99999999z'}});if(failedRecovery.response.status!==409)throw new Error(`Owner recovery downstream failure was not surfaced safely: ${failedRecovery.response.status} ${JSON.stringify(failedRecovery.data)}`);const burnedRecovery=await call('/api/auth/recover-owner-password',{method:'POST',extraHeaders:{'x-kiur-owner-setup-token':env.OWNER_PASSWORD_SETUP_TOKEN},body:{email:'owner@example.com',password:'OwnerSecurePass20262026!'}});if(burnedRecovery.response.status!==410)throw new Error('Failed owner recovery operation was not burned closed');
delete env.OWNER_PASSWORD_SETUP_TOKEN;const ownerLogin=await call('/api/auth/login',{method:'POST',body:{email:'owner@example.com',password:'OwnerSecurePass20262026!'}});if(ownerLogin.response.status!==200||ownerLogin.data.user.role!=='owner')throw new Error('Recovered owner password could not sign in');const ownerCookie=ownerLogin.response.headers.get('set-cookie').split(';')[0];
const disabledRecovery=await call('/api/auth/recover-owner-password',{method:'POST',extraHeaders:{'x-kiur-owner-setup-token':'owner-recovery-token-at-least-32-characters'},body:{email:'owner@example.com',password:'AnotherSecurePass2026!'}});if(disabledRecovery.response.status!==404)throw new Error('Owner recovery route remained active without its deployment secret');

const registration=await call('/api/auth/register',{method:'POST',body:{name:'طالب تجريبي',email:'student@example.com',password:'12345678a',universityId:'uni-eratrans',collegeId:'college-eratrans-medical',departmentId:'dep-anesthesia',phaseId:'pha-a4'}});if(registration.response.status!==202||!registration.data.pending)throw new Error(`Registration did not create a pending account: ${registration.response.status} ${JSON.stringify(registration.data)}`);
const beforeVerification=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'12345678a'}});if(beforeVerification.response.status!==403||beforeVerification.data.error.code!=='EMAIL_UNVERIFIED')throw new Error('Unverified Firebase account could log in');
if(!firebase.messages.some(item=>item.kind==='verify_email'&&item.email==='student@example.com'))throw new Error('Firebase verification email was not requested');firebase.verify('student@example.com');
const beforeApproval=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'12345678a'}});if(beforeApproval.response.status!==403||beforeApproval.data.error.code!=='ACCOUNT_PENDING')throw new Error('Pending account could log in');
await call('/api/me',{extraHeaders:{'oai-authenticated-user-id':'owner-auth','oai-authenticated-user-email':'owner@example.com'}});const studentId=sqlite.prepare(`SELECT id FROM users WHERE email=?`).get('student@example.com').id;
const approval=await call(`/api/admin/users/${studentId}`,{method:'PATCH',extraHeaders:{'oai-authenticated-user-id':'owner-auth','oai-authenticated-user-email':'owner@example.com'},body:{status:'active'}});if(approval.response.status!==200)throw new Error('Owner could not approve account');
const login=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'12345678a'}});let cookie=login.response.headers.get('set-cookie');if(login.response.status!==200||!cookie?.includes('__Host-kiur_session=')||!cookie.includes('HttpOnly')||!cookie.includes('Secure')||!cookie.includes('SameSite=Strict'))throw new Error('Strict host-only session cookie was not issued');
const session=await call('/api/auth/session',{extraHeaders:{cookie:cookie.split(';')[0]}});if(session.response.status!==200||session.data.user.email!=='student@example.com')throw new Error('Password session was not resolved');
const unauthorizedAdmin=await call('/api/admin/users',{extraHeaders:{cookie:cookie.split(';')[0]}});if(unauthorizedAdmin.response.status!==403)throw new Error('Student session reached the admin account API');
const epochBefore=Number(sqlite.prepare(`SELECT auth_epoch FROM users WHERE id=?`).get(studentId).auth_epoch);const logoutAll=await call('/api/auth/logout-all',{method:'POST',extraHeaders:{cookie:cookie.split(';')[0]},body:{}});if(logoutAll.response.status!==200||!logoutAll.data.allSessions)throw new Error('Logout-all endpoint failed');if((await call('/api/auth/session',{extraHeaders:{cookie:cookie.split(';')[0]}})).response.status!==401)throw new Error('Logout-all left the initiating session valid');if(Number(sqlite.prepare(`SELECT auth_epoch FROM users WHERE id=?`).get(studentId).auth_epoch)!==epochBefore+1)throw new Error('Logout-all did not advance the auth epoch');if((await call('/api/auth/session',{extraHeaders:{cookie:ownerCookie}})).response.status!==200)throw new Error('Logout-all invalidated another user');const relogin=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'12345678a'}});cookie=relogin.response.headers.get('set-cookie');
const rollbackBefore=sqlite.prepare(`SELECT name,auth_epoch AS authEpoch FROM users WHERE id=?`).get(studentId);let rolledBack=false;try{await revokeUserSessions(env,studentId,[env.DB.prepare(`UPDATE users SET name='SHOULD_ROLL_BACK' WHERE id=?`).bind(studentId),env.DB.prepare(`INSERT INTO owner_recovery_operations(operation_hash,user_id) VALUES('rollback-test',?)`).bind(studentId),env.DB.prepare(`INSERT INTO owner_recovery_operations(operation_hash,user_id) VALUES('rollback-test',?)`).bind(studentId)])}catch{rolledBack=true}const rollbackAfter=sqlite.prepare(`SELECT name,auth_epoch AS authEpoch FROM users WHERE id=?`).get(studentId);if(!rolledBack||rollbackAfter.name!==rollbackBefore.name||rollbackAfter.authEpoch!==rollbackBefore.authEpoch||sqlite.prepare(`SELECT 1 FROM owner_recovery_operations WHERE operation_hash='rollback-test'`).get())throw new Error('Session invalidation batch did not roll back atomically');
const logout=await call('/api/auth/logout',{method:'POST',extraHeaders:{cookie:cookie.split(';')[0]},body:{}});const clearedCookie=logout.response.headers.get('set-cookie')||'';if(logout.response.status!==200||!clearedCookie.includes('__Host-kiur_session=')||!clearedCookie.includes('Max-Age=0')||!clearedCookie.includes('HttpOnly')||!clearedCookie.includes('Secure'))throw new Error('Logout did not clear the secure session cookie');
const revoked=await call('/api/auth/session',{extraHeaders:{cookie:cookie.split(';')[0]}});if(revoked.response.status!==401)throw new Error('Revoked session remained valid');
const reset=await call('/api/auth/forgot-password',{method:'POST',body:{email:'student@example.com'}});if(reset.response.status!==202||!firebase.messages.some(item=>item.kind==='password_reset'&&item.email==='student@example.com'))throw new Error(`Firebase password reset was not requested: ${reset.response.status} ${JSON.stringify(reset.data)} ${JSON.stringify(firebase.messages)}`);
const firebaseLink=sqlite.prepare(`SELECT firebase_uid AS firebaseUid,email_verified_at AS verifiedAt,password_hash AS passwordHash FROM users WHERE id=?`).get(studentId);if(!firebaseLink.firebaseUid||!firebaseLink.verifiedAt||firebaseLink.passwordHash!==null)throw new Error('Firebase identity state was not stored safely');
const events=sqlite.prepare(`SELECT event_type AS eventType,outcome FROM account_events WHERE user_id=? ORDER BY id`).all(studentId);for(const expected of ['register','account_status','login_success','logout','password_reset_requested'])if(!events.some(item=>item.eventType===expected))throw new Error(`Missing account event ${expected}`);if(!events.some(item=>item.eventType==='login_failure'&&item.outcome==='failure'))throw new Error('Failed login was not recorded');console.log(JSON.stringify({ok:true,pending:registration.response.status,unverified:beforeVerification.response.status,blocked:beforeApproval.response.status,approved:approval.response.status,session:session.response.status,revoked:revoked.response.status,accountEvents:events.length,firebase:true}));

const legacyPassword=await createPasswordRecord('LegacyPass2026',env);sqlite.prepare(`INSERT INTO users(id,email,name,role,account_role,account_status,auth_provider,password_hash,password_salt,password_iterations,password_peppered,email_verified_at) VALUES(?,?,?,'student','student','active','password',?,?,?,?,CURRENT_TIMESTAMP)`).run('legacy-user','legacy@example.com','طالب قديم',legacyPassword.hash,legacyPassword.salt,legacyPassword.iterations,legacyPassword.peppered);sqlite.prepare(`INSERT INTO user_identities(provider,provider_user_id,user_id,email) VALUES('password',?,?,?)`).run('legacy@example.com','legacy-user','legacy@example.com');
const legacyLogin=await call('/api/auth/login',{method:'POST',body:{email:'legacy@example.com',password:'LegacyPass2026'}});if(legacyLogin.response.status!==200)throw new Error(`Legacy account migration failed: ${JSON.stringify(legacyLogin.data)}`);const migratedLegacy=sqlite.prepare(`SELECT firebase_uid AS firebaseUid,password_hash AS passwordHash FROM users WHERE id='legacy-user'`).get();if(!migratedLegacy.firebaseUid||migratedLegacy.passwordHash!==null||!sqlite.prepare(`SELECT 1 FROM account_events WHERE user_id='legacy-user' AND event_type='firebase_migration'`).get())throw new Error('Legacy credentials were not migrated safely');
const restCalls=[];const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{restCalls.push({url:String(url),options});return String(url).includes(':signUp')?Response.json({localId:'rest-uid',idToken:'rest-token',email:'rest@example.com'}):Response.json({email:'rest@example.com'})};try{const direct=await firebaseSignUp({FIREBASE_WEB_API_KEY:'firebase-web-test'},'rest@example.com','RestPassword2026');await firebaseSendVerification({FIREBASE_WEB_API_KEY:'firebase-web-test'},direct.idToken)}finally{globalThis.fetch=originalFetch}if(restCalls.length!==2||!restCalls[0].url.startsWith('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=')||!restCalls[1].url.startsWith('https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=')||restCalls[1].options.headers['x-firebase-locale']!=='ar'||String(restCalls[0].options.body).includes('firebase-web-test'))throw new Error('Firebase REST transport was not configured safely');
