import {readFile} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker/site-worker.js';
import {createFirebaseAuthMock} from './firebase-auth-mock.mjs';
import {createPasswordRecord} from '../worker/password-auth.js';
import {firebaseSendVerification,firebaseSignUp} from '../worker/firebase-auth.js';

class Statement{constructor(database,sql){this.statement=database.prepare(sql)}bind(...values){this.values=values;return this}async first(){return this.statement.get(...(this.values||[]))||null}async all(){return {results:this.statement.all(...(this.values||[]))}}async run(){const result=this.statement.run(...(this.values||[]));return {meta:{changes:Number(result.changes)}}}}
class D1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(statements){const results=[];for(const statement of statements)results.push(await statement.run());return results}}
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
for(const file of ['drizzle/0000_medexam.sql','drizzle/0001_academic_hierarchy.sql','drizzle/0002_backfill_existing_tests.sql','drizzle/0003_scale_indexes.sql','drizzle/0004_attempt_shuffle.sql','drizzle/0005_security_hardening.sql','drizzle/0006_accounts_organizations_permissions.sql','drizzle/0007_exam_modes_question_types_files.sql','drizzle/0008_staff_titles_and_college_copy.sql','drizzle/0009_clinical_glimpses_library_logs.sql','drizzle/0010_student_bans.sql','drizzle/0011_security_hardening.sql','drizzle/0012_firebase_auth.sql','drizzle/0013_academic_trash_and_notifications.sql'])sqlite.exec(await readFile(file,'utf8'));
const firebase=createFirebaseAuthMock();const env={DB:new D1(sqlite),OWNER_USER_IDS:'owner-auth',PASSWORD_PEPPER:'test-password-pepper-32-characters-long',DEVICE_HASH_PEPPER:'test-device-pepper-32-characters-long',FIREBASE_AUTH:firebase.api};const base='https://example.test';
function headers(extra={}){return {'content-type':'application/json','origin':base,'sec-fetch-site':'same-origin',...extra}}
async function call(path,{method='GET',body,extraHeaders={}}={}){const response=await worker.fetch(new Request(base+path,{method,headers:headers(extraHeaders),body:body===undefined?undefined:JSON.stringify(body)}),env);let data=null;if(response.status!==204)data=await response.json();return {response,data}}

const registration=await call('/api/auth/register',{method:'POST',body:{name:'طالب تجريبي',email:'student@example.com',password:'SecurePass2026',universityId:'uni-eratrans',collegeId:'college-eratrans-medical',departmentId:'dep-anesthesia',phaseId:'pha-a4'}});if(registration.response.status!==202||!registration.data.pending)throw new Error(`Registration did not create a pending account: ${registration.response.status} ${JSON.stringify(registration.data)}`);
const beforeVerification=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'SecurePass2026'}});if(beforeVerification.response.status!==403||beforeVerification.data.error.code!=='EMAIL_UNVERIFIED')throw new Error('Unverified Firebase account could log in');
if(!firebase.messages.some(item=>item.kind==='verify_email'&&item.email==='student@example.com'))throw new Error('Firebase verification email was not requested');firebase.verify('student@example.com');
const beforeApproval=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'SecurePass2026'}});if(beforeApproval.response.status!==403||beforeApproval.data.error.code!=='ACCOUNT_PENDING')throw new Error('Pending account could log in');
await call('/api/me',{extraHeaders:{'oai-authenticated-user-id':'owner-auth','oai-authenticated-user-email':'owner@example.com'}});const studentId=sqlite.prepare(`SELECT id FROM users WHERE email=?`).get('student@example.com').id;
const approval=await call(`/api/admin/users/${studentId}`,{method:'PATCH',extraHeaders:{'oai-authenticated-user-id':'owner-auth','oai-authenticated-user-email':'owner@example.com'},body:{status:'active'}});if(approval.response.status!==200)throw new Error('Owner could not approve account');
const login=await call('/api/auth/login',{method:'POST',body:{email:'student@example.com',password:'SecurePass2026'}});const cookie=login.response.headers.get('set-cookie');if(login.response.status!==200||!cookie?.includes('HttpOnly')||!cookie.includes('Secure')||!cookie.includes('SameSite=Lax'))throw new Error('Secure session cookie was not issued');
const session=await call('/api/auth/session',{extraHeaders:{cookie:cookie.split(';')[0]}});if(session.response.status!==200||session.data.user.email!=='student@example.com')throw new Error('Password session was not resolved');
const logout=await call('/api/auth/logout',{method:'POST',extraHeaders:{cookie:cookie.split(';')[0]},body:{}});if(logout.response.status!==200)throw new Error('Logout failed');const revoked=await call('/api/auth/session',{extraHeaders:{cookie:cookie.split(';')[0]}});if(revoked.response.status!==401)throw new Error('Revoked session remained valid');
const reset=await call('/api/auth/forgot-password',{method:'POST',body:{email:'student@example.com'}});if(reset.response.status!==202||!firebase.messages.some(item=>item.kind==='password_reset'&&item.email==='student@example.com'))throw new Error(`Firebase password reset was not requested: ${reset.response.status} ${JSON.stringify(reset.data)} ${JSON.stringify(firebase.messages)}`);
const firebaseLink=sqlite.prepare(`SELECT firebase_uid AS firebaseUid,email_verified_at AS verifiedAt,password_hash AS passwordHash FROM users WHERE id=?`).get(studentId);if(!firebaseLink.firebaseUid||!firebaseLink.verifiedAt||firebaseLink.passwordHash!==null)throw new Error('Firebase identity state was not stored safely');
const events=sqlite.prepare(`SELECT event_type AS eventType,outcome FROM account_events WHERE user_id=? ORDER BY id`).all(studentId);for(const expected of ['register','account_status','login_success','logout','password_reset_requested'])if(!events.some(item=>item.eventType===expected))throw new Error(`Missing account event ${expected}`);if(!events.some(item=>item.eventType==='login_failure'&&item.outcome==='failure'))throw new Error('Failed login was not recorded');console.log(JSON.stringify({ok:true,pending:registration.response.status,unverified:beforeVerification.response.status,blocked:beforeApproval.response.status,approved:approval.response.status,session:session.response.status,revoked:revoked.response.status,accountEvents:events.length,firebase:true}));

const legacyPassword=await createPasswordRecord('LegacyPass2026',env);sqlite.prepare(`INSERT INTO users(id,email,name,role,account_role,account_status,auth_provider,password_hash,password_salt,password_iterations,password_peppered,email_verified_at) VALUES(?,?,?,'student','student','active','password',?,?,?,?,CURRENT_TIMESTAMP)`).run('legacy-user','legacy@example.com','طالب قديم',legacyPassword.hash,legacyPassword.salt,legacyPassword.iterations,legacyPassword.peppered);sqlite.prepare(`INSERT INTO user_identities(provider,provider_user_id,user_id,email) VALUES('password',?,?,?)`).run('legacy@example.com','legacy-user','legacy@example.com');
const legacyLogin=await call('/api/auth/login',{method:'POST',body:{email:'legacy@example.com',password:'LegacyPass2026'}});if(legacyLogin.response.status!==200)throw new Error(`Legacy account migration failed: ${JSON.stringify(legacyLogin.data)}`);const migratedLegacy=sqlite.prepare(`SELECT firebase_uid AS firebaseUid,password_hash AS passwordHash FROM users WHERE id='legacy-user'`).get();if(!migratedLegacy.firebaseUid||migratedLegacy.passwordHash!==null||!sqlite.prepare(`SELECT 1 FROM account_events WHERE user_id='legacy-user' AND event_type='firebase_migration'`).get())throw new Error('Legacy credentials were not migrated safely');
const restCalls=[];const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{restCalls.push({url:String(url),options});return String(url).includes(':signUp')?Response.json({localId:'rest-uid',idToken:'rest-token',email:'rest@example.com'}):Response.json({email:'rest@example.com'})};try{const direct=await firebaseSignUp({FIREBASE_WEB_API_KEY:'firebase-web-test'},'rest@example.com','RestPassword2026');await firebaseSendVerification({FIREBASE_WEB_API_KEY:'firebase-web-test'},direct.idToken)}finally{globalThis.fetch=originalFetch}if(restCalls.length!==2||!restCalls[0].url.startsWith('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=')||!restCalls[1].url.startsWith('https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=')||restCalls[1].options.headers['x-firebase-locale']!=='ar'||String(restCalls[0].options.body).includes('firebase-web-test'))throw new Error('Firebase REST transport was not configured safely');
