import {hasPermission} from './access-control.js';
import {readJsonBody,secureHeaders} from './security.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:secureHeaders({'content-type':'application/json; charset=utf-8','cache-control':'no-store'})})}
function fail(code,message,status=400){return json({error:{code,message}},status)}
async function body(request){const parsed=await readJsonBody(request);return parsed.error?{response:fail(parsed.error.code,parsed.error.message,parsed.error.status)}:{value:parsed.value}}
function normalizeText(value){return String(value||'').normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('ar')}
function splitAnswers(value){return String(value||'').split(/[|؛;]/).map(item=>item.trim()).filter(Boolean).slice(0,20)}
function parseCorrect(value,options){const text=String(value??'').trim();if(/^\d+$/.test(text)){const number=Number(text);if(number>=0&&number<options.length)return number;if(number>=1&&number<=options.length)return number-1}const letter=text.toUpperCase().charCodeAt(0)-65;if(letter>=0&&letter<options.length)return letter;return options.findIndex(option=>normalizeText(option)===normalizeText(text))}
function normalizeRow(raw,index){
  const type=String(raw?.type||raw?.questionType||'mcq').trim().toLowerCase();const questionType={mcq:'mcq','multiple choice':'mcq','صح/خطأ':'true_false','true/false':'true_false','true_false':'true_false','أكمل الفراغ':'fill_blank','fill_blank':'fill_blank','حالة سريرية':'clinical_case','clinical_case':'clinical_case'}[type];const text=String(raw?.text||raw?.question||'').trim();const errors=[];if(!questionType)errors.push('نوع السؤال غير معروف');if(text.length<3||text.length>5000)errors.push('نص السؤال مفقود أو طويل جدًا');
  let options=[];let correctOption=0;let acceptedAnswers=[];if(questionType==='fill_blank'){acceptedAnswers=Array.isArray(raw.acceptedAnswers)?raw.acceptedAnswers.map(String).filter(Boolean):splitAnswers(raw.acceptedAnswers||raw.correctAnswer);if(!acceptedAnswers.length)errors.push('أضف إجابة مقبولة واحدة على الأقل')}else{options=Array.isArray(raw.options)?raw.options.map(String).map(item=>item.trim()).filter(Boolean):[raw.optionA,raw.optionB,raw.optionC,raw.optionD,raw.optionE,raw.optionF].map(value=>String(value||'').trim()).filter(Boolean);if(questionType==='true_false'&&!options.length)options=['صح','خطأ'];if(options.length<2||options.length>8)errors.push('عدد الخيارات يجب أن يكون بين 2 و8');correctOption=parseCorrect(raw.correctAnswer??raw.correctOption,options);if(correctOption<0||correctOption>=options.length)errors.push('الإجابة الصحيحة لا تطابق الخيارات')}
  const imageId=String(raw?.imageId||'').trim()||null;if(questionType==='clinical_case'&&!imageId)errors.push('سؤال الحالة السريرية يحتاج صورة من المكتبة');return {row:index+1,questionType:questionType||'mcq',text,options,correctOption,acceptedAnswers,explanation:String(raw?.explanation||'').trim().slice(0,10000),imageId,errors};
}
async function testContext(env,testId){return env.DB.prepare(`SELECT t.id,t.lecture_id AS lectureId,t.department_id AS departmentId,t.phase_id AS phaseId,t.section_id AS sectionId,t.subject_id AS subjectId,c.university_id AS universityId,d.college_id AS collegeId FROM tests t LEFT JOIN departments d ON d.id=t.department_id LEFT JOIN colleges c ON c.id=d.college_id WHERE t.id=? AND t.status!='archived'`).bind(testId).first()}
async function prepareRows(env,testId,rows){const normalized=rows.slice(0,1000).map(normalizeRow);const existing=await env.DB.prepare(`SELECT id,text,question_type AS questionType FROM questions WHERE test_id=?`).bind(testId).all();const map=new Map(existing.results.map(item=>[`${item.questionType}:${normalizeText(item.text)}`,item.id]));for(const row of normalized){const conflict=map.get(`${row.questionType}:${normalizeText(row.text)}`);if(conflict)row.existingQuestionId=conflict}return normalized}
async function checkImages(env,user,context,rows){const clinical=rows.filter(row=>row.questionType==='clinical_case');if(!clinical.length)return;if(!(await hasPermission(env,user,'use_media',context))){for(const row of clinical)row.errors.push('لا تملك صلاحية استخدام مكتبة الصور');return}for(const row of clinical){if(!row.imageId)continue;const asset=await env.DB.prepare(`SELECT id FROM media_assets WHERE id=? AND deleted_at IS NULL`).bind(row.imageId).first();if(!asset)row.errors.push('معرف الصورة غير موجود في المكتبة')}}

export async function handleImportApi(request,env,url,user){
  if(!url.pathname.startsWith('/api/admin/imports'))return null;if(!['owner','admin','teacher'].includes(user?.role))return fail('FORBIDDEN','هذه العملية للكوادر المخولة فقط',403);
  if(url.pathname==='/api/admin/imports/preview'&&request.method==='POST'){
    const parsed=await body(request);if(parsed.response)return parsed.response;const value=parsed.value||{};if(!['xlsx','docx'].includes(value.sourceType)||typeof value.fileName!=='string'||value.fileName.length>180||!Array.isArray(value.rows)||!value.rows.length||value.rows.length>1000)return fail('VALIDATION','ملف الاستيراد أو صفوفه غير صالحة');const context=await testContext(env,String(value.testId||''));if(!context)return fail('NOT_FOUND','الاختبار غير موجود',404);if(!(await hasPermission(env,user,'import_questions',context)))return fail('FORBIDDEN','لا تملك صلاحية الاستيراد لهذا الاختبار',403);
    const rows=await prepareRows(env,context.id,value.rows);await checkImages(env,user,context,rows);const validRows=rows.filter(row=>!row.errors.length).length;const errorRows=rows.length-validRows;const conflicts=rows.filter(row=>row.existingQuestionId).map(row=>({row:row.row,existingQuestionId:row.existingQuestionId,text:row.text}));const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO import_batches(id,source_type,original_name,target_lecture_id,target_test_id,total_rows,valid_rows,error_rows,conflicts_json,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,value.sourceType,value.fileName.slice(0,180),context.lectureId,context.id,rows.length,validRows,errorRows,JSON.stringify(conflicts),user.id).run();return json({batchId:id,rows,summary:{total:rows.length,valid:validRows,errors:errorRows,conflicts:conflicts.length}});
  }
  const commit=url.pathname.match(/^\/api\/admin\/imports\/([^/]+)\/commit$/);if(commit&&request.method==='POST'){
    const batch=await env.DB.prepare(`SELECT id,target_test_id AS testId,status,created_by AS createdBy FROM import_batches WHERE id=?`).bind(commit[1]).first();if(!batch)return fail('NOT_FOUND','معاينة الاستيراد غير موجودة',404);if(batch.status!=='previewed')return fail('ALREADY_COMMITTED','تم اعتماد هذه المعاينة سابقًا',409);const context=await testContext(env,batch.testId);if(!context||!(await hasPermission(env,user,'import_questions',context)))return fail('FORBIDDEN','لا تملك صلاحية اعتماد هذا الاستيراد',403);
    const parsed=await body(request);if(parsed.response)return parsed.response;const value=parsed.value||{};if(!Array.isArray(value.rows)||value.rows.length>1000)return fail('VALIDATION','صفوف الاستيراد غير صالحة');const rows=await prepareRows(env,batch.testId,value.rows);await checkImages(env,user,context,rows);const actions=value.conflictActions&&typeof value.conflictActions==='object'?value.conflictActions:{};let position=Number((await env.DB.prepare(`SELECT COALESCE(MAX(position),0) AS value FROM questions WHERE test_id=?`).bind(batch.testId).first())?.value||0);const statements=[];let inserted=0,replaced=0,skipped=0;
    for(const row of rows){if(row.errors.length){skipped++;continue}if(row.existingQuestionId){const action=actions[String(row.row)]||'skip';if(action!=='replace'){skipped++;continue}statements.push(env.DB.prepare(`UPDATE questions SET text=?,options_json=?,correct_option=?,explanation=?,question_type=?,accepted_answers_json=?,image_id=? WHERE id=? AND test_id=?`).bind(row.text,JSON.stringify(row.options),row.correctOption,row.explanation||null,row.questionType,row.acceptedAnswers.length?JSON.stringify(row.acceptedAnswers):null,row.imageId,row.existingQuestionId,batch.testId));replaced++;continue}position++;statements.push(env.DB.prepare(`INSERT INTO questions(id,test_id,text,options_json,correct_option,explanation,position,question_type,accepted_answers_json,image_id) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),batch.testId,row.text,JSON.stringify(row.options),row.correctOption,row.explanation||null,position,row.questionType,row.acceptedAnswers.length?JSON.stringify(row.acceptedAnswers):null,row.imageId));inserted++}
    statements.push(env.DB.prepare(`UPDATE import_batches SET status='committed',committed_at=CURRENT_TIMESTAMP WHERE id=? AND status='previewed'`).bind(batch.id));statements.push(env.DB.prepare(`INSERT INTO audit_logs(entity,entity_id,action,by_user_id,details_json) VALUES('import',?,'commit',?,?)`).bind(batch.id,user.id,JSON.stringify({inserted,replaced,skipped,testId:batch.testId})));await env.DB.batch(statements);return json({inserted,replaced,skipped});
  }
  return null;
}
