import {loadGrants,permittedWith,resolveScope} from './access-control.js';
import {readJsonBody,readLimitedBytes,secureHeaders} from './security.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:secureHeaders({'content-type':'application/json; charset=utf-8','cache-control':'no-store'})})}
function fail(code,message,status=400){return json({error:{code,message}},status)}
function base64Url(bytes){let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function safeFileName(value){return String(value||'image').replace(/[\r\n"\\/]/g,'_').slice(0,180)}
function header(request,name,max){try{return decodeURIComponent(request.headers.get(name)||'').trim().slice(0,max)}catch{return ''}}
function tags(value){return [...new Set((Array.isArray(value)?value:String(value||'').split(/[,،]/)).map(item=>String(item).trim()).filter(Boolean))].slice(0,20)}
function magicMatches(type,bytes){if(type==='image/jpeg')return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==='image/png')return [0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a].every((value,index)=>bytes[index]===value);if(type==='image/webp')return String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';return false}
async function libraryLog(env,user,mediaId,action,details={},testId=null,questionId=null){await env.DB.prepare(`INSERT INTO library_logs(media_id,action,by_user_id,test_id,question_id,details_json) VALUES(?,?,?,?,?,?)`).bind(mediaId,action,user.id,testId,questionId,JSON.stringify(details)).run()}
async function assetContext(env,row){return resolveScope(env,row.scopeType,row.scopeId)}
async function allowed(env,user,grants,permission,row){if(user?.role==='owner')return true;const context=await assetContext(env,row);return Boolean(context&&permittedWith(grants,permission,context))}
async function selectedUploadScope(env,user,grants,request){
  if(user.role==='owner')return {scopeType:'platform',scopeId:'platform'};
  const requestedType=header(request,'x-scope-type',40),requestedId=header(request,'x-scope-id',160);let grant;
  if(requestedType&&requestedId){const context=await resolveScope(env,requestedType,requestedId);if(context&&permittedWith(grants,'manage_library',context))grant={scopeType:requestedType,scopeId:requestedId}}
  grant=grant||grants.find(item=>item.permissions.includes('manage_library'));return grant?{scopeType:grant.scopeType,scopeId:grant.scopeId}:null;
}
async function studentMayRead(env,user,mediaId){
  if(user.role!=='student'||!user.departmentId||!user.phaseId)return false;
  const row=await env.DB.prepare(`SELECT 1 AS allowed FROM questions q JOIN tests t ON t.id=q.test_id JOIN departments d ON d.id=t.department_id JOIN colleges c ON c.id=d.college_id WHERE q.image_id=? AND t.status='published' AND t.department_id=? AND t.phase_id=? AND (t.section_id IS NULL OR t.section_id=?) AND (COALESCE(t.exam_mode,'practice')!='formal' OR EXISTS(SELECT 1 FROM attempts a WHERE a.user_id=? AND a.test_id=t.id AND a.status='in_progress' AND unixepoch(COALESCE(a.deadline_at,datetime(a.started_at,'+' || (t.duration_minutes*60) || ' seconds')))>unixepoch('now'))) AND NOT EXISTS(SELECT 1 FROM academic_deleted_items z WHERE (z.resource_type='university' AND z.resource_id=c.university_id) OR (z.resource_type='college' AND z.resource_id=d.college_id) OR (z.resource_type='department' AND z.resource_id=t.department_id) OR (z.resource_type='phase' AND z.resource_id=t.phase_id) OR (z.resource_type='section' AND z.resource_id=t.section_id) OR (z.resource_type='subject' AND z.resource_id=t.subject_id) OR (z.resource_type='lecture' AND z.resource_id=t.lecture_id)) UNION ALL SELECT 1 FROM clinical_glimpses g WHERE g.image_id=? AND g.status='published' AND g.deleted_at IS NULL AND (g.publish_at IS NULL OR g.publish_at<=CURRENT_TIMESTAMP) AND (g.audience_all=1 OR EXISTS(SELECT 1 FROM clinical_glimpse_targets x WHERE x.glimpse_id=g.id AND (x.university_id IS NULL OR x.university_id=?) AND (x.college_id IS NULL OR x.college_id=?) AND (x.department_id IS NULL OR x.department_id=?) AND (x.phase_id IS NULL OR x.phase_id=?) AND NOT EXISTS(SELECT 1 FROM academic_deleted_items z WHERE (z.resource_type='university' AND z.resource_id=x.university_id) OR (z.resource_type='college' AND z.resource_id=x.college_id) OR (z.resource_type='department' AND z.resource_id=x.department_id) OR (z.resource_type='phase' AND z.resource_id=x.phase_id)))) LIMIT 1`).bind(mediaId,user.departmentId,user.phaseId,user.sectionId||'',user.id,mediaId,user.universityId||'',user.collegeId||'',user.departmentId||'',user.phaseId||'').first();return Boolean(row)
}

export async function handleMediaApi(request,env,url,user){
  const asset=url.pathname.match(/^\/api\/media\/([^/]+)$/);
  if(asset&&request.method==='GET'){
    if(!user)return fail('UNAUTHENTICATED','سجّل الدخول للمتابعة',401);if(!env.FILES)return fail('STORAGE_UNAVAILABLE','مخزن الصور غير مهيأ',503);
    const row=await env.DB.prepare(`SELECT object_key AS objectKey,original_name AS originalName,content_type AS contentType,scope_type AS scopeType,scope_id AS scopeId FROM media_assets WHERE id=? AND deleted_at IS NULL`).bind(asset[1]).first();if(!row)return fail('NOT_FOUND','الصورة غير موجودة',404);
    const grants=user.role==='owner'||user.role==='student'?[]:await loadGrants(env,user.id);const canRead=user.role==='owner'||(user.role==='student'?await studentMayRead(env,user,asset[1]):await allowed(env,user,grants,'use_media',row)||await allowed(env,user,grants,'manage_library',row));if(!canRead)return fail('FORBIDDEN','هذه الصورة خارج نطاقك أو غير مرتبطة بمحتوى متاح لك',403);
    const object=await env.FILES.get(row.objectKey);if(!object)return fail('NOT_FOUND','ملف الصورة غير موجود',404);return new Response(object.body,{headers:secureHeaders({'content-type':row.contentType,'content-disposition':`inline; filename="${safeFileName(row.originalName)}"`,'cache-control':'private, max-age=3600','x-content-type-options':'nosniff'})});
  }
  if(!url.pathname.startsWith('/api/admin/media'))return null;if(!user)return fail('UNAUTHENTICATED','سجّل الدخول للمتابعة',401);const grants=user.role==='owner'?[]:await loadGrants(env,user.id);
  if(url.pathname==='/api/admin/media/logs'&&request.method==='GET'){
    const rows=await env.DB.prepare(`SELECT l.id,l.media_id AS mediaId,l.action,l.test_id AS testId,l.question_id AS questionId,l.at,l.details_json AS detailsJson,u.name AS actorName,m.title,m.original_name AS originalName,m.scope_type AS scopeType,m.scope_id AS scopeId FROM library_logs l LEFT JOIN users u ON u.id=l.by_user_id LEFT JOIN media_assets m ON m.id=l.media_id ORDER BY l.at DESC LIMIT 500`).all();const data=[];for(const row of rows.results)if(user.role==='owner'||(row.scopeType&&(await allowed(env,user,grants,'view_library_log',row))))data.push(row);if(user.role!=='owner'&&!grants.some(item=>item.permissions.includes('view_library_log')))return fail('FORBIDDEN','لا تملك صلاحية عرض سجل المكتبة',403);return json({data});
  }
  if(url.pathname==='/api/admin/media'&&request.method==='GET'){
    const includeDeleted=user.role==='owner'&&url.searchParams.get('deleted')==='1';const rows=await env.DB.prepare(`SELECT id,original_name AS originalName,content_type AS contentType,byte_size AS byteSize,alt_text AS altText,title,clinical_question AS clinicalQuestion,explanation,correct_answer AS correctAnswer,tags_json AS tagsJson,uploaded_by AS uploadedBy,created_at AS createdAt,updated_at AS updatedAt,deleted_at AS deletedAt,scope_type AS scopeType,scope_id AS scopeId FROM media_assets ${includeDeleted?'':'WHERE deleted_at IS NULL'} ORDER BY created_at DESC LIMIT 300`).all();const data=[];for(const row of rows.results)if(await allowed(env,user,grants,'use_media',row)||await allowed(env,user,grants,'manage_library',row))data.push({...row,tags:JSON.parse(row.tagsJson||'[]')});if(user.role!=='owner'&&!grants.some(item=>item.permissions.includes('use_media')||item.permissions.includes('manage_library')))return fail('FORBIDDEN','لا تملك صلاحية استخدام مكتبة الصور',403);return json({data});
  }
  if(url.pathname==='/api/admin/media'&&request.method==='POST'){
    if(!env.FILES)return fail('STORAGE_UNAVAILABLE','مخزن الملفات غير مهيأ',503);const scope=await selectedUploadScope(env,user,grants,request);if(!scope)return fail('FORBIDDEN','رفع الصور متاح للمشرفين المخولين فقط',403);
    const contentType=String(request.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!['image/jpeg','image/png','image/webp'].includes(contentType))return fail('VALIDATION','يسمح بصور JPG وPNG وWebP فقط');const parsed=await readLimitedBytes(request,5242880);if(parsed.error)return fail(parsed.error.code,parsed.error.message,parsed.error.status);const bytes=parsed.value;if(!bytes.length||!magicMatches(contentType,bytes))return fail('INVALID_IMAGE','محتوى الملف لا يطابق نوع الصورة المعلن',400);
    const digest=base64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));const duplicate=await env.DB.prepare(`SELECT id FROM media_assets WHERE sha256=? AND scope_type=? AND scope_id=? AND deleted_at IS NULL`).bind(digest,scope.scopeType,scope.scopeId).first();if(duplicate)return json({id:duplicate.id,duplicate:true},200);
    const id=crypto.randomUUID();const objectKey=`medical-images/${new Date().toISOString().slice(0,10)}/${id}`;const originalName=safeFileName(header(request,'x-file-name',180)||'clinical-image');const altText=header(request,'x-alt-text',500)||null;const title=header(request,'x-title',160)||originalName;const clinicalQuestion=header(request,'x-clinical-question',2000)||null;const explanation=header(request,'x-explanation',5000)||null;const correctAnswer=header(request,'x-correct-answer',1000)||null;const tagList=tags(header(request,'x-tags',500));
    await env.FILES.put(objectKey,bytes,{httpMetadata:{contentType},customMetadata:{uploadedBy:user.id,scopeType:scope.scopeType,scopeId:scope.scopeId}});try{await env.DB.prepare(`INSERT INTO media_assets(id,object_key,original_name,content_type,byte_size,sha256,alt_text,title,clinical_question,explanation,correct_answer,tags_json,uploaded_by,updated_by,scope_type,scope_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,objectKey,originalName,contentType,bytes.length,digest,altText,title,clinicalQuestion,explanation,correctAnswer,JSON.stringify(tagList),user.id,user.id,scope.scopeType,scope.scopeId).run();await libraryLog(env,user,id,'upload',{contentType,byteSize:bytes.length,title,scope})}catch(error){await env.FILES.delete(objectKey);throw error}return json({id},201);
  }
  const restore=url.pathname.match(/^\/api\/admin\/media\/([^/]+)\/restore$/);if(restore&&request.method==='POST'){
    if(user.role!=='owner')return fail('FORBIDDEN','استعادة عناصر المكتبة متاحة للمالك فقط',403);const result=await env.DB.prepare(`UPDATE media_assets SET deleted_at=NULL,deleted_by=NULL,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NOT NULL`).bind(user.id,restore[1]).run();if(!Number(result.meta?.changes))return fail('NOT_FOUND','العنصر المحذوف غير موجود',404);await libraryLog(env,user,restore[1],'restore');return json({restored:true});
  }
  const adminAsset=url.pathname.match(/^\/api\/admin\/media\/([^/]+)$/);if(adminAsset&&request.method==='PATCH'){
    const row=await env.DB.prepare(`SELECT id,scope_type AS scopeType,scope_id AS scopeId FROM media_assets WHERE id=? AND deleted_at IS NULL`).bind(adminAsset[1]).first();if(!row)return fail('NOT_FOUND','الصورة غير موجودة',404);if(!(await allowed(env,user,grants,'manage_library',row)))return fail('FORBIDDEN','لا تملك صلاحية إدارة هذه الصورة',403);const parsed=await readJsonBody(request);if(parsed.error)return fail(parsed.error.code,parsed.error.message,parsed.error.status);const value=parsed.value||{},title=String(value.title||'').trim().slice(0,160),altText=String(value.altText||'').trim().slice(0,500),clinicalQuestion=String(value.clinicalQuestion||'').trim().slice(0,2000),explanation=String(value.explanation||'').trim().slice(0,5000),correctAnswer=String(value.correctAnswer||'').trim().slice(0,1000);if(title.length<2)return fail('VALIDATION','عنوان الصورة مطلوب');await env.DB.prepare(`UPDATE media_assets SET title=?,alt_text=?,clinical_question=?,explanation=?,correct_answer=?,tags_json=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(title,altText||null,clinicalQuestion||null,explanation||null,correctAnswer||null,JSON.stringify(tags(value.tags)),user.id,adminAsset[1]).run();await libraryLog(env,user,adminAsset[1],'update',{title});return json({updated:true});
  }
  if(adminAsset&&request.method==='DELETE'){
    const row=await env.DB.prepare(`SELECT object_key AS objectKey,scope_type AS scopeType,scope_id AS scopeId FROM media_assets WHERE id=?`).bind(adminAsset[1]).first();if(!row)return fail('NOT_FOUND','الصورة غير موجودة',404);if(!(await allowed(env,user,grants,'manage_library',row)))return fail('FORBIDDEN','حذف هذه الصورة خارج نطاق صلاحيتك',403);const publishedLinked=await env.DB.prepare(`SELECT (SELECT count(*) FROM questions q JOIN tests t ON t.id=q.test_id WHERE q.image_id=? AND t.status='published')+(SELECT count(*) FROM clinical_glimpses g WHERE g.image_id=? AND g.status='published' AND g.deleted_at IS NULL) AS count`).bind(adminAsset[1],adminAsset[1]).first();if(Number(publishedLinked?.count)>0)return fail('IN_USE','لا يمكن حذف صورة مرتبطة بمحتوى منشور',409);const permanent=url.searchParams.get('permanent')==='1';if(permanent){if(user.role!=='owner')return fail('FORBIDDEN','الحذف النهائي متاح لمالك المنصة فقط',403);const anyLinked=await env.DB.prepare(`SELECT (SELECT count(*) FROM questions WHERE image_id=?)+(SELECT count(*) FROM clinical_glimpses WHERE image_id=?) AS count`).bind(adminAsset[1],adminAsset[1]).first();if(Number(anyLinked?.count)>0)return fail('IN_USE','افصل الصورة عن الأسئلة واللمحات قبل حذفها نهائيًا',409);await libraryLog(env,user,adminAsset[1],'delete_forever');await env.DB.prepare(`DELETE FROM media_assets WHERE id=?`).bind(adminAsset[1]).run();await env.FILES?.delete(row.objectKey)}else{await env.DB.prepare(`UPDATE media_assets SET deleted_at=CURRENT_TIMESTAMP,deleted_by=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL`).bind(user.id,user.id,adminAsset[1]).run();await libraryLog(env,user,adminAsset[1],'soft_delete')}return new Response(null,{status:204,headers:secureHeaders()});
  }
  return null;
}
