import {loadGrants} from './access-control.js';
import {secureHeaders} from './security.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:secureHeaders({'content-type':'application/json; charset=utf-8','cache-control':'no-store'})})}
function fail(code,message,status=400){return json({error:{code,message}},status)}
function canUse(user,grants=[]){return user?.role==='owner'||grants.some(grant=>grant.permissions.includes('use_media')||grant.permissions.includes('manage_library'))}
function canUpload(user,grants=[]){return ['owner','admin','teacher'].includes(user?.role)&&(user.role==='owner'||grants.some(grant=>grant.permissions.includes('manage_library')))}
function canViewLog(user,grants=[]){return user?.role==='owner'||grants.some(grant=>grant.permissions.includes('view_library_log'))}
function base64Url(bytes){let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function safeFileName(value){return String(value||'image').replace(/[\r\n"\\/]/g,'_').slice(0,180)}
function header(request,name,max){try{return decodeURIComponent(request.headers.get(name)||'').trim().slice(0,max)}catch{return ''}}
function tags(value){return [...new Set(String(value||'').split(/[,،]/).map(item=>item.trim()).filter(Boolean))].slice(0,20)}
async function libraryLog(env,user,mediaId,action,details={},testId=null,questionId=null){await env.DB.prepare(`INSERT INTO library_logs(media_id,action,by_user_id,test_id,question_id,details_json) VALUES(?,?,?,?,?,?)`).bind(mediaId,action,user.id,testId,questionId,JSON.stringify(details)).run()}

export async function handleMediaApi(request,env,url,user){
  const asset=url.pathname.match(/^\/api\/media\/([^/]+)$/);
  if(asset&&request.method==='GET'){
    if(!user)return fail('UNAUTHENTICATED','سجّل الدخول للمتابعة',401);if(!env.FILES)return fail('STORAGE_UNAVAILABLE','مخزن الصور غير مهيأ',503);
    const row=await env.DB.prepare(`SELECT object_key AS objectKey,original_name AS originalName,content_type AS contentType FROM media_assets WHERE id=? AND deleted_at IS NULL`).bind(asset[1]).first();if(!row)return fail('NOT_FOUND','الصورة غير موجودة',404);const object=await env.FILES.get(row.objectKey);if(!object)return fail('NOT_FOUND','ملف الصورة غير موجود',404);
    return new Response(object.body,{headers:secureHeaders({'content-type':row.contentType,'content-disposition':`inline; filename="${safeFileName(row.originalName)}"`,'cache-control':'private, max-age=3600','x-content-type-options':'nosniff'})});
  }
  if(!url.pathname.startsWith('/api/admin/media'))return null;if(!user)return fail('UNAUTHENTICATED','سجّل الدخول للمتابعة',401);const grants=user.role==='owner'?[]:await loadGrants(env,user.id);
  if(url.pathname==='/api/admin/media/logs'&&request.method==='GET'){
    if(!canViewLog(user,grants))return fail('FORBIDDEN','لا تملك صلاحية عرض سجل المكتبة',403);const rows=await env.DB.prepare(`SELECT l.id,l.media_id AS mediaId,l.action,l.test_id AS testId,l.question_id AS questionId,l.at,l.details_json AS detailsJson,u.name AS actorName,m.title,m.original_name AS originalName FROM library_logs l LEFT JOIN users u ON u.id=l.by_user_id LEFT JOIN media_assets m ON m.id=l.media_id ORDER BY l.at DESC LIMIT 500`).all();return json({data:rows.results});
  }
  if(url.pathname==='/api/admin/media'&&request.method==='GET'){
    if(!canUse(user,grants))return fail('FORBIDDEN','لا تملك صلاحية استخدام مكتبة الصور',403);const includeDeleted=user.role==='owner'&&url.searchParams.get('deleted')==='1';const rows=await env.DB.prepare(`SELECT id,original_name AS originalName,content_type AS contentType,byte_size AS byteSize,alt_text AS altText,title,clinical_question AS clinicalQuestion,explanation,correct_answer AS correctAnswer,tags_json AS tagsJson,uploaded_by AS uploadedBy,created_at AS createdAt,updated_at AS updatedAt,deleted_at AS deletedAt FROM media_assets ${includeDeleted?'':'WHERE deleted_at IS NULL'} ORDER BY created_at DESC LIMIT 300`).all();return json({data:rows.results.map(row=>({...row,tags:JSON.parse(row.tagsJson||'[]')}))});
  }
  if(url.pathname==='/api/admin/media'&&request.method==='POST'){
    if(!canUpload(user,grants))return fail('FORBIDDEN','رفع الصور متاح للمشرفين المخولين فقط',403);if(!env.FILES)return fail('STORAGE_UNAVAILABLE','مخزن الملفات غير مهيأ',503);
    const contentType=String(request.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!['image/jpeg','image/png','image/webp'].includes(contentType))return fail('VALIDATION','يسمح بصور JPG وPNG وWebP فقط');const declared=Number(request.headers.get('content-length')||0);if(declared>5242880)return fail('PAYLOAD_TOO_LARGE','حجم الصورة يجب ألا يتجاوز 5MB',413);
    const bytes=new Uint8Array(await request.arrayBuffer());if(!bytes.length||bytes.length>5242880)return fail('PAYLOAD_TOO_LARGE','حجم الصورة غير صالح أو يتجاوز 5MB',413);const digest=base64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)));const duplicate=await env.DB.prepare(`SELECT id FROM media_assets WHERE sha256=? AND deleted_at IS NULL`).bind(digest).first();if(duplicate)return json({id:duplicate.id,duplicate:true},200);
    const id=crypto.randomUUID();const objectKey=`medical-images/${new Date().toISOString().slice(0,10)}/${id}`;const originalName=safeFileName(header(request,'x-file-name',180)||'clinical-image');const altText=header(request,'x-alt-text',500)||null;const title=header(request,'x-title',160)||originalName;const clinicalQuestion=header(request,'x-clinical-question',2000)||null;const explanation=header(request,'x-explanation',5000)||null;const correctAnswer=header(request,'x-correct-answer',1000)||null;const tagList=tags(header(request,'x-tags',500));
    await env.FILES.put(objectKey,bytes,{httpMetadata:{contentType},customMetadata:{uploadedBy:user.id}});try{await env.DB.prepare(`INSERT INTO media_assets(id,object_key,original_name,content_type,byte_size,sha256,alt_text,title,clinical_question,explanation,correct_answer,tags_json,uploaded_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,objectKey,originalName,contentType,bytes.length,digest,altText,title,clinicalQuestion,explanation,correctAnswer,JSON.stringify(tagList),user.id,user.id).run();await libraryLog(env,user,id,'upload',{contentType,byteSize:bytes.length,title})}catch(error){await env.FILES.delete(objectKey);throw error}return json({id},201);
  }
  const restore=url.pathname.match(/^\/api\/admin\/media\/([^/]+)\/restore$/);if(restore&&request.method==='POST'){
    if(user.role!=='owner')return fail('FORBIDDEN','استعادة عناصر المكتبة متاحة للمالك فقط',403);const result=await env.DB.prepare(`UPDATE media_assets SET deleted_at=NULL,deleted_by=NULL,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NOT NULL`).bind(user.id,restore[1]).run();if(!Number(result.meta?.changes))return fail('NOT_FOUND','العنصر المحذوف غير موجود',404);await libraryLog(env,user,restore[1],'restore');return json({restored:true});
  }
  const adminAsset=url.pathname.match(/^\/api\/admin\/media\/([^/]+)$/);if(adminAsset&&request.method==='PATCH'){
    if(!canUpload(user,grants))return fail('FORBIDDEN','لا تملك صلاحية إدارة المكتبة',403);let value;try{value=await request.json()}catch{return fail('INVALID_JSON','بيانات الطلب غير صالحة')};const title=String(value.title||'').trim().slice(0,160),altText=String(value.altText||'').trim().slice(0,500),clinicalQuestion=String(value.clinicalQuestion||'').trim().slice(0,2000),explanation=String(value.explanation||'').trim().slice(0,5000),correctAnswer=String(value.correctAnswer||'').trim().slice(0,1000);if(title.length<2)return fail('VALIDATION','عنوان الصورة مطلوب');const result=await env.DB.prepare(`UPDATE media_assets SET title=?,alt_text=?,clinical_question=?,explanation=?,correct_answer=?,tags_json=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL`).bind(title,altText||null,clinicalQuestion||null,explanation||null,correctAnswer||null,JSON.stringify(tags(value.tags)),user.id,adminAsset[1]).run();if(!Number(result.meta?.changes))return fail('NOT_FOUND','الصورة غير موجودة',404);await libraryLog(env,user,adminAsset[1],'update',{title});return json({updated:true});
  }
  if(adminAsset&&request.method==='DELETE'){
    if(!canUpload(user,grants))return fail('FORBIDDEN','حذف الصور متاح للمخولين فقط',403);const row=await env.DB.prepare(`SELECT object_key AS objectKey FROM media_assets WHERE id=?`).bind(adminAsset[1]).first();if(!row)return fail('NOT_FOUND','الصورة غير موجودة',404);const publishedLinked=await env.DB.prepare(`SELECT (SELECT count(*) FROM questions q JOIN tests t ON t.id=q.test_id WHERE q.image_id=? AND t.status='published')+(SELECT count(*) FROM clinical_glimpses g WHERE g.image_id=? AND g.status='published' AND g.deleted_at IS NULL) AS count`).bind(adminAsset[1],adminAsset[1]).first();if(Number(publishedLinked?.count)>0)return fail('IN_USE','لا يمكن حذف صورة مرتبطة بمحتوى منشور',409);const permanent=url.searchParams.get('permanent')==='1';if(permanent){if(user.role!=='owner')return fail('FORBIDDEN','الحذف النهائي متاح لمالك المنصة فقط',403);const anyLinked=await env.DB.prepare(`SELECT (SELECT count(*) FROM questions WHERE image_id=?)+(SELECT count(*) FROM clinical_glimpses WHERE image_id=?) AS count`).bind(adminAsset[1],adminAsset[1]).first();if(Number(anyLinked?.count)>0)return fail('IN_USE','افصل الصورة عن الأسئلة واللمحات قبل حذفها نهائيًا',409);await libraryLog(env,user,adminAsset[1],'delete_forever');await env.DB.prepare(`DELETE FROM media_assets WHERE id=?`).bind(adminAsset[1]).run();await env.FILES?.delete(row.objectKey)}else{await env.DB.prepare(`UPDATE media_assets SET deleted_at=CURRENT_TIMESTAMP,deleted_by=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL`).bind(user.id,user.id,adminAsset[1]).run();await libraryLog(env,user,adminAsset[1],'soft_delete')}return new Response(null,{status:204,headers:secureHeaders()});
  }
  return null;
}
