import {grantMatches,hasPermission,loadGrants} from './access-control.js';
import {accountDeviceHash} from './account-events.js';
import {readJsonBody,secureHeaders} from './security.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:secureHeaders({'content-type':'application/json; charset=utf-8','cache-control':'no-store'})})}
function fail(code,message,status=400){return json({error:{code,message}},status)}
function context(row){return {universityId:row.universityId,collegeId:row.collegeId,departmentId:row.departmentId,phaseId:row.phaseId,sectionId:row.sectionId}}
function clean(value,max=2000){return String(value||'').trim().slice(0,max)}
function nowIso(){return new Date().toISOString()}
function requestNumber(){const stamp=new Date().toISOString().slice(0,10).replace(/-/g,'');return `KIUR-BAN-${stamp}-${crypto.randomUUID().slice(0,8).toUpperCase()}`}
function duration(value,unit){const number=Number(value);const factors={minutes:60,hours:3600,days:86400};if(!Number.isInteger(number)||number<1||!factors[unit])return null;const seconds=number*factors[unit];return seconds<=90*86400?seconds:null}
async function readBody(request){const parsed=await readJsonBody(request);return parsed.error?{response:fail(parsed.error.code,parsed.error.message,parsed.error.status)}:{value:parsed.value||{}}}
async function student(env,id){return env.DB.prepare(`SELECT u.id,u.name,u.email,u.account_role AS role,u.account_status AS accountStatus,u.ban_status AS banStatus,u.ban_until AS banUntil,u.active_ban_request_id AS activeBanRequestId,u.active_ban_id AS activeBanId,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,v.name AS universityName,c.name AS collegeName,COALESCE(d.display_name,d.name) AS departmentName,p.name AS phaseName,x.name AS sectionName FROM users u LEFT JOIN universities v ON v.id=u.university_id LEFT JOIN colleges c ON c.id=u.college_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN phases p ON p.id=u.phase_id LEFT JOIN sections x ON x.id=u.section_id WHERE u.id=? AND u.account_role='student'`).bind(id).first()}
async function grantScope(env,actor,permission,targetContext){if(actor.role==='owner')return {scopeType:'platform',scopeId:'platform'};const grants=await loadGrants(env,actor.id);const grant=grants.find(item=>item.permissions.includes(permission)&&grantMatches(item,targetContext));return grant?{scopeType:grant.scopeType,scopeId:grant.scopeId}:null}
async function logStatement(env,request,{actor,student:target,requestId=null,banId=null,action,scopeType=null,scopeId=null,reason=null,evidence=null,durationSeconds=null,status=null,details={}}){const deviceHash=await accountDeviceHash(request);return env.DB.prepare(`INSERT INTO student_ban_logs(request_id,ban_id,student_id,action,by_user_id,actor_name_snapshot,actor_email_snapshot,student_name_snapshot,student_email_snapshot,scope_type,scope_id,reason_snapshot,evidence_snapshot,duration_seconds,status_snapshot,device_hash,details_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(requestId,banId,target.id,action,actor?.id||null,actor?.name||'النظام',actor?.email||null,target.name,target.email,scopeType,scopeId,reason,evidence,durationSeconds,status,deviceHash,JSON.stringify(details||{}))}

export async function refreshStudentRestriction(request,env,user){
  if(!user||user.role!=='student'||!user.banStatus||user.banStatus==='none')return {user,restriction:null};
  if(user.banUntil&&Date.parse(user.banUntil)<=Date.now()){
    const target=await student(env,user.id);let changes=0;let action='restriction_expired';
    if(user.banStatus==='precaution'){
      const result=await env.DB.prepare(`UPDATE student_ban_requests SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND student_id=? AND status='pending' AND precaution_expires_at<=CURRENT_TIMESTAMP`).bind(user.activeBanRequestId,user.id).run();changes=Number(result.meta?.changes||0);action='precaution_auto_cancelled';
    }else{
      const result=await env.DB.prepare(`UPDATE student_bans SET status='expired',updated_at=CURRENT_TIMESTAMP WHERE id=? AND student_id=? AND status IN ('active','lift_pending') AND ends_at<=CURRENT_TIMESTAMP`).bind(user.activeBanId,user.id).run();changes=Number(result.meta?.changes||0);action='temporary_ban_expired';
    }
    if(changes){await env.DB.prepare(`UPDATE users SET ban_status='none',ban_until=NULL,active_ban_request_id=NULL,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(user.id).run();try{await env.DB.batch([await logStatement(env,request,{actor:null,student:target,requestId:user.activeBanRequestId,banId:user.activeBanId,action,status:'expired'})])}catch{}return {user:{...user,banStatus:'none',banUntil:null,activeBanRequestId:null,activeBanId:null},restriction:null}}
  }
  const restriction=user.banStatus==='precaution'
    ?await env.DB.prepare(`SELECT r.id AS requestId,r.request_number AS requestNumber,r.request_type AS requestType,r.reason,r.precaution_expires_at AS endsAt,'precaution' AS banType FROM student_ban_requests r WHERE r.id=? AND r.student_id=? AND r.status='pending'`).bind(user.activeBanRequestId,user.id).first()
    :await env.DB.prepare(`SELECT b.id AS banId,r.request_number AS requestNumber,r.id AS requestId,r.request_type AS requestType,b.reason,b.ends_at AS endsAt,b.ban_type AS banType FROM student_bans b JOIN student_ban_requests r ON r.id=b.request_id WHERE b.id=? AND b.student_id=? AND b.status IN ('active','lift_pending')`).bind(user.activeBanId,user.id).first();
  return {user,restriction};
}

export function restrictedStudentPathAllowed(path,method){return (path==='/api/me'&&method==='GET')||(path==='/api/me/ban'&&method==='GET')||(path==='/api/me/ban/appeal'&&method==='POST')||(path==='/api/auth/logout'&&method==='POST')}

async function listData(env,actor,url){
  const q=clean(url.searchParams.get('q'),80);const like=`%${q}%`;const grants=actor.role==='owner'?null:await loadGrants(env,actor.id);
  const can=(permission,row)=>actor.role==='owner'||grants.some(grant=>grant.permissions.includes(permission)&&grantMatches(grant,context(row)));
  const students=await env.DB.prepare(`SELECT u.id,u.name,u.email,u.ban_status AS banStatus,u.ban_until AS banUntil,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,v.name AS universityName,c.name AS collegeName,COALESCE(d.display_name,d.name) AS departmentName,p.name AS phaseName,x.name AS sectionName FROM users u LEFT JOIN universities v ON v.id=u.university_id LEFT JOIN colleges c ON c.id=u.college_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN phases p ON p.id=u.phase_id LEFT JOIN sections x ON x.id=u.section_id WHERE u.account_role='student' AND (?='' OR u.name LIKE ? OR u.email LIKE ?) ORDER BY u.created_at DESC LIMIT 500`).bind(q,like,like).all();
  const requests=await env.DB.prepare(`SELECT r.id,r.request_number AS requestNumber,r.request_type AS requestType,r.ban_id AS banId,r.duration_value AS durationValue,r.duration_unit AS durationUnit,r.duration_seconds AS durationSeconds,r.reason,r.evidence_text AS evidenceText,r.status,r.precaution_expires_at AS precautionExpiresAt,r.requested_by AS requestedBy,r.reviewed_by AS reviewedBy,r.reviewed_at AS reviewedAt,r.review_note AS reviewNote,r.created_at AS createdAt,u.id AS studentId,u.name AS studentName,u.email AS studentEmail,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,a.name AS requesterName,a.email AS requesterEmail,z.name AS reviewerName,z.email AS reviewerEmail FROM student_ban_requests r JOIN users u ON u.id=r.student_id JOIN users a ON a.id=r.requested_by LEFT JOIN users z ON z.id=r.reviewed_by ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.created_at DESC LIMIT 500`).all();
  const bans=await env.DB.prepare(`SELECT b.id,b.request_id AS requestId,b.student_id AS studentId,b.ban_type AS banType,b.reason,b.starts_at AS startsAt,b.ends_at AS endsAt,b.status,b.approved_by AS approvedBy,b.lifted_by AS liftedBy,b.lifted_at AS liftedAt,b.lift_reason AS liftReason,u.name AS studentName,u.email AS studentEmail,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,r.request_number AS requestNumber FROM student_bans b JOIN users u ON u.id=b.student_id JOIN student_ban_requests r ON r.id=b.request_id ORDER BY b.created_at DESC LIMIT 500`).all();
  const appeals=await env.DB.prepare(`SELECT p.id,p.request_id AS requestId,p.ban_id AS banId,p.student_id AS studentId,p.reason,p.status,p.created_at AS createdAt,p.reviewed_by AS reviewedBy,p.reviewed_at AS reviewedAt,p.review_note AS reviewNote,u.name AS studentName,u.email AS studentEmail,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,COALESCE(b.ban_type,r.request_type) AS banType,r.request_number AS requestNumber FROM student_ban_appeals p JOIN users u ON u.id=p.student_id JOIN student_ban_requests r ON r.id=p.request_id LEFT JOIN student_bans b ON b.id=p.ban_id ORDER BY CASE p.status WHEN 'pending' THEN 0 ELSE 1 END,p.created_at DESC LIMIT 500`).all();
  const visibleStudents=students.results.filter(row=>can('request_student_ban',row)||can('review_student_ban',row));const visibleRequests=requests.results.filter(row=>can('request_student_ban',row)||can('review_student_ban',row));const visibleBans=bans.results.filter(row=>can('request_student_ban',row)||can('review_student_ban',row));const visibleAppeals=appeals.results.filter(row=>can('review_student_ban',row));
  let logs=[];if(actor.role==='owner'||grants.some(grant=>grant.permissions.includes('view_student_ban_log'))){const rows=await env.DB.prepare(`SELECT l.*,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId FROM student_ban_logs l JOIN users u ON u.id=l.student_id ORDER BY l.at DESC LIMIT 500`).all();logs=rows.results.filter(row=>can('view_student_ban_log',row))}
  return {students:visibleStudents,requests:visibleRequests,bans:visibleBans,appeals:visibleAppeals,logs};
}

export async function handleStudentBanApi(request,env,url,actor,restriction){
  if(url.pathname==='/api/me/ban'&&request.method==='GET')return actor?.role==='student'&&restriction?json({restriction}):fail('NOT_BANNED','لا يوجد حظر فعال',404);
  if(url.pathname==='/api/me/ban/appeal'&&request.method==='POST'){
    if(actor?.role!=='student'||!restriction?.requestId)return fail('NOT_BANNED','لا يوجد حظر قابل للاستئناف',404);const parsed=await readBody(request);if(parsed.response)return parsed.response;const reason=clean(parsed.value.reason,1000);if(reason.length<5)return fail('VALIDATION','اكتب سبب الاستئناف بوضوح');
    const id=crypto.randomUUID();try{await env.DB.batch([env.DB.prepare(`INSERT INTO student_ban_appeals(id,request_id,ban_id,student_id,reason) VALUES(?,?,?,?,?)`).bind(id,restriction.requestId,restriction.banId||null,actor.id,reason),await logStatement(env,request,{actor,student:actor,requestId:restriction.requestId,banId:restriction.banId||null,action:'student_appeal_submitted',reason,status:'pending'})])}catch{return fail('APPEAL_ALREADY_USED','تم إرسال الاستئناف الوحيد لهذا الحظر مسبقًا',409)}return json({id,submitted:true},201);
  }
  if(!url.pathname.startsWith('/api/admin/student-bans'))return null;
  if(!['owner','admin','teacher'].includes(actor?.role))return fail('FORBIDDEN','هذه الأداة للكوادر المخولة فقط',403);
  if(url.pathname==='/api/admin/student-bans'&&request.method==='GET')return json(await listData(env,actor,url));
  if(url.pathname==='/api/admin/student-bans/requests'&&request.method==='POST'){
    const parsed=await readBody(request);if(parsed.response)return parsed.response;const value=parsed.value;const target=await student(env,clean(value.studentId,100));if(!target)return fail('NOT_FOUND','الطالب غير موجود',404);const scope=await grantScope(env,actor,'request_student_ban',context(target));if(!scope)return fail('FORBIDDEN','الطالب خارج نطاق صلاحية طلب الحظر',403);if(target.banStatus!=='none')return fail('ALREADY_RESTRICTED','الطالب لديه حظر أو تعليق فعال',409);
    const type=value.banType==='permanent'?'permanent':'temporary';const seconds=type==='temporary'?duration(value.durationValue,value.durationUnit):null;if(type==='temporary'&&!seconds)return fail('VALIDATION','اختر مدة صحيحة لا تتجاوز 90 يومًا');const reason=clean(value.reason,2000);const evidence=clean(value.evidence,4000)||null;if(reason.length<5)return fail('VALIDATION','سبب الحظر مطلوب ويجب أن يكون واضحًا');const precaution=value.applyPrecaution!==false;const precautionSeconds=precaution?Math.min(24*3600,seconds||24*3600):0;const id=crypto.randomUUID();const number=requestNumber();const precautionUntil=precaution?new Date(Date.now()+precautionSeconds*1000).toISOString():null;
    const statements=[env.DB.prepare(`INSERT INTO student_ban_requests(id,request_number,student_id,request_type,duration_value,duration_unit,duration_seconds,reason,evidence_text,precaution_started_at,precaution_expires_at,requested_by,requester_scope_type,requester_scope_id) VALUES(?,?,?,?,?,?,?,?,?,${precaution?'CURRENT_TIMESTAMP':'NULL'},?,?,?,?)`).bind(id,number,target.id,type,type==='temporary'?Number(value.durationValue):null,type==='temporary'?value.durationUnit:null,seconds,reason,evidence,precautionUntil,actor.id,scope.scopeType,scope.scopeId)];if(precaution)statements.push(env.DB.prepare(`UPDATE users SET ban_status='precaution',ban_until=?,active_ban_request_id=?,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND ban_status='none'`).bind(precautionUntil,id,target.id));statements.push(await logStatement(env,request,{actor,student:target,requestId:id,action:precaution?'ban_requested_with_precaution':'ban_requested',scopeType:scope.scopeType,scopeId:scope.scopeId,reason,evidence,durationSeconds:seconds,status:'pending',details:{requestNumber:number,banType:type,precautionUntil}}));try{await env.DB.batch(statements)}catch{return fail('REQUEST_CONFLICT','يوجد طلب أو حظر فعال لهذا الطالب',409)}return json({id,requestNumber:number,precautionUntil},201);
  }
  const review=url.pathname.match(/^\/api\/admin\/student-bans\/requests\/([^/]+)\/review$/);
  if(review&&request.method==='POST'){
    const row=await env.DB.prepare(`SELECT r.*,r.student_id AS studentId,r.requested_by AS requestedBy,r.request_type AS requestType,r.duration_seconds AS durationSeconds,r.evidence_text AS evidenceText,u.name,u.email,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId FROM student_ban_requests r JOIN users u ON u.id=r.student_id WHERE r.id=?`).bind(review[1]).first();if(!row)return fail('NOT_FOUND','طلب الحظر غير موجود',404);if(row.status!=='pending')return fail('ALREADY_REVIEWED','تمت مراجعة الطلب مسبقًا',409);if(row.requestedBy===actor.id)return fail('SELF_APPROVAL_FORBIDDEN','لا يجوز لمقدم الطلب اعتماده',403);if(!(await hasPermission(env,actor,'review_student_ban',context(row))))return fail('FORBIDDEN','الطلب خارج نطاق صلاحية المراجعة',403);const parsed=await readBody(request);if(parsed.response)return parsed.response;const action=parsed.value.action==='approve'?'approve':'reject';const note=clean(parsed.value.note,2000);if(action==='reject'&&note.length<3)return fail('VALIDATION','اكتب سبب الرفض');const permanent=['permanent','lift_permanent'].includes(row.requestType);if(action==='approve'&&permanent&&actor.role!=='owner')return fail('OWNER_ONLY','اعتماد الحظر النهائي أو رفعه متاح للمالك وحده',403);const target=await student(env,row.studentId);const statements=[];
    if(action==='reject'){statements.push(env.DB.prepare(`UPDATE student_ban_requests SET status='rejected',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(actor.id,note,row.id));if(row.precaution_expires_at)statements.push(env.DB.prepare(`UPDATE users SET ban_status='none',ban_until=NULL,active_ban_request_id=NULL,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND active_ban_request_id=?`).bind(row.studentId,row.id));statements.push(await logStatement(env,request,{actor,student:target,requestId:row.id,banId:row.ban_id,action:'ban_request_rejected',scopeType:row.requester_scope_type,scopeId:row.requester_scope_id,reason:row.reason,evidence:row.evidenceText,durationSeconds:row.durationSeconds,status:'rejected',details:{reviewNote:note}}));await env.DB.batch(statements);return json({reviewed:true,status:'rejected'});}
    if(row.requestType.startsWith('lift_')){const ban=await env.DB.prepare(`SELECT * FROM student_bans WHERE id=? AND student_id=? AND status IN ('active','lift_pending')`).bind(row.ban_id,row.studentId).first();if(!ban)return fail('NOT_ACTIVE','الحظر لم يعد فعالًا',409);statements.push(env.DB.prepare(`UPDATE student_ban_requests SET status='approved',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(actor.id,note,row.id),env.DB.prepare(`UPDATE student_bans SET status='lifted',lifted_by=?,lifted_at=CURRENT_TIMESTAMP,lift_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(actor.id,row.reason,row.ban_id),env.DB.prepare(`UPDATE users SET ban_status='none',ban_until=NULL,active_ban_request_id=NULL,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND active_ban_id=?`).bind(row.studentId,row.ban_id),await logStatement(env,request,{actor,student:target,requestId:row.id,banId:row.ban_id,action:'ban_lift_approved',reason:row.reason,status:'lifted',details:{reviewNote:note}}));await env.DB.batch(statements);return json({reviewed:true,status:'approved',lifted:true});}
    const banId=crypto.randomUUID();const endsAt=row.requestType==='temporary'?new Date(Date.now()+Number(row.durationSeconds)*1000).toISOString():null;statements.push(env.DB.prepare(`INSERT INTO student_bans(id,request_id,student_id,ban_type,reason,ends_at,approved_by) VALUES(?,?,?,?,?,?,?)`).bind(banId,row.id,row.studentId,row.requestType,row.reason,endsAt,actor.id),env.DB.prepare(`UPDATE student_ban_requests SET status='approved',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(actor.id,note,row.id),env.DB.prepare(`UPDATE student_ban_appeals SET ban_id=? WHERE request_id=? AND ban_id IS NULL`).bind(banId,row.id),env.DB.prepare(`UPDATE users SET ban_status=?,ban_until=?,active_ban_request_id=?,active_ban_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(row.requestType,endsAt,row.id,banId,row.studentId),await logStatement(env,request,{actor,student:target,requestId:row.id,banId,action:'ban_approved',scopeType:row.requester_scope_type,scopeId:row.requester_scope_id,reason:row.reason,evidence:row.evidenceText,durationSeconds:row.durationSeconds,status:'active',details:{reviewNote:note,endsAt}}));await env.DB.batch(statements);return json({reviewed:true,status:'approved',banId,endsAt});
  }
  const lift=url.pathname.match(/^\/api\/admin\/student-bans\/([^/]+)\/lift-requests$/);
  if(lift&&request.method==='POST'){
    const ban=await env.DB.prepare(`SELECT b.*,u.name,u.email,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId FROM student_bans b JOIN users u ON u.id=b.student_id WHERE b.id=? AND b.status IN ('active','lift_pending')`).bind(lift[1]).first();if(!ban)return fail('NOT_FOUND','الحظر الفعال غير موجود',404);const scope=await grantScope(env,actor,'request_student_ban',context(ban));if(!scope)return fail('FORBIDDEN','الطالب خارج نطاق صلاحيتك',403);const parsed=await readBody(request);if(parsed.response)return parsed.response;const reason=clean(parsed.value.reason,2000);if(reason.length<5)return fail('VALIDATION','سبب طلب رفع الحظر مطلوب');const id=crypto.randomUUID();const number=requestNumber();const type=ban.ban_type==='permanent'?'lift_permanent':'lift_temporary';try{await env.DB.batch([env.DB.prepare(`INSERT INTO student_ban_requests(id,request_number,student_id,request_type,ban_id,reason,status,requested_by,requester_scope_type,requester_scope_id) VALUES(?,?,?,?,?,?,'pending',?,?,?)`).bind(id,number,ban.student_id,type,ban.id,reason,actor.id,scope.scopeType,scope.scopeId),env.DB.prepare(`UPDATE student_bans SET status='lift_pending',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(ban.id),await logStatement(env,request,{actor,student:ban,requestId:id,banId:ban.id,action:'ban_lift_requested',scopeType:scope.scopeType,scopeId:scope.scopeId,reason,status:'pending',details:{requestNumber:number}})])}catch{return fail('REQUEST_CONFLICT','يوجد طلب رفع قيد المراجعة',409)}return json({id,requestNumber:number},201);
  }
  const appealReview=url.pathname.match(/^\/api\/admin\/student-bans\/appeals\/([^/]+)\/review$/);
  if(appealReview&&request.method==='POST'){
    const appeal=await env.DB.prepare(`SELECT p.*,p.student_id AS studentId,r.request_type AS requestType,u.name,u.email,u.university_id AS universityId,u.college_id AS collegeId,u.department_id AS departmentId,u.phase_id AS phaseId,u.section_id AS sectionId,b.ban_type AS banType FROM student_ban_appeals p JOIN student_ban_requests r ON r.id=p.request_id LEFT JOIN student_bans b ON b.id=p.ban_id JOIN users u ON u.id=p.student_id WHERE p.id=?`).bind(appealReview[1]).first();if(!appeal)return fail('NOT_FOUND','الاستئناف غير موجود',404);if(appeal.status!=='pending')return fail('ALREADY_REVIEWED','تمت مراجعة الاستئناف',409);if(!(await hasPermission(env,actor,'review_student_ban',context(appeal))))return fail('FORBIDDEN','الاستئناف خارج نطاقك',403);const parsed=await readBody(request);if(parsed.response)return parsed.response;const action=parsed.value.action==='approve'?'approve':'reject';const note=clean(parsed.value.note,2000);if(action==='approve'&&appeal.ban_id&&appeal.banType==='permanent'&&actor.role!=='owner')return fail('OWNER_ONLY','رفع الحظر النهائي متاح للمالك وحده',403);const statements=[env.DB.prepare(`UPDATE student_ban_appeals SET status=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,review_note=? WHERE id=? AND status='pending'`).bind(action==='approve'?'approved':'rejected',actor.id,note,appeal.id)];if(action==='approve'&&appeal.ban_id)statements.push(env.DB.prepare(`UPDATE student_bans SET status='lifted',lifted_by=?,lifted_at=CURRENT_TIMESTAMP,lift_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('active','lift_pending')`).bind(actor.id,appeal.reason,appeal.ban_id),env.DB.prepare(`UPDATE users SET ban_status='none',ban_until=NULL,active_ban_request_id=NULL,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND active_ban_id=?`).bind(appeal.studentId,appeal.ban_id));if(action==='approve'&&!appeal.ban_id)statements.push(env.DB.prepare(`UPDATE student_ban_requests SET status='cancelled',reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,review_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(actor.id,'قُبل استئناف التعليق الاحترازي: '+note,appeal.request_id),env.DB.prepare(`UPDATE users SET ban_status='none',ban_until=NULL,active_ban_request_id=NULL,active_ban_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND active_ban_request_id=?`).bind(appeal.studentId,appeal.request_id));statements.push(await logStatement(env,request,{actor,student:appeal,requestId:appeal.request_id,banId:appeal.ban_id,action:action==='approve'?'student_appeal_approved':'student_appeal_rejected',reason:appeal.reason,status:action==='approve'?'lifted':'active',details:{reviewNote:note}}));await env.DB.batch(statements);return json({reviewed:true,status:action==='approve'?'approved':'rejected'});
  }
  return null;
}
