import {useEffect,useMemo,useRef,useState} from 'react';
import {BrainCircuit,Building2,CheckCircle2,ChevronLeft,Copy,ExternalLink,Eye,EyeOff,GraduationCap,HeartPulse,LoaderCircle,LockKeyhole,Mail,Microscope,ShieldCheck,Sparkles,UserRound} from 'lucide-react';
import './auth.css';
import {googleBrowserContext,prepareGoogleAuth,requestGoogleIdToken} from './firebaseGoogle';
import {ThemeToggle} from './theme-preference';

type Item={id:string;name:string;universityId?:string;collegeId?:string;departmentId?:string;phaseId?:string};
type Catalog={universities:Item[];colleges:Item[];departments:Item[];phases:Item[];sections:Item[]};
type AuthMode='login'|'register'|'activate'|'forgot'|'reset'|'action';
type ResetState='idle'|'checking'|'ready'|'invalid';
type AuthScreenProps={backgroundVideoUrl?:string|null;onAuthenticated?:()=>void|Promise<void>;onBrowse?:()=>void};
class ApiError extends Error{code:string;constructor(code:string,message:string){super(message);this.code=code}}
async function send(path:string,body:unknown){const response=await fetch(path,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new ApiError(data?.error?.code||'REQUEST_FAILED',data?.error?.message||'تعذر إكمال العملية');return data}
const DEFAULT_BACKGROUND_VIDEO='/media/kiur-auth-background.mp4';
const rememberedEmail=()=>{try{return localStorage.getItem('kiur-remembered-email')||''}catch{return ''}};
const rememberEmail=(value:string)=>{try{localStorage.setItem('kiur-remembered-email',value)}catch{}};

export default function AuthScreen({backgroundVideoUrl=DEFAULT_BACKGROUND_VIDEO,onAuthenticated,onBrowse}:AuthScreenProps){
  const query=new URLSearchParams(window.location.search);const resetCode=query.get('oobCode')||'';const emailActionMode=query.get('mode')||'';const continueUrl=query.get('continueUrl')||'';
  const supportedAction=['resetPassword','verifyEmail','recoverEmail'].includes(emailActionMode);const actionRequested=window.location.pathname==='/auth/action'||supportedAction;const malformedAction=actionRequested&&(!supportedAction||!resetCode);
  const isReset=!malformedAction&&emailActionMode==='resetPassword';const isEmailAction=!malformedAction&&['verifyEmail','recoverEmail'].includes(emailActionMode);
  const activationToken=query.get('token')||'';
  const [mode,setMode]=useState<AuthMode>(malformedAction?'action':isReset?'reset':isEmailAction?'action':window.location.pathname==='/activate-staff'&&activationToken?'activate':'login');
  const [catalog,setCatalog]=useState<Catalog|null>(null);const [message,setMessage]=useState(()=>{if(malformedAction)return 'رابط الإجراء غير مكتمل أو غير صالح. اطلب رابطًا جديدًا.';const code=query.get('authMessage')||'';return ({google_suspended:'الحساب موقوف؛ تواصل مع المشرف.',google_expired:'انتهت جلسة دخول Google؛ ابدأ من الزر مرة أخرى.',google_cancelled:'تم إلغاء دخول Google.',google_link_required:'هذا البريد مرتبط بحساب موجود. ادخل بالطريقة السابقة؛ يجب ربط هوية Firebase الموثقة قبل استخدام Google.',google_retry:'تعذر إكمال دخول Google؛ حاول مجددًا.',google_unavailable:'دخول Google غير مهيأ حاليًا.'} as Record<string,string>)[code]||''});const [busy,setBusy]=useState(false);const [success,setSuccess]=useState(false);const [canResend,setCanResend]=useState(false);
  const [resetState,setResetState]=useState<ResetState>('idle');const [resetAccount,setResetAccount]=useState('');const [continuePath,setContinuePath]=useState('/');
  const [showPassword,setShowPassword]=useState(false);const [remember,setRemember]=useState(Boolean(rememberedEmail()));const [videoReady,setVideoReady]=useState(false);const [reduceMotion,setReduceMotion]=useState(false);
  const [googleReady,setGoogleReady]=useState(false);
  const browserContext=useMemo(()=>googleBrowserContext(),[]);const [externalBrowserHelp,setExternalBrowserHelp]=useState(browserContext.embedded);
  const videoRef=useRef<HTMLVideoElement>(null);
  const emailActionStarted=useRef(false);
  const [form,setForm]=useState(()=>{let saved:any={};try{saved=JSON.parse(localStorage.getItem('kiur-guest-path')||'{}')}catch{}return {name:'',email:rememberedEmail(),password:'',universityId:saved.universityId||'',collegeId:saved.collegeId||'',departmentId:saved.departmentId||'',phaseId:saved.phaseId||'',sectionId:saved.sectionId||''}});
  useEffect(()=>{if(mode!=='register'||catalog)return;const controller=new AbortController();fetch('/api/public/catalog',{signal:controller.signal}).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>setCatalog(data)).catch(error=>{if(error.name!=='AbortError')setMessage('تعذر تحميل الهيكل الأكاديمي؛ أعد المحاولة قبل إنشاء حساب')});return()=>controller.abort()},[mode,catalog]);
  useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduceMotion(query.matches);update();query.addEventListener?.('change',update);return()=>query.removeEventListener?.('change',update)},[]);
  useEffect(()=>{let active=true;prepareGoogleAuth().then(()=>{if(active)setGoogleReady(true)}).catch(()=>{if(active)setGoogleReady(false)});return()=>{active=false}},[]);
  useEffect(()=>{const video=videoRef.current;if(!video)return;if(reduceMotion)video.pause();else void video.play().catch(()=>setVideoReady(false))},[reduceMotion]);
  useEffect(()=>{if(mode!=='reset'||resetState!=='idle')return;setResetState('checking');setBusy(true);send('/api/auth/check-password-reset',{mode:'resetPassword',oobCode:resetCode,continueUrl}).then(data=>{setResetState('ready');setResetAccount(data.maskedEmail||'');setContinuePath(data.continuePath||'/');setMessage('')}).catch(error=>{setResetState('invalid');setMessage((error as Error).message)}).finally(()=>setBusy(false))},[mode,resetState,resetCode,continueUrl]);
  useEffect(()=>{if(mode!=='action'||emailActionStarted.current||malformedAction)return;emailActionStarted.current=true;setBusy(true);send('/api/auth/apply-email-action',{mode:emailActionMode,oobCode:resetCode,continueUrl}).then(data=>{setSuccess(true);setMessage(data.message);setContinuePath(data.continuePath||'/');history.replaceState({},'', data.continuePath||'/')}).catch(error=>setMessage((error as Error).message)).finally(()=>setBusy(false))},[mode,emailActionMode,resetCode,continueUrl,malformedAction]);
  const colleges=useMemo(()=>catalog?.colleges?.filter(item=>item.universityId===form.universityId)||[],[catalog,form.universityId]);const departments=useMemo(()=>catalog?.departments?.filter(item=>item.collegeId===form.collegeId)||[],[catalog,form.collegeId]);const phases=useMemo(()=>catalog?.phases?.filter(item=>item.departmentId===form.departmentId)||[],[catalog,form.departmentId]);const sections=useMemo(()=>catalog?.sections?.filter(item=>item.phaseId===form.phaseId)||[],[catalog,form.phaseId]);
  const setPath=(key:keyof typeof form,value:string)=>{const next={...form,[key]:value};if(catalog&&key==='universityId'){const collegeId=catalog.colleges?.find(item=>item.universityId===value)?.id||'';const departmentId=catalog.departments?.find(item=>item.collegeId===collegeId)?.id||'';const phaseId=catalog.phases?.find(item=>item.departmentId===departmentId)?.id||'';Object.assign(next,{collegeId,departmentId,phaseId,sectionId:''})}if(catalog&&key==='collegeId'){const departmentId=catalog.departments?.find(item=>item.collegeId===value)?.id||'';const phaseId=catalog.phases?.find(item=>item.departmentId===departmentId)?.id||'';Object.assign(next,{departmentId,phaseId,sectionId:''})}if(catalog&&key==='departmentId'){const phaseId=catalog.phases?.find(item=>item.departmentId===value)?.id||'';Object.assign(next,{phaseId,sectionId:''})}if(key==='phaseId')next.sectionId='';setForm(next)};
  const changeMode=(next:AuthMode)=>{if(busy)return;setMode(next);setMessage('');setCanResend(false);setSuccess(false)};
  const finishLogin=async()=>{setSuccess(true);if(remember){try{localStorage.setItem('kiur-remembered-email',form.email.trim())}catch{}}else{try{localStorage.removeItem('kiur-remembered-email')}catch{}}await new Promise(resolve=>setTimeout(resolve,380));if(onAuthenticated)await onAuthenticated();else window.location.reload()};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setMessage('');setCanResend(false);setSuccess(false);try{if(mode==='reset'){const data=await send('/api/auth/reset-password',{oobCode:resetCode,password:form.password});const accountEmail=String(data.email||form.email).trim().toLowerCase();setForm({...form,email:accountEmail,password:''});if(accountEmail)rememberEmail(accountEmail);history.replaceState({},'', '/');setRemember(Boolean(accountEmail));if(data.authenticated){setSuccess(true);setMessage(data.message);await new Promise(resolve=>setTimeout(resolve,380));if(onAuthenticated)await onAuthenticated();else window.location.reload();return}setMode('login');setMessage(`${data.message} تم تثبيت بريد الحساب في خانة الدخول.`)}else if(mode==='activate'){const data=await send('/api/auth/activate-staff',{token:activationToken,password:form.password});setMessage(data.message||'تم تفعيل الحساب');history.replaceState({},'', '/');setMode('login')}else if(mode==='forgot'){const data=await send('/api/auth/forgot-password',{email:form.email});setMessage(data.message+' — افحص مجلد الرسائل غير المرغوب فيها أيضًا.')}else if(mode==='login'){await send('/api/auth/login',{email:form.email,password:form.password});await finishLogin()}else{const data=await send('/api/auth/register',form);setMessage(data.message||'تحقق من بريدك ثم سجّل الدخول مباشرة');setMode('login')}}catch(error){const issue=error as ApiError;setMessage(issue.message);setCanResend(issue.code==='EMAIL_UNVERIFIED')}finally{setBusy(false)}};
  const resend=async()=>{if(busy)return;setBusy(true);setMessage('');try{const data=await send('/api/auth/resend-verification',{email:form.email,password:form.password});setMessage(data.message);setCanResend(false)}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}};
  const googleLogin=async()=>{if(busy||!googleReady)return;if(browserContext.embedded){setExternalBrowserHelp(true);setMessage('متصفح التطبيق الداخلي لا يسمح بدخول Google بصورة موثوقة. افتح الرابط في Safari أو Chrome ثم حاول مجددًا');return}setBusy(true);setMessage('');try{await send('/api/auth/google/start',mode==='register'?{universityId:form.universityId,collegeId:form.collegeId,departmentId:form.departmentId,phaseId:form.phaseId,sectionId:form.sectionId}:{});const idToken=await requestGoogleIdToken();const data=await send('/api/auth/google/complete',{idToken});if(data.authenticated)await finishLogin();else setMessage(data.message||'تعذر فتح الحساب؛ حاول مجددًا')}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}};
  const copyCurrentLink=async()=>{try{await navigator.clipboard.writeText(window.location.href);setMessage('تم نسخ رابط KIUR. الصقه في Safari أو Chrome')}catch{setMessage('من قائمة المتصفح اختر «فتح في Safari» أو انسخ الرابط يدويًا')}};
  const title=mode==='action'?(emailActionMode==='verifyEmail'?'توثيق البريد الإلكتروني':'استعادة البريد الإلكتروني'):mode==='reset'?'تعيين كلمة مرور جديدة':mode==='activate'?'تفعيل حساب الكادر':mode==='forgot'?'استعادة كلمة المرور':mode==='register'?'ابدأ مسارك في KIUR':'مرحبًا بعودتك';
  const subtitle=mode==='action'?'يجري التحقق من رابط Google وتطبيقه بصورة آمنة.':mode==='reset'?'استخدم 8 أرقام على الأقل مع حرف واحد على الأقل.':mode==='activate'?'عيّن كلمة مرور قوية لإكمال تفعيل حسابك.':mode==='forgot'?'سنرسل إلى بريدك رابطًا آمنًا لاستعادة الحساب.':mode==='register'?'أنشئ حسابك، ثم حدّد مسارك الأكاديمي بدقة.':'سجّل الدخول وتابع مسارك الطبي من حيث توقفت.';
  const submitText=mode==='reset'?'حفظ كلمة المرور':mode==='activate'?'تفعيل الحساب':mode==='forgot'?'إرسال رابط الاستعادة':mode==='register'?'إنشاء حساب الطالب':'الدخول إلى KIUR';
  return <main className={'authPage authMode-'+mode} dir="rtl"><ThemeToggle compact/>
    <div className="authBackdrop" aria-hidden="true">
      {backgroundVideoUrl&&<video ref={videoRef} className={videoReady&&!reduceMotion?'ready':''} autoPlay={!reduceMotion} loop muted playsInline preload="metadata" onCanPlay={()=>setVideoReady(true)} onError={()=>setVideoReady(false)}><source src={backgroundVideoUrl} type="video/mp4"/></video>}
      <div className="authFallback"/><div className="authGrid"/><i className="authOrb orbOne"/><i className="authOrb orbTwo"/><i className="authOrb orbThree"/>
      <HeartPulse className="authFloat floatOne"/><BrainCircuit className="authFloat floatTwo"/><Microscope className="authFloat floatThree"/>
    </div>
    <section className="authCard hybridAuth" aria-labelledby="auth-title">
      <div className="authBrand"><span><HeartPulse/></span><div><b>KIUR</b><small>BY ERATRANS</small></div></div>
      <header className="authIntro"><span className="authEyebrow"><Sparkles/> بوابتك الطبية الذكية</span><h1 id="auth-title">{title}</h1><p>{subtitle}</p></header>
      {mode!=='activate'&&mode!=='forgot'&&mode!=='reset'&&mode!=='action'&&<>
        <button type="button" className="signinButton googleSignin" disabled={busy||!googleReady} onClick={()=>void googleLogin()}><span aria-hidden="true">G</span><span>{googleReady?(browserContext.embedded?'فتح Google في المتصفح الخارجي':'المتابعة بحساب Google'):'جارٍ تهيئة Google…'}</span><ChevronLeft/></button>
        {externalBrowserHelp&&<section className="externalBrowserHelp" role="alert"><ExternalLink/><div><b>{browserContext.ios?'افتح KIUR في Safari':'افتح KIUR في Chrome'}</b><p>{browserContext.ios?'اضغط زر ••• أعلى الشاشة ثم اختر «فتح في Safari».':'افتح قائمة التطبيق واختر «فتح في المتصفح الخارجي».'}</p></div><button type="button" onClick={()=>void copyCurrentLink()}><Copy/>نسخ الرابط</button></section>}
        <div className="authDivider"><span>أو عبر البريد الإلكتروني</span></div>
        <div className="authTabs" role="tablist" aria-label="نوع الحساب"><button type="button" role="tab" aria-selected={mode==='login'} className={mode==='login'?'active':''} onClick={()=>changeMode('login')}>تسجيل الدخول</button><button type="button" role="tab" aria-selected={mode==='register'} className={mode==='register'?'active':''} onClick={()=>changeMode('register')}>حساب طالب جديد</button></div>
      </>}
      {mode==='reset'&&resetState==='checking'&&<div className="authMessage" role="status"><LoaderCircle className="spin"/> جارٍ التحقق من صلاحية رابط الاستعادة…</div>}
      {mode==='reset'&&resetState==='ready'&&resetAccount&&<div className="authMessage resetAccount" role="status">سيتم تغيير كلمة المرور للحساب {resetAccount}</div>}
      {mode!=='action'&&(mode!=='reset'||resetState==='ready')&&<form className="emailAuth" onSubmit={event=>void submit(event)} aria-busy={busy}>
        {mode==='register'&&<label className="authField"><span>الاسم الكامل</span><div><UserRound/><input required minLength={2} maxLength={120} autoComplete="name" placeholder="مثال: حسين ماجد" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></div></label>}
        {mode!=='activate'&&mode!=='reset'&&<label className="authField"><span>البريد الإلكتروني</span><div><Mail/><input required type="email" inputMode="email" dir="ltr" autoComplete="email" placeholder="name@example.com" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></div></label>}
        {mode!=='forgot'&&<label className="authField"><span>كلمة المرور</span><div><LockKeyhole/><input required type={showPassword?'text':'password'} minLength={mode==='login'?1:9} maxLength={128} pattern={mode==='login'?undefined:'(?=(?:[^0-9]*[0-9]){8})(?=.*\\p{L}).{9,128}'} title={mode==='login'?undefined:'8 أرقام على الأقل من 0 إلى 9 مع حرف واحد على الأقل'} dir="ltr" autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='login'?'كلمة المرور':'8 أرقام مع حرف على الأقل'} value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/><button type="button" className="passwordToggle" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?'إخفاء كلمة المرور':'إظهار كلمة المرور'}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>}
        {mode==='register'&&<fieldset className="registrationPath"><legend><GraduationCap/> المسار الأكاديمي</legend><label><span>الجامعة</span><select required value={form.universityId} onChange={event=>setPath('universityId',event.target.value)}><option value="">اختر الجامعة</option>{(catalog?.universities || []).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>الكلية</span><select required value={form.collegeId} onChange={event=>setPath('collegeId',event.target.value)}><option value="">اختر الكلية</option>{colleges.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>القسم</span><select required value={form.departmentId} onChange={event=>setPath('departmentId',event.target.value)}><option value="">اختر القسم</option>{departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>المرحلة</span><select required value={form.phaseId} onChange={event=>setPath('phaseId',event.target.value)}><option value="">اختر المرحلة</option>{phases.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="sectionSelect"><span>الشعبة (اختياري)</span><select value={form.sectionId} onChange={event=>setPath('sectionId',event.target.value)}><option value="">دون شعبة محددة</option>{sections.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></fieldset>}
        {mode==='login'&&<div className="authOptions"><label className="rememberChoice"><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)}/><span aria-hidden="true"/> تذكّر بريدي</label><button type="button" className="authTextButton" onClick={()=>changeMode('forgot')}>نسيت كلمة المرور؟</button></div>}
        <button className={'emailSubmit '+(success?'success':'')} disabled={busy||success}>{success?<><CheckCircle2/> تم التحقق، جارٍ فتح المنصة…</>:busy?<><LoaderCircle className="spin"/> جارٍ التحقق…</>:<><span>{submitText}</span><ChevronLeft/></>}</button>
        {(mode==='forgot'||mode==='reset')&&<button type="button" className="authTextButton backToLogin" onClick={()=>changeMode('login')}>العودة إلى تسجيل الدخول</button>}{canResend&&<button type="button" className="authTextButton backToLogin" disabled={busy} onClick={()=>void resend()}>إعادة إرسال رسالة التحقق</button>}
      </form>}
      {message&&<div className="authMessage" role="alert">{message}</div>}
      {mode==='reset'&&resetState==='invalid'&&<button type="button" className="emailSubmit" onClick={()=>changeMode('forgot')}>طلب رابط استعادة جديد</button>}
      {mode==='action'&&!busy&&<button type="button" className="emailSubmit" onClick={()=>{if(success&&continuePath!=='/')window.location.assign(continuePath);else changeMode('login')}}>{success&&continuePath!=='/'?'المتابعة إلى المنصة':'العودة إلى تسجيل الدخول'}</button>}
      <footer className="authNote"><ShieldCheck/> {mode==='register'?'بعد توثيق البريد يمكنك الدخول مباشرة':'دخول مشفّر — لن نطلب منك مشاركة كلمة المرور'}</footer>
      {onBrowse&&mode==='login'&&<button type="button" className="authBrowse" onClick={onBrowse}>متابعة التصفح كزائر</button>}
      {mode==='login'&&<p className="authHint"><Building2/> اضغط Enter للمتابعة</p>}
    </section>
  </main>;
}
