import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Building2,Copy,GraduationCap,Plus,RotateCcw,Save,Trash2} from 'lucide-react';
import './catalog.css';

type Item={id:string;name:string;sortOrder:number;universityId?:string;collegeId?:string;departmentId?:string;phaseId?:string;subjectId?:string};
export type Catalog={universities:Item[];colleges:Item[];departments:Item[];phases:Item[];sections:Item[];subjects:Item[];lectures:Item[]};
type CopyResult={id:string;name:string;counts:{departments:number;phases:number;sections:number;subjects:number;lectures:number}};

async function request<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===204)return undefined as T;const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}

function Row({item,active,badge,onSelect,onSave,onDelete}:{item:Item;active?:boolean;badge?:string;onSelect?:()=>void;onSave:(name:string)=>Promise<void>;onDelete?:()=>Promise<void>}){
  const [name,setName]=useState(item.name);const [busy,setBusy]=useState(false);useEffect(()=>setName(item.name),[item.name]);
  const remove=()=>{if(!onDelete||!confirm(`نقل «${item.name}» وما يتبعه إلى المحذوفات؟`))return;setBusy(true);void onDelete().finally(()=>setBusy(false))};
  return <div className={'catalogRow '+(active?'active':'')} onClick={onSelect}><input value={name} onClick={event=>event.stopPropagation()} onChange={event=>setName(event.target.value)}/>{badge&&<span className="countBadge">{badge}</span>}<button className="saveMini" aria-label={'حفظ '+item.name} disabled={busy||name.trim()===item.name||name.trim().length<2} onClick={event=>{event.stopPropagation();setBusy(true);void onSave(name.trim()).finally(()=>setBusy(false))}}><Save/></button>{onDelete&&<button className="deleteMini" aria-label={'حذف '+item.name} disabled={busy} onClick={event=>{event.stopPropagation();remove()}}><Trash2/></button>}</div>
}
function Add({placeholder,onAdd}:{placeholder:string;onAdd:(name:string)=>Promise<void>}){const [name,setName]=useState('');const [busy,setBusy]=useState(false);return <div className="catalogAdd"><input value={name} onChange={event=>setName(event.target.value)} placeholder={placeholder}/><button disabled={busy||name.trim().length<2} onClick={()=>{setBusy(true);void onAdd(name.trim()).then(()=>setName('')).finally(()=>setBusy(false))}}><Plus/>إضافة</button></div>}
function Panel({title,subtitle,items,selected,onSelect,onAdd,onSave,onDelete,badge}:{title:string;subtitle:string;items:Item[];selected:string;onSelect:(id:string)=>void;onAdd?:(name:string)=>Promise<void>;onSave:(id:string,name:string)=>Promise<void>;onDelete?:(id:string)=>Promise<void>;badge?:(item:Item)=>string}){return <section className="catalogBox"><header><div><b>{title}</b><small>{subtitle}</small></div><span className="largeCount">{items.length}</span></header>{onAdd&&<Add placeholder={'إضافة '+title} onAdd={onAdd}/>}<div className="catalogList">{items.map(item=><Row key={item.id} item={item} active={item.id===selected} badge={badge?.(item)} onSelect={()=>onSelect(item.id)} onSave={name=>onSave(item.id,name)} onDelete={onDelete?()=>onDelete(item.id):undefined}/>)}</div>{!items.length&&<div className="catalogEmpty">لا توجد بيانات هنا بعد.</div>}</section>}

export default function CatalogManagerV2({catalog,reload,notify,currentRole,permissions=[]}:{catalog:Catalog;reload:()=>Promise<Catalog>;notify:(message:string)=>void;currentRole:'owner'|'admin'|'teacher'|'student';permissions?:string[]}){
  const [working,setWorking]=useState(catalog);const [trash,setTrash]=useState<any[]>([]);const canDelete=currentRole==='owner'||permissions.includes('delete_catalog');
  useEffect(()=>setWorking(catalog),[catalog]);
  const [universityId,setUniversityId]=useState(working.universities[0]?.id||'');
  const colleges=useMemo(()=>working.colleges.filter(item=>item.universityId===universityId),[working,universityId]);
  const [collegeId,setCollegeId]=useState(colleges[0]?.id||'');
  const departments=useMemo(()=>working.departments.filter(item=>item.collegeId===collegeId),[working,collegeId]);
  const [departmentId,setDepartmentId]=useState(departments[0]?.id||'');
  const phases=useMemo(()=>working.phases.filter(item=>item.departmentId===departmentId),[working,departmentId]);
  const [phaseId,setPhaseId]=useState(phases[0]?.id||'');
  const sections=useMemo(()=>working.sections.filter(item=>item.phaseId===phaseId),[working,phaseId]);
  const subjects=useMemo(()=>working.subjects.filter(item=>item.phaseId===phaseId),[working,phaseId]);
  const [subjectId,setSubjectId]=useState(subjects[0]?.id||'');
  const lectures=useMemo(()=>working.lectures.filter(item=>item.subjectId===subjectId),[working,subjectId]);
  const sourceCollege=useMemo(()=>working.colleges.find(item=>item.id===collegeId),[working,collegeId]);
  const copyTargets=useMemo(()=>working.universities.filter(item=>item.id!==sourceCollege?.universityId),[working,sourceCollege]);
  const [copyTargetUniversityId,setCopyTargetUniversityId]=useState(copyTargets[0]?.id||'');
  const [copyName,setCopyName]=useState(sourceCollege?sourceCollege.name+' - نسخة':'');
  const [copyBusy,setCopyBusy]=useState(false);

  useEffect(()=>{if(!colleges.some(item=>item.id===collegeId))setCollegeId(colleges[0]?.id||'')},[colleges]);
  useEffect(()=>{if(!departments.some(item=>item.id===departmentId))setDepartmentId(departments[0]?.id||'')},[departments]);
  useEffect(()=>{if(!phases.some(item=>item.id===phaseId))setPhaseId(phases[0]?.id||'')},[phases]);
  useEffect(()=>{if(!subjects.some(item=>item.id===subjectId))setSubjectId(subjects[0]?.id||'')},[subjects]);
  useEffect(()=>{if(!copyTargets.some(item=>item.id===copyTargetUniversityId))setCopyTargetUniversityId(copyTargets[0]?.id||'')},[copyTargets,copyTargetUniversityId]);
  useEffect(()=>setCopyName(sourceCollege?sourceCollege.name+' - نسخة':''),[sourceCollege?.id]);
  useEffect(()=>{if(canDelete)void request<{data:any[]}>('/api/admin/academic-trash').then(result=>setTrash(result.data)).catch(()=>setTrash([]))},[canDelete]);

  const add=(plural:keyof Catalog,body:Record<string,string>,message:string)=>async(name:string)=>{const temporaryId='pending-'+crypto.randomUUID();const optimistic={id:temporaryId,name,sortOrder:9999,...body} as Item;setWorking(value=>({...value,[plural]:[...value[plural],optimistic]}));try{const result=await request<{id:string}>(`/api/admin/${plural}`,{method:'POST',body:JSON.stringify({...body,name})});setWorking(value=>({...value,[plural]:value[plural].map(item=>item.id===temporaryId?{...item,id:result.id}:item)}));notify(message);void reload().catch(()=>undefined)}catch(error){setWorking(value=>({...value,[plural]:value[plural].filter(item=>item.id!==temporaryId)}));notify((error as Error).message);throw error}};
  const panel=(plural:keyof Catalog)=>(id:string,name:string)=>{const before=working;setWorking(value=>({...value,[plural]:value[plural].map(item=>item.id===id?{...item,name}:item)}));return request(`/api/admin/${plural}/${id}`,{method:'PATCH',body:JSON.stringify({name})}).then(()=>{notify('تم حفظ الاسم');void reload().catch(()=>undefined)}).catch(error=>{setWorking(before);notify((error as Error).message);throw error})};
  const descendants=(plural:keyof Catalog,id:string,value:Catalog)=>{const remove:{[K in keyof Catalog]:Set<string>}={universities:new Set(),colleges:new Set(),departments:new Set(),phases:new Set(),sections:new Set(),subjects:new Set(),lectures:new Set()};remove[plural].add(id);let changed=true;while(changed){changed=false;for(const item of value.colleges)if(remove.universities.has(item.universityId||'')&&!remove.colleges.has(item.id)){remove.colleges.add(item.id);changed=true}for(const item of value.departments)if(remove.colleges.has(item.collegeId||'')&&!remove.departments.has(item.id)){remove.departments.add(item.id);changed=true}for(const item of value.phases)if(remove.departments.has(item.departmentId||'')&&!remove.phases.has(item.id)){remove.phases.add(item.id);changed=true}for(const item of value.sections)if(remove.phases.has(item.phaseId||'')&&!remove.sections.has(item.id)){remove.sections.add(item.id);changed=true}for(const item of value.subjects)if(remove.phases.has(item.phaseId||'')&&!remove.subjects.has(item.id)){remove.subjects.add(item.id);changed=true}for(const item of value.lectures)if(remove.subjects.has(item.subjectId||'')&&!remove.lectures.has(item.id)){remove.lectures.add(item.id);changed=true}}return remove};
  const remove=(plural:keyof Catalog)=>(id:string)=>{const before=working;const hidden=descendants(plural,id,before);setWorking(value=>Object.fromEntries(Object.entries(value).map(([key,items])=>[key,(items as Item[]).filter(item=>!hidden[key as keyof Catalog].has(item.id))])) as Catalog);return request<{batchId:string}>(`/api/admin/${plural}/${id}`,{method:'DELETE'}).then(async()=>{notify('تم النقل إلى المحذوفات ويمكن استعادته');const result=await request<{data:any[]}>('/api/admin/academic-trash');setTrash(result.data);void reload().catch(()=>undefined)}).catch(error=>{setWorking(before);notify((error as Error).message);throw error})};
  const restore=async(id:string)=>{try{await request(`/api/admin/academic-trash/${id}`,{method:'POST',body:'{}'});setTrash(value=>value.filter(item=>item.id!==id));await reload();notify('تمت استعادة العنصر وكل ما يتبعه')}catch(error){notify((error as Error).message)}};
  const sourceCounts=useMemo(()=>{const departmentIds=new Set(working.departments.filter(item=>item.collegeId===collegeId).map(item=>item.id));const phaseIds=new Set(working.phases.filter(item=>departmentIds.has(item.departmentId||'')).map(item=>item.id));const subjectIds=new Set(working.subjects.filter(item=>phaseIds.has(item.phaseId||'')).map(item=>item.id));return {departments:departmentIds.size,phases:phaseIds.size,sections:working.sections.filter(item=>phaseIds.has(item.phaseId||'')).length,subjects:subjectIds.size,lectures:working.lectures.filter(item=>subjectIds.has(item.subjectId||'')).length}},[working,collegeId]);
  const copyCollege=async()=>{if(!sourceCollege||!copyTargetUniversityId||copyName.trim().length<2)return;const target=working.universities.find(item=>item.id===copyTargetUniversityId);if(!confirm(`نسخ «${sourceCollege.name}» إلى «${target?.name}»؟\nسيتم إنشاء نسخة مستقلة من الهيكل الأكاديمي دون الاختبارات والحسابات.`))return;setCopyBusy(true);try{const result=await request<CopyResult>(`/api/admin/colleges/${sourceCollege.id}/copy`,{method:'POST',body:JSON.stringify({targetUniversityId:copyTargetUniversityId,name:copyName.trim()})});await reload();setUniversityId(copyTargetUniversityId);setCollegeId(result.id);notify(`تم نسخ الكلية: ${result.counts.departments} أقسام، ${result.counts.phases} مراحل، ${result.counts.subjects} مواد و${result.counts.lectures} محاضرات`)}catch(error){notify((error as Error).message)}finally{setCopyBusy(false)}};

  return <section className="catalogManager">
    <div className="catalogSummary"><article><span><Building2/></span><b>{working.universities.length}</b><small>جامعات</small></article><article><span><Building2/></span><b>{working.colleges.length}</b><small>كليات</small></article><article><span><GraduationCap/></span><b>{working.departments.length}</b><small>أقسام</small></article><article><span><BookOpen/></span><b>{working.lectures.length}</b><small>محاضرات</small></article></div>
    <section className="collegeCopy panel"><span className="copyIcon"><Copy/></span><div className="copyIntro"><b>نسخ كلية إلى جامعة أخرى</b><small>{sourceCollege?`سيُنسخ ${sourceCounts.departments} أقسام، ${sourceCounts.phases} مراحل، ${sourceCounts.sections} شُعب، ${sourceCounts.subjects} مواد و${sourceCounts.lectures} محاضرات.`:'اختر كلية مصدر أولًا.'}</small></div><input aria-label="اسم الكلية الجديدة" value={copyName} onChange={event=>setCopyName(event.target.value)} placeholder="اسم الكلية في الجامعة الجديدة"/><select aria-label="الجامعة الهدف" value={copyTargetUniversityId} onChange={event=>setCopyTargetUniversityId(event.target.value)}><option value="">اختر الجامعة الهدف</option>{copyTargets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="solid" disabled={copyBusy||!sourceCollege||!copyTargetUniversityId||copyName.trim().length<2} onClick={()=>void copyCollege()}><Copy/>{copyBusy?'جارٍ النسخ...':'نسخ الكلية'}</button><p>لا تُنسخ الاختبارات أو حسابات الطلاب أو الصلاحيات؛ النسخة الأكاديمية مستقلة ويمكن تعديلها بأمان.</p></section>
    <div className="catalogColumns catalogWide"><Panel title="الجامعات" subtitle="أعلى مستوى تنظيمي" items={working.universities} selected={universityId} onSelect={setUniversityId} onAdd={add('universities',{},'تمت إضافة الجامعة')} onSave={panel('universities')} onDelete={canDelete?remove('universities'):undefined}/><Panel title="الكليات" subtitle={working.universities.find(item=>item.id===universityId)?.name||'اختر جامعة'} items={colleges} selected={collegeId} onSelect={setCollegeId} onAdd={universityId?add('colleges',{universityId},'تمت إضافة الكلية'):undefined} onSave={panel('colleges')} onDelete={canDelete?remove('colleges'):undefined}/><Panel title="الأقسام" subtitle={colleges.find(item=>item.id===collegeId)?.name||'اختر كلية'} items={departments} selected={departmentId} onSelect={setDepartmentId} onAdd={collegeId?add('departments',{collegeId},'تمت إضافة القسم'):undefined} onSave={panel('departments')} onDelete={canDelete?remove('departments'):undefined}/><Panel title="المراحل" subtitle={departments.find(item=>item.id===departmentId)?.name||'اختر قسمًا'} items={phases} selected={phaseId} onSelect={setPhaseId} onAdd={departmentId?add('phases',{departmentId},'تمت إضافة المرحلة'):undefined} onSave={panel('phases')} onDelete={canDelete?remove('phases'):undefined}/><Panel title="الشُعب" subtitle={phases.find(item=>item.id===phaseId)?.name||'اختر مرحلة'} items={sections} selected="" onSelect={()=>{}} onAdd={phaseId?add('sections',{phaseId},'تمت إضافة الشعبة'):undefined} onSave={panel('sections')} onDelete={canDelete?remove('sections'):undefined}/><Panel title="المواد" subtitle={phases.find(item=>item.id===phaseId)?.name||'اختر مرحلة'} items={subjects} selected={subjectId} onSelect={setSubjectId} onAdd={phaseId?add('subjects',{phaseId},'تمت إضافة المادة'):undefined} onSave={panel('subjects')} onDelete={canDelete?remove('subjects'):undefined} badge={item=>working.lectures.filter(lecture=>lecture.subjectId===item.id).length+' محاضرة'}/><Panel title="المحاضرات" subtitle={subjects.find(item=>item.id===subjectId)?.name||'اختر مادة'} items={lectures} selected="" onSelect={()=>{}} onAdd={subjectId?add('lectures',{subjectId},'تمت إضافة المحاضرة'):undefined} onSave={panel('lectures')} onDelete={canDelete?remove('lectures'):undefined}/></div>
    {canDelete&&<section className="panel catalogTrash"><header><div><b>المحذوفات الأكاديمية</b><small>حذف ناعم يحفظ الاختبارات والسجلات، ويمكن الاستعادة بنقرة واحدة.</small></div><span className="largeCount">{trash.length}</span></header>{trash.map(item=><article key={item.id}><div><b>{item.resourceName}</b><small>{item.resourceType} • {new Intl.DateTimeFormat('ar-IQ',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.deletedAt))}</small></div><button type="button" onClick={()=>void restore(item.id)}><RotateCcw/> استعادة</button></article>)}{!trash.length&&<div className="catalogEmpty">المحذوفات فارغة.</div>}</section>}
    <p className="catalogNote">تظهر الإضافة والتعديل والحذف فورًا، ثم يؤكدها الخادم في الخلفية مع تراجع آمن عند الخطأ.</p>
  </section>;
}
