import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Building2,Copy,GraduationCap,Plus,Save,Trash2} from 'lucide-react';
import './catalog.css';

type Item={id:string;name:string;sortOrder:number;universityId?:string;collegeId?:string;departmentId?:string;phaseId?:string;subjectId?:string};
export type Catalog={universities:Item[];colleges:Item[];departments:Item[];phases:Item[];sections:Item[];subjects:Item[];lectures:Item[]};
type CopyResult={id:string;name:string;counts:{departments:number;phases:number;sections:number;subjects:number;lectures:number}};

async function request<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===204)return undefined as T;const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}

function Row({item,active,badge,onSelect,onSave,onDelete}:{item:Item;active?:boolean;badge?:string;onSelect?:()=>void;onSave:(name:string)=>Promise<void>;onDelete:()=>Promise<void>}){const [name,setName]=useState(item.name);const [busy,setBusy]=useState(false);useEffect(()=>setName(item.name),[item.name]);return <div className={'catalogRow '+(active?'active':'')} onClick={onSelect}><input value={name} onClick={event=>event.stopPropagation()} onChange={event=>setName(event.target.value)}/>{badge&&<span className="countBadge">{badge}</span>}<button className="saveMini" aria-label={'حفظ '+item.name} disabled={busy||name.trim()===item.name||name.trim().length<2} onClick={event=>{event.stopPropagation();setBusy(true);void onSave(name.trim()).finally(()=>setBusy(false))}}><Save/></button><button className="deleteMini" aria-label={'حذف '+item.name} disabled={busy} onClick={event=>{event.stopPropagation();if(confirm(`حذف «${item.name}»؟`)){setBusy(true);void onDelete().finally(()=>setBusy(false))}}}><Trash2/></button></div>}
function Add({placeholder,onAdd}:{placeholder:string;onAdd:(name:string)=>Promise<void>}){const [name,setName]=useState('');const [busy,setBusy]=useState(false);return <div className="catalogAdd"><input value={name} onChange={event=>setName(event.target.value)} placeholder={placeholder}/><button disabled={busy||name.trim().length<2} onClick={()=>{setBusy(true);void onAdd(name.trim()).then(()=>setName('')).finally(()=>setBusy(false))}}><Plus/>إضافة</button></div>}
function Panel({title,subtitle,items,selected,onSelect,onAdd,onSave,onDelete,badge}:{title:string;subtitle:string;items:Item[];selected:string;onSelect:(id:string)=>void;onAdd?:(name:string)=>Promise<void>;onSave:(id:string,name:string)=>Promise<void>;onDelete:(id:string)=>Promise<void>;badge?:(item:Item)=>string}){return <section className="catalogBox"><header><div><b>{title}</b><small>{subtitle}</small></div><span className="largeCount">{items.length}</span></header>{onAdd&&<Add placeholder={'إضافة '+title} onAdd={onAdd}/>}<div className="catalogList">{items.map(item=><Row key={item.id} item={item} active={item.id===selected} badge={badge?.(item)} onSelect={()=>onSelect(item.id)} onSave={name=>onSave(item.id,name)} onDelete={()=>onDelete(item.id)}/>)}</div>{!items.length&&<div className="catalogEmpty">لا توجد بيانات هنا بعد.</div>}</section>}

export default function CatalogManagerV2({catalog,reload,notify}:{catalog:Catalog;reload:()=>Promise<Catalog>;notify:(message:string)=>void}){
  const [universityId,setUniversityId]=useState(catalog.universities[0]?.id||'');
  const colleges=useMemo(()=>catalog.colleges.filter(item=>item.universityId===universityId),[catalog,universityId]);
  const [collegeId,setCollegeId]=useState(colleges[0]?.id||'');
  const departments=useMemo(()=>catalog.departments.filter(item=>item.collegeId===collegeId),[catalog,collegeId]);
  const [departmentId,setDepartmentId]=useState(departments[0]?.id||'');
  const phases=useMemo(()=>catalog.phases.filter(item=>item.departmentId===departmentId),[catalog,departmentId]);
  const [phaseId,setPhaseId]=useState(phases[0]?.id||'');
  const sections=useMemo(()=>catalog.sections.filter(item=>item.phaseId===phaseId),[catalog,phaseId]);
  const subjects=useMemo(()=>catalog.subjects.filter(item=>item.phaseId===phaseId),[catalog,phaseId]);
  const [subjectId,setSubjectId]=useState(subjects[0]?.id||'');
  const lectures=useMemo(()=>catalog.lectures.filter(item=>item.subjectId===subjectId),[catalog,subjectId]);
  const sourceCollege=useMemo(()=>catalog.colleges.find(item=>item.id===collegeId),[catalog,collegeId]);
  const copyTargets=useMemo(()=>catalog.universities.filter(item=>item.id!==sourceCollege?.universityId),[catalog,sourceCollege]);
  const [copyTargetUniversityId,setCopyTargetUniversityId]=useState(copyTargets[0]?.id||'');
  const [copyName,setCopyName]=useState(sourceCollege?sourceCollege.name+' - نسخة':'');
  const [copyBusy,setCopyBusy]=useState(false);

  useEffect(()=>{if(!colleges.some(item=>item.id===collegeId))setCollegeId(colleges[0]?.id||'')},[colleges]);
  useEffect(()=>{if(!departments.some(item=>item.id===departmentId))setDepartmentId(departments[0]?.id||'')},[departments]);
  useEffect(()=>{if(!phases.some(item=>item.id===phaseId))setPhaseId(phases[0]?.id||'')},[phases]);
  useEffect(()=>{if(!subjects.some(item=>item.id===subjectId))setSubjectId(subjects[0]?.id||'')},[subjects]);
  useEffect(()=>{if(!copyTargets.some(item=>item.id===copyTargetUniversityId))setCopyTargetUniversityId(copyTargets[0]?.id||'')},[copyTargets,copyTargetUniversityId]);
  useEffect(()=>setCopyName(sourceCollege?sourceCollege.name+' - نسخة':''),[sourceCollege?.id]);

  const mutate=async(path:string,method:string,body:unknown,message:string)=>{try{const result=await request<{id?:string}>(path,{method,body:body===undefined?undefined:JSON.stringify(body)});await reload();notify(message);return result}catch(error){notify((error as Error).message);throw error}};
  const panel=(plural:string)=>(id:string,name:string)=>mutate(`/api/admin/${plural}/${id}`,'PATCH',{name},'تم حفظ الاسم').then(()=>undefined);
  const remove=(plural:string)=>(id:string)=>mutate(`/api/admin/${plural}/${id}`,'DELETE',undefined,'تم الحذف').then(()=>undefined);
  const sourceCounts=useMemo(()=>{const departmentIds=new Set(catalog.departments.filter(item=>item.collegeId===collegeId).map(item=>item.id));const phaseIds=new Set(catalog.phases.filter(item=>departmentIds.has(item.departmentId||'')).map(item=>item.id));const subjectIds=new Set(catalog.subjects.filter(item=>phaseIds.has(item.phaseId||'')).map(item=>item.id));return {departments:departmentIds.size,phases:phaseIds.size,sections:catalog.sections.filter(item=>phaseIds.has(item.phaseId||'')).length,subjects:subjectIds.size,lectures:catalog.lectures.filter(item=>subjectIds.has(item.subjectId||'')).length}},[catalog,collegeId]);
  const copyCollege=async()=>{if(!sourceCollege||!copyTargetUniversityId||copyName.trim().length<2)return;const target=catalog.universities.find(item=>item.id===copyTargetUniversityId);if(!confirm(`نسخ «${sourceCollege.name}» إلى «${target?.name}»؟\nسيتم إنشاء نسخة مستقلة من الهيكل الأكاديمي دون الاختبارات والحسابات.`))return;setCopyBusy(true);try{const result=await request<CopyResult>(`/api/admin/colleges/${sourceCollege.id}/copy`,{method:'POST',body:JSON.stringify({targetUniversityId:copyTargetUniversityId,name:copyName.trim()})});await reload();setUniversityId(copyTargetUniversityId);setCollegeId(result.id);notify(`تم نسخ الكلية: ${result.counts.departments} أقسام، ${result.counts.phases} مراحل، ${result.counts.subjects} مواد و${result.counts.lectures} محاضرات`)}catch(error){notify((error as Error).message)}finally{setCopyBusy(false)}};

  return <section className="catalogManager">
    <div className="catalogSummary"><article><span><Building2/></span><b>{catalog.universities.length}</b><small>جامعات</small></article><article><span><Building2/></span><b>{catalog.colleges.length}</b><small>كليات</small></article><article><span><GraduationCap/></span><b>{catalog.departments.length}</b><small>أقسام</small></article><article><span><BookOpen/></span><b>{catalog.lectures.length}</b><small>محاضرات</small></article></div>
    <section className="collegeCopy panel"><span className="copyIcon"><Copy/></span><div className="copyIntro"><b>نسخ كلية إلى جامعة أخرى</b><small>{sourceCollege?`سيُنسخ ${sourceCounts.departments} أقسام، ${sourceCounts.phases} مراحل، ${sourceCounts.sections} شُعب، ${sourceCounts.subjects} مواد و${sourceCounts.lectures} محاضرات.`:'اختر كلية مصدر أولًا.'}</small></div><input aria-label="اسم الكلية الجديدة" value={copyName} onChange={event=>setCopyName(event.target.value)} placeholder="اسم الكلية في الجامعة الجديدة"/><select aria-label="الجامعة الهدف" value={copyTargetUniversityId} onChange={event=>setCopyTargetUniversityId(event.target.value)}><option value="">اختر الجامعة الهدف</option>{copyTargets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="solid" disabled={copyBusy||!sourceCollege||!copyTargetUniversityId||copyName.trim().length<2} onClick={()=>void copyCollege()}><Copy/>{copyBusy?'جارٍ النسخ...':'نسخ الكلية'}</button><p>لا تُنسخ الاختبارات أو حسابات الطلاب أو الصلاحيات؛ النسخة الأكاديمية مستقلة ويمكن تعديلها بأمان.</p></section>
    <div className="catalogColumns catalogWide"><Panel title="الجامعات" subtitle="أعلى مستوى تنظيمي" items={catalog.universities} selected={universityId} onSelect={setUniversityId} onAdd={name=>mutate('/api/admin/universities','POST',{name},'تمت إضافة الجامعة').then(()=>undefined)} onSave={panel('universities')} onDelete={remove('universities')}/><Panel title="الكليات" subtitle={catalog.universities.find(item=>item.id===universityId)?.name||'اختر جامعة'} items={colleges} selected={collegeId} onSelect={setCollegeId} onAdd={universityId?name=>mutate('/api/admin/colleges','POST',{name,universityId},'تمت إضافة الكلية').then(()=>undefined):undefined} onSave={panel('colleges')} onDelete={remove('colleges')}/><Panel title="الأقسام" subtitle={colleges.find(item=>item.id===collegeId)?.name||'اختر كلية'} items={departments} selected={departmentId} onSelect={setDepartmentId} onAdd={collegeId?name=>mutate('/api/admin/departments','POST',{name,collegeId},'تمت إضافة القسم').then(()=>undefined):undefined} onSave={panel('departments')} onDelete={remove('departments')}/><Panel title="المراحل" subtitle={departments.find(item=>item.id===departmentId)?.name||'اختر قسمًا'} items={phases} selected={phaseId} onSelect={setPhaseId} onAdd={departmentId?name=>mutate('/api/admin/phases','POST',{name,departmentId},'تمت إضافة المرحلة').then(()=>undefined):undefined} onSave={panel('phases')} onDelete={remove('phases')}/><Panel title="الشُعب" subtitle={phases.find(item=>item.id===phaseId)?.name||'اختر مرحلة'} items={sections} selected="" onSelect={()=>{}} onAdd={phaseId?name=>mutate('/api/admin/sections','POST',{name,phaseId},'تمت إضافة الشعبة').then(()=>undefined):undefined} onSave={panel('sections')} onDelete={remove('sections')}/><Panel title="المواد" subtitle={phases.find(item=>item.id===phaseId)?.name||'اختر مرحلة'} items={subjects} selected={subjectId} onSelect={setSubjectId} onAdd={phaseId?name=>mutate('/api/admin/subjects','POST',{name,phaseId},'تمت إضافة المادة').then(()=>undefined):undefined} onSave={panel('subjects')} onDelete={remove('subjects')} badge={item=>catalog.lectures.filter(lecture=>lecture.subjectId===item.id).length+' محاضرة'}/><Panel title="المحاضرات" subtitle={subjects.find(item=>item.id===subjectId)?.name||'اختر مادة'} items={lectures} selected="" onSelect={()=>{}} onAdd={subjectId?name=>mutate('/api/admin/lectures','POST',{name,subjectId},'تمت إضافة المحاضرة').then(()=>undefined):undefined} onSave={panel('lectures')} onDelete={remove('lectures')}/></div>
    <p className="catalogNote">يحمي النظام العناصر المرتبطة بطلاب أو اختبارات أو صلاحيات من الحذف، مع السماح بتعديل أسمائها.</p>
  </section>;
}
