import {useState} from 'react';
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,Upload} from 'lucide-react';
import './imports.css';

type Test={id:string;title:string;subjectName?:string;lectureName?:string};type PreviewRow={row:number;questionType:string;text:string;options:string[];correctOption:number;acceptedAnswers:string[];explanation:string;imageId?:string|null;errors:string[];existingQuestionId?:string};
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}
const aliases:Record<string,string>={'نوع السؤال':'type','type':'type','نص السؤال':'text','question':'text','text':'text','الخيار أ':'optionA','a':'optionA','الخيار ب':'optionB','b':'optionB','الخيار ج':'optionC','c':'optionC','الخيار د':'optionD','d':'optionD','الإجابة الصحيحة':'correctAnswer','answer':'correctAnswer','الإجابات المقبولة':'acceptedAnswers','accepted answers':'acceptedAnswers','الشرح':'explanation','explanation':'explanation','معرف الصورة':'imageId','image id':'imageId'};
function normalizeHeader(value:unknown){return String(value||'').trim().toLocaleLowerCase('ar')}
async function excelRows(file:File){const ExcelJS=await import('exceljs');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)return [];const headers:string[]=[];sheet.getRow(1).eachCell((cell,column)=>{headers[column]=aliases[normalizeHeader(cell.text)]||normalizeHeader(cell.text)});const rows:Record<string,string>[]=[];sheet.eachRow((row,index)=>{if(index===1)return;const value:Record<string,string>={};headers.forEach((header,column)=>{if(header)value[header]=row.getCell(column).text.trim()});if(Object.values(value).some(Boolean))rows.push(value)});return rows}
function wordRows(text:string){return text.split(/\n\s*(?:---+|السؤال\s*\d+\s*:?)\s*\n/i).map(block=>{const row:Record<string,string>={};for(const line of block.split(/\r?\n/)){const match=line.match(/^\s*([^:：]+)[:：]\s*(.+)$/);if(!match)continue;const key=aliases[normalizeHeader(match[1])]||({نوع:'type',سؤال:'text','أ':'optionA','ب':'optionB','ج':'optionC','د':'optionD',إجابة:'correctAnswer',شرح:'explanation'} as Record<string,string>)[match[1].trim()];if(key)row[key]=match[2].trim()}return row}).filter(row=>row.text)}
async function parseFile(file:File){if(file.name.toLowerCase().endsWith('.xlsx'))return {sourceType:'xlsx',rows:await excelRows(file)} as const;if(file.name.toLowerCase().endsWith('.docx')){const mammoth=await import('mammoth/mammoth.browser');const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return {sourceType:'docx',rows:wordRows(result.value)} as const}throw new Error('اختر ملف XLSX أو DOCX فقط')}
export default function ImportManager({tests,notify,onCommitted}:{tests:Test[];notify:(message:string)=>void;onCommitted:()=>Promise<void>}){const [testId,setTestId]=useState(tests[0]?.id||'');const [file,setFile]=useState<File|null>(null);const [sourceRows,setSourceRows]=useState<Record<string,string>[]>([]);const [preview,setPreview]=useState<{batchId:string;rows:PreviewRow[];summary:{total:number;valid:number;errors:number;conflicts:number}}|null>(null);const [actions,setActions]=useState<Record<string,'skip'|'replace'>>({});const [busy,setBusy]=useState(false);
  const downloadTemplate=async()=>{const ExcelJS=await import('exceljs');const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('KIUR Questions');sheet.addRow(['نوع السؤال','نص السؤال','الخيار أ','الخيار ب','الخيار ج','الخيار د','الإجابة الصحيحة','الإجابات المقبولة','الشرح','معرف الصورة']);sheet.addRow(['mcq','ما الإجابة الصحيحة؟','خيار 1','خيار 2','خيار 3','خيار 4','A','','شرح اختياري','']);sheet.addRow(['fill_blank','أكمل: العضو المسؤول عن ضخ الدم هو ____','','','','','','القلب|قلب','تُقبل الإجابات المفصولة بعلامة |','']);sheet.getRow(1).font={bold:true};sheet.columns.forEach(column=>column.width=24);const bytes=await workbook.xlsx.writeBuffer();const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));link.download='KIUR-question-import-template.xlsx';link.click();URL.revokeObjectURL(link.href)};
  const inspect=async()=>{if(!file||!testId)return;setBusy(true);try{const parsed=await parseFile(file);setSourceRows(parsed.rows);const data=await request<typeof preview extends null?never:NonNullable<typeof preview>>('/api/admin/imports/preview',{method:'POST',body:JSON.stringify({testId,sourceType:parsed.sourceType,fileName:file.name,rows:parsed.rows})});setPreview(data);const defaults:Record<string,'skip'>={};data.rows.filter(row=>row.existingQuestionId).forEach(row=>defaults[String(row.row)]='skip');setActions(defaults);notify('اكتملت المعاينة؛ راجع الأخطاء والتعارضات قبل الحفظ')}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const commit=async()=>{if(!preview)return;setBusy(true);try{const result=await request<{inserted:number;replaced:number;skipped:number}>(`/api/admin/imports/${preview.batchId}/commit`,{method:'POST',body:JSON.stringify({rows:sourceRows,conflictActions:actions})});notify(`تمت إضافة ${result.inserted} واستبدال ${result.replaced} وتجاهل ${result.skipped}`);setPreview(null);setFile(null);await onCommitted()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  return <section className="importManager"><div className="panel importIntro"><div><span><FileSpreadsheet/></span><h3>استيراد أسئلة Excel أو Word</h3><p>استخدم القالب الرسمي، ثم راجع كل خطأ وتعارض قبل حفظ أي سؤال.</p></div><button onClick={()=>void downloadTemplate()}><Download/> تنزيل قالب Excel الرسمي</button></div><section className="panel importControls"><label><span>الاختبار المستهدف</span><select value={testId} onChange={event=>{setTestId(event.target.value);setPreview(null)}}>{tests.map(test=><option key={test.id} value={test.id}>{test.title} — {test.lectureName||test.subjectName}</option>)}</select></label><label className="fileDrop"><Upload/><span>{file?.name||'اختر ملف XLSX أو DOCX'}</span><input type="file" accept=".xlsx,.docx" onChange={event=>{setFile(event.target.files?.[0]||null);setPreview(null)}}/></label><button className="solid" disabled={!file||!testId||busy} onClick={()=>void inspect()}>{busy?'جارٍ التحليل...':'معاينة وفحص الملف'}</button></section>{preview&&<section className="panel previewPanel"><header><div><h3>نتيجة المعاينة</h3><p>{preview.summary.total} صف • {preview.summary.valid} صالح • {preview.summary.errors} أخطاء • {preview.summary.conflicts} تعارضات</p></div><button className="solid" disabled={busy||preview.summary.valid===0} onClick={()=>void commit()}><CheckCircle2/> اعتماد وحفظ</button></header><div className="previewTable"><table><thead><tr><th>الصف</th><th>النوع والسؤال</th><th>الحالة</th><th>قرار التعارض</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.row} className={row.errors.length?'invalidRow':''}><td>{row.row}</td><td><b>{row.questionType}</b><small>{row.text}</small></td><td>{row.errors.length?<span className="importError"><AlertTriangle/>{row.errors.join('، ')}</span>:row.existingQuestionId?<span className="importConflict">سؤال مكرر</span>:<span className="importValid">صالح</span>}</td><td>{row.existingQuestionId?<select value={actions[String(row.row)]||'skip'} onChange={event=>setActions({...actions,[String(row.row)]:event.target.value as 'skip'|'replace'})}><option value="skip">تجاهل</option><option value="replace">استبدال الموجود</option></select>:'—'}</td></tr>)}</tbody></table></div></section>}</section>}
