import {useEffect,useRef,useState} from 'react';
import {Ban,CheckCircle2,Clock3,Gavel,History,Search,ShieldAlert,XCircle} from 'lucide-react';
import './ban.css';
import './ban-review.css';

type Role='owner'|'admin'|'teacher'|'student';
type Props={currentRole:Role;currentUserId:string;permissions:string[];notify:(message:string)=>void};
type Data={students:any[];requests:any[];bans:any[];appeals:any[];logs:any[]};
type ReviewTarget={kind:'request'|'appeal';id:string;action:'approve'|'reject'};
type LiftTarget={id:string;studentName:string;requestNumber:string;banType:string};
const empty:Data={students:[],requests:[],bans:[],appeals:[],logs:[]};
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}
const statusLabel=(value:string)=>({pending:'قيد المراجعة',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغى تلقائيًا',expired:'منتهٍ',active:'فعال',lift_pending:'طلب رفع قيد المراجعة',lifted:'مرفوع'}[value]||value);
const typeLabel=(value:string)=>({temporary:'حظر مؤقت',permanent:'حظر نهائي',lift_temporary:'رفع حظر مؤقت',lift_permanent:'رفع حظر نهائي',precaution:'تعليق احترازي'}[value]||value);
const formatDate=(value?:string|null)=>value?new Intl.DateTimeFormat('ar-IQ',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';

export default function StudentBanManager({currentRole,currentUserId,permissions,notify}:Props){
  const canRequest=currentRole==='owner'||permissions.includes('request_student_ban');const canReview=currentRole==='owner'||permissions.includes('review_student_ban');const canLog=currentRole==='owner'||permissions.includes('view_student_ban_log');
  const [data,setData]=useState<Data>(empty);const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [studentId,setStudentId]=useState('');const [banType,setBanType]=useState<'temporary'|'permanent'>('temporary');const [durationValue,setDurationValue]=useState(1);const [durationUnit,setDurationUnit]=useState<'minutes'|'hours'|'days'>('days');const [reason,setReason]=useState('');const [evidence,setEvidence]=useState('');const [precaution,setPrecaution]=useState(true);const [reviewTarget,setReviewTarget]=useState<ReviewTarget|null>(null);const [reviewNote,setReviewNote]=useState('');const [liftTarget,setLiftTarget]=useState<LiftTarget|null>(null);const [liftReason,setLiftReason]=useState('');const [liftEvidence,setLiftEvidence]=useState('');const loadSequence=useRef(0);
  const load=async(search=query)=>{const sequence=++loadSequence.current;const next=await api<Data>('/api/admin/student-bans?q='+encodeURIComponent(search));if(sequence===loadSequence.current)setData(next)};
  useEffect(()=>{const timer=setTimeout(()=>void load().catch(error=>notify(error.message)),200);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{if(!data.students.some(item=>item.id===studentId))setStudentId(data.students[0]?.id||'')},[data.students]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const result=await api<{requestNumber:string}>('/api/admin/student-bans/requests',{method:'POST',body:JSON.stringify({studentId,banType,durationValue,durationUnit,reason,evidence,applyPrecaution:precaution})});notify(`تم رفع الطلب ${result.requestNumber} للمراجعة`);setReason('');setEvidence('');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const openReview=(kind:'request'|'appeal',id:string,action:'approve'|'reject')=>{setReviewNote('');setReviewTarget({kind,id,action})};
  const confirmReview=async()=>{if(!reviewTarget)return;if(reviewTarget.action==='reject'&&reviewNote.trim().length<3){notify('اكتب سبب الرفض بوضوح');return}setBusy(true);try{const path=reviewTarget.kind==='request'?`/api/admin/student-bans/requests/${reviewTarget.id}/review`:`/api/admin/student-bans/appeals/${reviewTarget.id}/review`;await api(path,{method:'POST',body:JSON.stringify({action:reviewTarget.action,note:reviewNote.trim()})});notify(reviewTarget.kind==='appeal'?'تمت مراجعة الاستئناف بنجاح':reviewTarget.action==='approve'?'تم اعتماد القرار':'تم رفض الطلب ورفع التعليق الاحترازي');setReviewTarget(null);setReviewNote('');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const openLift=(item:any)=>{setLiftReason('');setLiftEvidence('');setLiftTarget({id:item.id,studentName:item.studentName,requestNumber:item.requestNumber,banType:item.banType})};
  const requestLift=async()=>{if(!liftTarget||liftReason.trim().length<5)return;setBusy(true);try{const result=await api<{requestNumber:string}>(`/api/admin/student-bans/${liftTarget.id}/lift-requests`,{method:'POST',body:JSON.stringify({reason:liftReason.trim(),evidence:liftEvidence.trim()})});notify(`تم إرسال طلب الرفع ${result.requestNumber} وحالته قيد المراجعة`);setLiftTarget(null);setLiftReason('');setLiftEvidence('');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const pending=data.requests.filter(item=>item.status==='pending');const active=data.bans.filter(item=>['active','lift_pending'].includes(item.status));
  return <section className="banManager">
    <div className="banSummary"><article><ShieldAlert/><b>{pending.length}</b><small>طلبات قيد المراجعة</small></article><article><Ban/><b>{active.length}</b><small>حالات حظر فعالة</small></article><article><Gavel/><b>{data.appeals.filter(item=>item.status==='pending').length}</b><small>استئنافات معلقة</small></article></div>
    <div className="banSearch"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث باسم الطالب أو البريد الإلكتروني" aria-label="البحث في حالات حظر الطلاب"/></div>
    {canRequest&&<form className="panel banRequestForm" onSubmit={event=>void submit(event)}><header><ShieldAlert/><div><h3>رفع طلب حظر طالب</h3><p>يُطبّق التعليق الاحترازي لمدة لا تتجاوز 24 ساعة، ولا يصبح الحظر نهائيًا دون مراجعة مستقلة.</p></div></header><div className="banFields"><label><span>الطالب ضمن نطاقك</span><select required value={studentId} onChange={event=>setStudentId(event.target.value)}>{data.students.map(item=><option key={item.id} value={item.id}>{item.name} — {item.email}</option>)}</select></label><label><span>نوع الطلب</span><select value={banType} onChange={event=>setBanType(event.target.value as any)}><option value="temporary">حظر مؤقت</option><option value="permanent">حظر نهائي — يعتمد المالك فقط</option></select></label>{banType==='temporary'&&<><label><span>المدة</span><input type="number" min={1} value={durationValue} onChange={event=>setDurationValue(Number(event.target.value))}/></label><label><span>الوحدة</span><select value={durationUnit} onChange={event=>setDurationUnit(event.target.value as any)}><option value="minutes">دقائق</option><option value="hours">ساعات</option><option value="days">أيام</option></select></label></>}<label className="wide"><span>السبب</span><textarea required minLength={5} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="wide"><span>الأدلة أو الملاحظات (اختياري)</span><textarea maxLength={4000} value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label className="wide precaution"><input type="checkbox" checked={precaution} onChange={event=>setPrecaution(event.target.checked)}/><span>تعليق احترازي فوري (24 ساعة كحد أقصى، ويلغى تلقائيًا إن لم يعتمد الطلب)</span></label></div><button className="solid" disabled={busy||!studentId||reason.length<5}>رفع الطلب للمراجعة</button></form>}
    <section className="panel banList"><header><h3>طلبات الحظر ورفع الحظر</h3><small>{currentRole==='owner'?'يستطيع المالك اعتماد طلبه، بينما يبقى الاعتماد الذاتي ممنوعًا على بقية المخولين.':'لا يستطيع مقدم الطلب اعتماد طلبه بنفسه.'}</small></header>{data.requests.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.studentEmail} • {item.requestNumber}</small><p>{typeLabel(item.requestType)} — {item.reason}</p><em>{statusLabel(item.status)} • {formatDate(item.createdAt)}{item.precautionExpiresAt?` • تعليق حتى ${formatDate(item.precautionExpiresAt)}`:''}</em></div>{canReview&&item.status==='pending'&&(item.requestedBy!==currentUserId||currentRole==='owner')&&<div className="banActions"><button type="button" disabled={busy} onClick={()=>openReview('request',item.id,'approve')}><CheckCircle2/> اعتماد</button><button type="button" className="reject" disabled={busy} onClick={()=>openReview('request',item.id,'reject')}><XCircle/> رفض</button></div>}</article>)}{!data.requests.length&&<div className="banEmpty">لا توجد طلبات ضمن نطاقك.</div>}</section>
    <section className="panel banList"><header><h3>الحظر الفعال</h3><small>الحظر المؤقت ينتهي تلقائيًا؛ والرفع المبكر يمر بمراجع مستقل.</small></header>{active.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.studentEmail} • {item.requestNumber}</small><p>{typeLabel(item.banType)} — {item.reason}</p><em>{statusLabel(item.status)} • النهاية: {item.banType==='permanent'?'نهائي':formatDate(item.endsAt)}</em></div>{canRequest&&item.status==='active'&&<div className="banActions"><button type="button" disabled={busy} onClick={()=>openLift(item)}><Clock3/> طلب رفع مبكر</button></div>}</article>)}{!active.length&&<div className="banEmpty">لا توجد حالات حظر فعالة ضمن نطاقك.</div>}</section>
    {canReview&&<section className="panel banList"><header><h3>استئنافات الطلاب</h3><small>لكل طالب زر استئناف واحد لكل طلب حظر.</small></header>{data.appeals.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.requestNumber} • {typeLabel(item.banType)}</small><p>{item.reason}</p><em>{statusLabel(item.status)} • {formatDate(item.createdAt)}</em></div>{item.status==='pending'&&<div className="banActions"><button type="button" disabled={busy} onClick={()=>openReview('appeal',item.id,'approve')}><CheckCircle2/> قبول</button><button type="button" className="reject" disabled={busy} onClick={()=>openReview('appeal',item.id,'reject')}><XCircle/> رفض</button></div>}</article>)}{!data.appeals.length&&<div className="banEmpty">لا توجد استئنافات.</div>}</section>}
    {canLog&&<section className="panel banLog"><header><History/><div><h3>سجل استعمال أداة الحظر</h3><small>سجل دائم وغير قابل للتعديل.</small></div></header><div className="tableWrap"><table><thead><tr><th>الوقت</th><th>الطالب</th><th>الإجراء</th><th>المنفذ</th><th>الحالة</th><th>معرف الجهاز المجزأ</th></tr></thead><tbody>{data.logs.map(item=><tr key={item.id}><td data-label="الوقت">{formatDate(item.at)}</td><td data-label="الطالب">{item.student_name_snapshot}<small>{item.student_email_snapshot}</small></td><td data-label="الإجراء">{item.action}</td><td data-label="المنفذ">{item.actor_name_snapshot}<small>{item.actor_email_snapshot}</small></td><td data-label="الحالة">{statusLabel(item.status_snapshot)}</td><td data-label="معرف الجهاز"><code>{String(item.device_hash).slice(0,16)}…</code></td></tr>)}</tbody></table></div></section>}
    {reviewTarget&&<div className="banReviewOverlay" role="dialog" aria-modal="true" aria-labelledby="ban-review-title"><section className="banReviewDialog"><div className={reviewTarget.action==='approve'?'decisionIcon approve':'decisionIcon reject'}>{reviewTarget.action==='approve'?<CheckCircle2/>:<XCircle/>}</div><h3 id="ban-review-title">{reviewTarget.kind==='appeal'?(reviewTarget.action==='approve'?'قبول استئناف الطالب':'رفض استئناف الطالب'):(reviewTarget.action==='approve'?'اعتماد طلب الحظر':'رفض طلب الحظر')}</h3><p>راجع القرار ثم اضغط «موافق وتنفيذ». سيُحدّث الطلب والسجل فور نجاح العملية.</p><label><span>{reviewTarget.action==='reject'?'سبب الرفض — مطلوب':'ملاحظة المراجعة — اختيارية'}</span><textarea autoFocus maxLength={2000} value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder={reviewTarget.action==='reject'?'اكتب سببًا واضحًا...':'اكتب ملاحظة للمحضر إن وجدت...'}/></label><div className="decisionActions"><button type="button" onClick={()=>{setReviewTarget(null);setReviewNote('')}} disabled={busy}>إلغاء</button><button type="button" className={reviewTarget.action==='approve'?'confirmDecision':'confirmDecision reject'} onClick={()=>void confirmReview()} disabled={busy||(reviewTarget.action==='reject'&&reviewNote.trim().length<3)}>{busy?'جارٍ التنفيذ...':'موافق وتنفيذ'}</button></div></section></div>}
    {liftTarget&&<div className="banReviewOverlay" role="dialog" aria-modal="true" aria-labelledby="ban-lift-title"><form className="banReviewDialog" onSubmit={event=>{event.preventDefault();void requestLift()}}><div className="decisionIcon approve"><Clock3/></div><h3 id="ban-lift-title">طلب رفع الحظر مبكرًا</h3><p>{liftTarget.studentName} • {typeLabel(liftTarget.banType)} • {liftTarget.requestNumber}</p><label><span>سبب طلب الرفع — مطلوب</span><textarea autoFocus required minLength={5} maxLength={2000} value={liftReason} onChange={event=>setLiftReason(event.target.value)} placeholder="اشرح السبب بوضوح..."/></label><label><span>دليل أو ملاحظة داعمة — اختياري</span><textarea maxLength={4000} value={liftEvidence} onChange={event=>setLiftEvidence(event.target.value)} placeholder="أضف مرجعًا أو تفاصيل الدليل..."/></label><div className="decisionActions"><button type="button" onClick={()=>{setLiftTarget(null);setLiftReason('');setLiftEvidence('')}} disabled={busy}>إلغاء</button><button type="submit" className="confirmDecision" disabled={busy||liftReason.trim().length<5}>{busy?'جارٍ الإرسال...':'إرسال الطلب'}</button></div></form></div>}
  </section>;
}

export function BannedStudentScreen({user,onLogout}:{user:any;onLogout:()=>void}){const restriction=user.restriction||{};const [reason,setReason]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{await api('/api/me/ban/appeal',{method:'POST',body:JSON.stringify({reason})});setSent(true)}catch(error){alert((error as Error).message)}finally{setBusy(false)}};return <main className="blockedPage"><section className="blockedCard"><span><Ban/></span><small>وصول محدود إلى منصة KIUR</small><h1>{restriction.banType==='precaution'?'تعليق احترازي مؤقت':'الحساب محظور حاليًا'}</h1><p>{restriction.reason||'تم تقييد الحساب بقرار إداري.'}</p><dl><div><dt>نوع الحظر</dt><dd>{typeLabel(restriction.banType)}</dd></div><div><dt>رقم الطلب</dt><dd>{restriction.requestNumber||'—'}</dd></div><div><dt>وقت الانتهاء</dt><dd>{restriction.banType==='permanent'?'نهائي':formatDate(restriction.endsAt)}</dd></div></dl>{sent?<div className="appealSent"><CheckCircle2/> تم إرسال استئنافك، ولا يمكن إرسال استئناف ثانٍ لهذا الطلب.</div>:<div className="appealBox"><label><span>سبب الاستئناف</span><textarea minLength={5} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)} placeholder="اكتب توضيحك للمراجع..."/></label><button className="solid" disabled={busy||reason.trim().length<5} onClick={()=>void submit()}>إرسال الاستئناف الوحيد</button></div>}<button className="logoutBlocked" onClick={onLogout}>تسجيل الخروج</button></section></main>}
