import {useEffect,useMemo,useRef,useState} from 'react';
import {Award,BarChart3,BookOpen,Camera,CheckCircle2,Clock3,FileBadge2,GraduationCap,History,KeyRound,LogOut,Mail,MessageCircleQuestion,RefreshCw,ShieldCheck,Sparkles,Trash2,Trophy,UserRound} from 'lucide-react';
import {CertificateButton} from './Certificate';
import './student-profile.css';

type Dashboard={identity:{id:string;name:string;email:string;accountCode:string;joinedAt:string;lastLoginAt?:string;emailVerifiedAt?:string;universityName?:string;collegeName?:string;departmentName?:string;phaseName?:string;sectionName?:string;avatarUrl?:string|null};preferences:{avatarStyle:string;showAvatar:boolean;showBadges:boolean;showActivity:boolean};summary:{attempts:number;averagePercentage:number;bestPercentage:number;latestPercentage:number;passed:number;failed:number;passRate:number};weekly:{week:string;average:number;attempts:number;lastAt:string}[];subjects:{name:string;average:number;attempts:number;passed:number}[];recent:{attemptId:string;title:string;subject:string;percentage:number;at:string;passed:number}[];certificates:{attemptId:string;verificationCode:string;issuedAt:string;testTitle:string;percentage:number}[];requests:{id:string;requestNumber:string;status:string;reason:string;resolutionNote?:string;createdAt:string;updatedAt:string}[];notifications:{total:number;unread:number};badges:{id:string;title:string;description:string;icon:string}[]};
type Session={id:string;createdAt:string;lastUsedAt:string;expiresAt:string;current:boolean};
type Props={onCorrectPath:()=>void;onLogout:()=>void;notify:(message:string)=>void;learningHub?:{favorites:{id:string;title:string}[];weakTopics:{subjectName:string;wrongAnswers:number;answered:number;accuracy:number}[];reviewPlan?:{subjectName:string;nextReviewAt:string;due:number;lastScore:number}[];activeAttempt?:{title:string}|null}|null};
async function call<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{...(options.body instanceof Blob?{}:{'content-type':'application/json'}),...(options.headers||{})}});if(response.status===204)return undefined as T;const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}
const statusLabel=(value:string)=>({pending:'قيد المراجعة',needs_info:'تحتاج معلومات',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغى'} as Record<string,string>)[value]||value;
const date=(value?:string)=>value?new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium'}).format(new Date(value)):'—';

export default function StudentProfile({onCorrectPath,onLogout,notify,learningHub}:Props){
  const [data,setData]=useState<Dashboard|null>(null),[sessions,setSessions]=useState<Session[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState<'overview'|'learning'|'awards'|'support'|'security'>('overview'),[avatarBusy,setAvatarBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  const load=async()=>{setLoading(true);try{const [profile,active]=await Promise.all([call<Dashboard>('/api/me/profile-dashboard'),call<{data:Session[]}>('/api/me/sessions')]);setData(profile);setSessions(active.data)}catch(error){notify((error as Error).message)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
  const initials=useMemo(()=>data?.identity.name.trim().split(/\s+/).slice(0,2).map(v=>v[0]).join('')||'ط',[data?.identity.name]);
  const upload=async(file?:File)=>{if(!file)return;if(file.size>2*1024*1024){notify('حجم الصورة يجب ألا يتجاوز 2MB');return}setAvatarBusy(true);try{const result=await call<{avatarUrl:string}>('/api/me/avatar',{method:'PUT',headers:{'content-type':file.type},body:file});setData(current=>current?{...current,identity:{...current.identity,avatarUrl:result.avatarUrl}}:current);notify('تم تحديث الصورة الشخصية')}catch(error){notify((error as Error).message)}finally{setAvatarBusy(false);if(input.current)input.current.value=''}};
  const removeAvatar=async()=>{if(!confirm('حذف الصورة الشخصية والعودة إلى الأحرف الأولى؟'))return;try{await call('/api/me/avatar',{method:'DELETE'});setData(current=>current?{...current,identity:{...current.identity,avatarUrl:null}}:current);notify('تم حذف الصورة الشخصية')}catch(error){notify((error as Error).message)}};
  const savePrefs=async(patch:Partial<Dashboard['preferences']>)=>{if(!data)return;const next={...data.preferences,...patch};setData({...data,preferences:next});try{await call('/api/me/profile-dashboard/preferences',{method:'PATCH',body:JSON.stringify(next)});notify('تم حفظ إعدادات الخصوصية')}catch(error){setData({...data});notify((error as Error).message)}};
  const revoke=async(id?:string)=>{try{await call(id?`/api/me/sessions/${id}`:'/api/me/sessions/revoke-others',{method:id?'DELETE':'POST',body:id?undefined:'{}'});setSessions(current=>id?current.filter(item=>item.id!==id):current.filter(item=>item.current));notify('تم إنهاء الجلسات المحددة')}catch(error){notify((error as Error).message)}};
  const reset=async()=>{if(!data)return;try{await call('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email:data.identity.email})});notify('أرسلنا رابط تغيير كلمة المرور إلى بريدك')}catch(error){notify((error as Error).message)}};
  if(loading)return <section className="profileLoading"><RefreshCw/><p>جارٍ تجهيز بروفايلك الدراسي…</p></section>;if(!data)return <section className="profileLoading"><p>تعذر تحميل البروفايل.</p><button onClick={()=>void load()}>إعادة المحاولة</button></section>;
  const path=[data.identity.universityName,data.identity.collegeName,data.identity.departmentName,data.identity.phaseName,data.identity.sectionName].filter(Boolean).join(' / ');
  const maxWeekly=Math.max(100,...data.weekly.map(item=>Number(item.average)));
  return <section className="studentProfile" dir="rtl">
    <header className="profileHero"><div className={'profileAvatar '+data.preferences.avatarStyle}>{data.identity.avatarUrl?<img src={data.identity.avatarUrl} alt={`الصورة الشخصية لـ ${data.identity.name}`}/>:<span>{initials}</span>}<button disabled={avatarBusy} onClick={()=>input.current?.click()} aria-label="تغيير الصورة الشخصية"><Camera/></button><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>void upload(event.target.files?.[0])}/></div><div className="profileIdentity"><small>ملف الطالب</small><h2>{data.identity.name}</h2><p><Mail/>{data.identity.email}{data.identity.emailVerifiedAt&&<b><CheckCircle2/>موثق</b>}</p><code>رمز الطالب: {data.identity.accountCode}</code></div><div className="profilePath"><GraduationCap/><div><small>المسار الأكاديمي</small><p>{path||'لم يكتمل المسار'}</p></div><button onClick={onCorrectPath}>طلب تصحيح</button></div></header>
    <nav className="profileTabs" aria-label="أقسام البروفايل">{([['overview','نظرة عامة',UserRound],['learning','التعلّم',BookOpen],['awards','الإنجازات',Award],['support','الدعم',MessageCircleQuestion],['security','الأمان',ShieldCheck]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav>
    {tab==='overview'&&<><div className="profileStats"><article><History/><b>{data.summary.attempts}</b><span>محاولة مكتملة</span></article><article><BarChart3/><b>{data.summary.averagePercentage}%</b><span>المتوسط العام</span></article><article><Trophy/><b>{data.summary.bestPercentage}%</b><span>أعلى نتيجة</span></article><article><CheckCircle2/><b>{data.summary.passRate}%</b><span>نسبة النجاح</span></article></div><div className="profileGrid"><section className="profileCard"><header><div><small>آخر 12 أسبوعًا</small><h3>تطور الأداء</h3></div><span>{data.summary.latestPercentage}% آخر نتيجة</span></header>{data.weekly.length?<div className="weeklyChart">{data.weekly.map(item=><div key={item.week}><i style={{height:`${Math.max(5,Number(item.average)/maxWeekly*100)}%`}}/><b>{item.average}%</b><small>{date(item.lastAt)}</small></div>)}</div>:<p className="profileEmpty">يظهر الرسم بعد إكمال أول اختبار.</p>}</section><section className="profileCard"><header><div><small>حسب المادة</small><h3>ملخص المواد</h3></div></header>{data.subjects.length?<div className="subjectProgress">{data.subjects.map(item=><div key={item.name}><span><b>{item.name}</b><small>{item.attempts} محاولة</small></span><i><em style={{width:`${Math.min(100,item.average)}%`}}/></i><strong>{item.average}%</strong></div>)}</div>:<p className="profileEmpty">لا توجد نتائج مصنفة بعد.</p>}</section></div>{data.preferences.showActivity&&<section className="profileCard activityCard"><header><div><small>خاص بك</small><h3>آخر النشاطات</h3></div></header>{data.recent.slice(0,8).map(item=><article key={item.attemptId}><span className={item.passed?'passed':'failed'}>{item.percentage}%</span><div><b>{item.title}</b><small>{item.subject} • {date(item.at)}</small></div></article>)}{!data.recent.length&&<p className="profileEmpty">لا يوجد نشاط حتى الآن.</p>}</section>}</>}
    {tab==='learning'&&<div className="profileGrid learningGrid"><section className="profileCard"><h3>موضوعات تحتاج تركيزًا</h3>{learningHub?.weakTopics?.map(item=><article className="learningRow" key={item.subjectName}><div><b>{item.subjectName}</b><small>{item.wrongAnswers} إجابة تحتاج مراجعة</small></div><strong>{item.accuracy}%</strong></article>)}{!learningHub?.weakTopics?.length&&<p className="profileEmpty">لا توجد نقاط ضعف كافية للتحليل.</p>}</section><section className="profileCard"><h3>خطة المراجعة</h3>{learningHub?.reviewPlan?.map(item=><article className="learningRow" key={item.subjectName}><div><b>{item.subjectName}</b><small>{item.due?'مستحقة الآن':`موعدها ${date(item.nextReviewAt)}`}</small></div><strong>{item.lastScore}%</strong></article>)}{!learningHub?.reviewPlan?.length&&<p className="profileEmpty">ستتكون الخطة تلقائيًا من نتائجك.</p>}</section><section className="profileCard"><h3>المحفوظات والمفضلة</h3>{learningHub?.activeAttempt&&<p className="resumeLine"><Clock3/>اختبار محفوظ: <b>{learningHub.activeAttempt.title}</b></p>}<div className="favoriteList">{learningHub?.favorites?.map(item=><span key={item.id}>{item.title}</span>)}</div>{!learningHub?.favorites?.length&&!learningHub?.activeAttempt&&<p className="profileEmpty">لا توجد اختبارات محفوظة أو مفضلة.</p>}</section></div>}
    {tab==='awards'&&<div className="profileGrid"><section className="profileCard"><header><div><small>اختيارية وخاصة</small><h3>الشارات العلمية</h3></div><label className="profileSwitch"><input type="checkbox" checked={data.preferences.showBadges} onChange={e=>void savePrefs({showBadges:e.target.checked})}/><span/>إظهار الشارات</label></header>{data.preferences.showBadges?<div className="badgeGrid">{data.badges.map(item=><article key={item.id}><Sparkles/><b>{item.title}</b><small>{item.description}</small></article>)}{!data.badges.length&&<p className="profileEmpty">أكمل أول اختبار للحصول على شارتك الأولى.</p>}</div>:<p className="profileEmpty">الشارات مخفية حسب اختيارك.</p>}</section><section className="profileCard"><h3>الشهادات الموثقة</h3>{data.certificates.map(item=><article className="certificateRow" key={item.attemptId}><FileBadge2/><div><b>{item.testTitle}</b><small>{item.percentage}% • {date(item.issuedAt)}</small></div><CertificateButton attemptId={item.attemptId} notify={notify}/></article>)}{!data.certificates.length&&<p className="profileEmpty">ستظهر شهادات الاختبارات الناجحة هنا.</p>}</section></div>}
    {tab==='support'&&<div className="profileGrid"><section className="profileCard supportIntro"><MessageCircleQuestion/><h3>هل مسارك الدراسي غير صحيح؟</h3><p>أرسل طلبًا موثقًا إلى الإدارة، واحصل على رقم متابعة وقرار محفوظ.</p><button onClick={onCorrectPath}>إنشاء طلب تصحيح المسار</button></section><section className="profileCard"><h3>طلباتك السابقة</h3>{data.requests.map(item=><article className="supportRequest" key={item.id}><div><code>{item.requestNumber}</code><span className={item.status}>{statusLabel(item.status)}</span></div><p>{item.reason}</p>{item.resolutionNote&&<small>رد الإدارة: {item.resolutionNote}</small>}<time>{date(item.updatedAt)}</time></article>)}{!data.requests.length&&<p className="profileEmpty">لم ترسل طلبات تصحيح بعد.</p>}</section></div>}
    {tab==='security'&&<div className="profileGrid"><section className="profileCard"><h3>الحساب والخصوصية</h3><div className="securityAction"><KeyRound/><div><b>كلمة المرور</b><small>سنرسل رابطًا آمنًا إلى بريدك الموثق.</small></div><button onClick={()=>void reset()}>إرسال رابط تغيير</button></div><div className="privacySettings"><label><input type="checkbox" checked={data.preferences.showActivity} onChange={e=>void savePrefs({showActivity:e.target.checked})}/><span/>إظهار آخر نشاط داخل بروفايلي</label><label>لون الأحرف الأولى<select value={data.preferences.avatarStyle} onChange={e=>void savePrefs({avatarStyle:e.target.value})}><option value="indigo">نيلي</option><option value="blue">أزرق</option><option value="violet">بنفسجي</option><option value="amber">كهرماني</option></select></label>{data.identity.avatarUrl&&<button className="deleteAvatar" onClick={()=>void removeAvatar()}><Trash2/>حذف الصورة الشخصية</button>}</div></section><section className="profileCard"><header><div><small>جلساتك فقط</small><h3>الأجهزة والجلسات</h3></div>{sessions.length>1&&<button onClick={()=>void revoke()}>إنهاء الجلسات الأخرى</button>}</header>{sessions.map(item=><article className="sessionRow" key={item.id}><ShieldCheck/><div><b>{item.current?'هذا الجهاز':'جهاز مسجل'}</b><small>آخر استخدام {date(item.lastUsedAt)} • ينتهي {date(item.expiresAt)}</small></div>{!item.current&&<button onClick={()=>void revoke(item.id)}>إنهاء</button>}</article>)}</section><section className="profileCard"><h3>معلومات الحساب</h3><p>تاريخ الانضمام: {date(data.identity.joinedAt)}</p><p>آخر دخول: {date(data.identity.lastLoginAt)}</p><button className="logoutProfile" onClick={onLogout}><LogOut/>تسجيل الخروج</button></section></div>}
  </section>;
}
