import {useEffect,useState} from 'react';
import {Award,Eye,EyeOff,Flag,HeartPulse,RefreshCw,ShieldCheck,Sparkles,Target,Trophy,Users} from 'lucide-react';
import './gamification.css';

type Mission={id:string;missionType:'weekly_activity'|'weak_topic';targetValue:number;progressValue:number;rewardPoints:number;status:string;subjectName?:string};
type Data={enabled:boolean;season:{title:string;endsAt:string};profile:{nickname:string;leaderboardVisible:boolean;selectedFrame:string};summary:{seasonPoints:number;lifetimePoints:number;level:number;nextLevel:number;progress:number;band:string;cohortSize:number};missions:Mission[];leaderboard:{id:string;displayName:string;points:number;position:number;isMe:boolean}[];badges:{badgeId:string;earnedAt:string}[];sectionGoal?:{title:string;targetPoints:number;currentPoints:number;rewardLabel?:string}|null};
const badgeNames:Record<string,[string,string]>= {first:['البداية الذكية','أول نقاط في مسارك'],steady:['إيقاع ثابت','تقدم متوازن ومستمر'],master:['إتقان سريري','مستوى متقدم من الإتقان'],mentor:['نبض المعرفة','أثر علمي طويل المدى']};
async function call<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}

export default function StudentPoints({notify}:{notify:(message:string)=>void}){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[nickname,setNickname]=useState('');
  const load=async()=>{setLoading(true);try{const value=await call<Data>('/api/gamification');setData(value);setNickname(value.profile.nickname)}catch(error){notify((error as Error).message)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
  const save=async(patch:Partial<Data['profile']>)=>{if(!data)return;const profile={...data.profile,...patch,nickname:patch.nickname??nickname};setSaving(true);try{await call('/api/gamification/preferences',{method:'PATCH',body:JSON.stringify(profile)});setData({...data,profile});notify('تم حفظ إعدادات المنافسة')}catch(error){notify((error as Error).message)}finally{setSaving(false)}};
  if(loading)return <section className="pointsLoading"><RefreshCw/><p>جارٍ حساب تقدمك العلمي…</p></section>;
  if(!data)return <section className="pointsLoading"><p>تعذر تحميل نظام النقاط.</p><button onClick={()=>void load()}>إعادة المحاولة</button></section>;
  if(!data.enabled)return <section className="pointsLoading"><ShieldCheck/><h3>نظام النقاط متوقف مؤقتًا</h3><p>نتائج اختباراتك تبقى محفوظة دون تغيير.</p></section>;
  const remaining=Math.max(0,Math.ceil((Date.parse(data.season.endsAt)-Date.now())/86400000));const goal=data.sectionGoal;const goalPercent=goal?Math.min(100,Math.round(Number(goal.currentPoints)/Math.max(1,Number(goal.targetPoints))*100)):0;
  return <section className="pointsDashboard" dir="rtl">
    <header className="pointsHero"><div><small>{data.season.title} • يتبقى {remaining} يومًا</small><h2>نقاطي</h2><p>نقاطك وإنجازاتك وتقدمك الدراسي — للإتقان والتحسن والمراجعة، لا للسرعة.</p></div><div className="levelOrb"><HeartPulse/><b>{data.summary.level}</b><span>المستوى</span></div></header>
    <div className="pointsStats"><article><Sparkles/><b>{data.summary.seasonPoints}</b><span>نقاط الموسم</span></article><article><Trophy/><b>{data.summary.lifetimePoints}</b><span>النقاط الدائمة</span></article><article><Users/><b>{data.summary.band}</b><span>ضمن مسارك الأكاديمي</span></article></div>
    <section className="levelProgress"><header><b>الطريق إلى المستوى {data.summary.level+1}</b><span>{data.summary.progress}%</span></header><i><em style={{width:`${Math.min(100,data.summary.progress)}%`}}/></i><small>{Math.max(0,data.summary.nextLevel-data.summary.lifetimePoints)} نقطة متبقية</small></section>
    <div className="pointsGrid"><section className="pointsCard"><header><Target/><div><small>أسبوع مرن + يوم سماح</small><h3>مهامك الشخصية</h3></div></header>{data.missions.length?data.missions.map(mission=><article className="mission" key={mission.id}><div><b>{mission.missionType==='weekly_activity'?'نشاط أسبوعي':`راجع ${mission.subjectName||'المادة الأضعف'}`}</b><small>المكافأة {mission.rewardPoints} نقطة</small></div><span>{mission.progressValue}/{mission.targetValue}</span><i><em style={{width:`${Math.min(100,mission.progressValue/mission.targetValue*100)}%`}}/></i></article>):<p className="pointsEmpty">أكمل اختبارًا لتتكون مهامك الذكية.</p>}</section>
      <section className="pointsCard"><header><Award/><div><small>إنجازات غير إلزامية</small><h3>شاراتك العلمية</h3></div></header><div className="pointsBadges">{data.badges.map(item=>{const badge=badgeNames[item.badgeId]||[item.badgeId,'إنجاز علمي'];return <article key={item.badgeId}><Award/><b>{badge[0]}</b><small>{badge[1]}</small></article>})}{!data.badges.length&&<p className="pointsEmpty">أول شارة بانتظار أول نقاطك.</p>}</div></section>
    </div>
    {goal&&<section className="sectionGoal"><Flag/><div><small>هدف تعاوني اختياري للشعبة</small><h3>{goal.title}</h3><i><em style={{width:`${goalPercent}%`}}/></i><p>{goal.currentPoints} من {goal.targetPoints} نقطة {goal.rewardLabel?`• ${goal.rewardLabel}`:''}</p></div><b>{goalPercent}%</b></section>}
    <div className="pointsGrid"><section className="pointsCard leaderboard"><header><Trophy/><div><small>{data.summary.cohortSize} طالبًا في نفس المسار</small><h3>لوحة المنافسة الهادئة</h3></div></header>{data.profile.leaderboardVisible?data.leaderboard.map(item=><article className={item.isMe?'me':''} key={item.id}><b>#{item.position}</b><span>{item.displayName}{item.isMe&&<small>أنت</small>}</span><strong>{item.points} نقطة</strong></article>):<div className="pointsEmpty"><EyeOff/><p>أخفيت ظهورك في اللوحة. ما زلت ترى تقدمك الشخصي أعلاه.</p></div>}</section>
      <section className="pointsCard preferences"><header><ShieldCheck/><div><small>خصوصيتك أولًا</small><h3>هوية المنافسة</h3></div></header><label><span>لقب مختصر اختياري</span><input maxLength={24} value={nickname} onChange={event=>setNickname(event.target.value)} placeholder="مثال: نبض التخدير"/></label><label><span>إطار الإنجاز</span><select value={data.profile.selectedFrame} onChange={event=>void save({selectedFrame:event.target.value})}><option value="pulse">نبض</option><option value="clinical">سريري</option><option value="cuneiform">رافديني</option></select></label><button disabled={saving} onClick={()=>void save({nickname})}><Sparkles/>{saving?'جارٍ الحفظ…':'حفظ اللقب'}</button><button className="visibility" disabled={saving} onClick={()=>void save({leaderboardVisible:!data.profile.leaderboardVisible})}>{data.profile.leaderboardVisible?<><EyeOff/>إخفائي من المنافسة</>:<><Eye/>إظهاري في المنافسة</>}</button></section>
    </div>
  </section>;
}
