import {Search,UserRoundCheck,Users} from 'lucide-react';
import './insights.css';

export type StudentRow={id:string;name:string;email:string;registeredAt:string;departmentName?:string|null;phaseName?:string|null;attempts:number;averagePercentage:number;passedAttempts:number;lastActivity?:string|null};

export default function StudentManager({students,total,search,onSearch,loading}:{students:StudentRow[];total:number;search:string;onSearch:(value:string)=>void;loading:boolean}){
  const attempted=students.filter(item=>Number(item.attempts)>0).length;const average=attempted?Math.round(students.reduce((sum,item)=>sum+Number(item.averagePercentage||0),0)/attempted*100)/100:0;
  return <section className="studentsManager"><div className="studentStats"><article><span><Users/></span><div><b>{total}</b><small>طالب مسجل</small></div></article><article><span><UserRoundCheck/></span><div><b>{attempted}</b><small>طلاب أكملوا اختبارات</small></div></article><article><span><UserRoundCheck/></span><div><b>{average}%</b><small>متوسط الطلاب المعروضين</small></div></article></div><section className="panel tableWrap"><div className="studentsHead"><div><h3>الطلاب المسجلون</h3><p>الاسم والبريد والمسار الدراسي ومتوسط نتائج الاختبارات.</p></div><label><Search/><input value={search} onChange={event=>onSearch(event.target.value)} placeholder="ابحث بالاسم أو البريد..."/></label></div><table className="studentsTable"><thead><tr><th>الطالب</th><th>البريد الإلكتروني</th><th>القسم والمرحلة</th><th>المحاولات</th><th>متوسط النتائج</th><th>الناجحة</th><th>تاريخ التسجيل</th></tr></thead><tbody>{students.map(item=><tr key={item.id}><td><div className="studentIdentity"><span>{item.name.slice(0,2)}</span><b>{item.name}</b></div></td><td className="studentEmail">{item.email}</td><td>{item.departmentName||'لم يحدد'}<small className="tableLecture">{item.phaseName||'لم يحدد المرحلة'}</small></td><td>{item.attempts}</td><td><span className={'scorePill '+(Number(item.averagePercentage)>=60?'goodScore':'lowScore')}>{Number(item.averagePercentage||0)}%</span></td><td>{item.passedAttempts}</td><td>{new Intl.DateTimeFormat('ar-IQ').format(new Date(item.registeredAt))}</td></tr>)}</tbody></table>{loading&&<div className="studentsLoading">جارٍ تحميل بيانات الطلاب...</div>}{!loading&&!students.length&&<div className="catalogEmpty">لا يوجد طلاب مطابقون للبحث.</div>}{total>students.length&&!search&&<p className="studentLimit">يعرض الجدول أحدث {students.length} طالب من أصل {total}.</p>}</section></section>
}
