import {useEffect,useState} from 'react';
import {Ban,CheckCircle2,Clock3,Gavel,History,Search,ShieldAlert,XCircle} from 'lucide-react';
import './ban.css';

type Role='owner'|'admin'|'teacher'|'student';
type Props={currentRole:Role;currentUserId:string;permissions:string[];notify:(message:string)=>void};
type Data={students:any[];requests:any[];bans:any[];appeals:any[];logs:any[]};
const empty:Data={students:[],requests:[],bans:[],appeals:[],logs:[]};
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||'تعذر إكمال العملية');return data}
const statusLabel=(value:string)=>({pending:'قيد المراجعة',approved:'معتمد',rejected:'مرفوض',cancelled:'ملغى تلقائيًا',expired:'منتهٍ',active:'فعال',lift_pending:'طلب رفع قيد المراجعة',lifted:'مرفوع'}[value]||value);
const typeLabel=(value:string)=>({temporary:'حظر مؤقت',permanent:'حظر نهائي',lift_temporary:'رفع حظر مؤقت',lift_permanent:'رفع حظر نهائي',precaution:'تعليق احترازي'}[value]||value);
const formatDate=(value?:string|null)=>value?new Intl.DateTimeFormat('ar-IQ',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';

export default function StudentBanManager({currentRole,currentUserId,permissions,notify}:Props){
  const canRequest=currentRole==='owner'||permissions.includes('request_student_ban');const canReview=currentRole==='owner'||permissions.includes('review_student_ban');const canLog=currentRole==='owner'||permissions.includes('view_student_ban_log');
  const [data,setData]=useState<Data>(empty);const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [studentId,setStudentId]=useState('');const [banType,setBanType]=useState<'temporary'|'permanent'>('temporary');const [durationValue,setDurationValue]=useState(1);const [durationUnit,setDurationUnit]=useState<'minutes'|'hours'|'days'>('days');const [reason,setReason]=useState('');const [evidence,setEvidence]=useState('');const [precaution,setPrecaution]=useState(true);
  const load=async(search=query)=>setData(await api<Data>('/api/admin/student-bans?q='+encodeURIComponent(search)));
  useEffect(()=>{const timer=setTimeout(()=>void load().catch(error=>notify(error.message)),200);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{if(!data.students.some(item=>item.id===studentId))setStudentId(data.students[0]?.id||'')},[data.students]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const result=await api<{requestNumber:string}>('/api/admin/student-bans/requests',{method:'POST',body:JSON.stringify({studentId,banType,durationValue,durationUnit,reason,evidence,applyPrecaution:precaution})});notify(`تم رفع الطلب ${result.requestNumber} للمراجعة`);setReason('');setEvidence('');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const review=async(id:string,action:'approve'|'reject')=>{const note=prompt(action==='approve'?'ملاحظة المراجعة (اختيارية)':'اكتب سبب الرفض');if(note===null)return;setBusy(true);try{await api(`/api/admin/student-bans/requests/${id}/review`,{method:'POST',body:JSON.stringify({action,note})});notify(action==='approve'?'تم اعتماد القرار':'تم رفض الطلب ورفع التعليق الاحترازي');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const reviewAppeal=async(id:string,action:'approve'|'reject')=>{const note=prompt(action==='approve'?'سبب قبول الاستئناف':'سبب رفض الاستئناف');if(note===null)return;setBusy(true);try{await api(`/api/admin/student-bans/appeals/${id}/review`,{method:'POST',body:JSON.stringify({action,note})});notify('تمت مراجعة الاستئناف');await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const requestLift=async(id:string)=>{const liftReason=prompt('اكتب سبب طلب رفع الحظر مبكرًا');if(!liftReason)return;setBusy(true);try{const result=await api<{requestNumber:string}>(`/api/admin/student-bans/${id}/lift-requests`,{method:'POST',body:JSON.stringify({reason:liftReason})});notify(`تم رفع طلب الإلغاء ${result.requestNumber}`);await load()}catch(error){notify((error as Error).message)}finally{setBusy(false)}};
  const pending=data.requests.filter(item=>item.status==='pending');const active=data.bans.filter(item=>['active','lift_pending'].includes(item.status));
  return <section className="banManager">
    <div className="banSummary"><article><ShieldAlert/><b>{pending.length}</b><small>طلبات قيد المراجعة</small></article><article><Ban/><b>{active.length}</b><small>حالات حظر فعالة</small></article><article><Gavel/><b>{data.appeals.filter(item=>item.status==='pending').length}</b><small>استئنافات معلقة</small></article></div>
    <div className="banSearch"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث باسم الطالب أو البريد الإلكتروني"/></div>
    {canRequest&&<form className="panel banRequestForm" onSubmit={event=>void submit(event)}><header><ShieldAlert/><div><h3>رفع طلب حظر طالب</h3><p>يُطبّق التعليق الاحترازي لمدة لا تتجاوز 24 ساعة، ولا يصبح الحظر نهائيًا دون مراجعة مستقلة.</p></div></header><div className="banFields"><label><span>الطالب ضمن نطاقك</span><select required value={studentId} onChange={event=>setStudentId(event.target.value)}>{data.students.map(item=><option key={item.id} value={item.id}>{item.name} — {item.email}</option>)}</select></label><label><span>نوع الطلب</span><select value={banType} onChange={event=>setBanType(event.target.value as any)}><option value="temporary">حظر مؤقت</option><option value="permanent">حظر نهائي — يعتمد المالك فقط</option></select></label>{banType==='temporary'&&<><label><span>المدة</span><input type="number" min={1} value={durationValue} onChange={event=>setDurationValue(Number(event.target.value))}/></label><label><span>الوحدة</span><select value={durationUnit} onChange={event=>setDurationUnit(event.target.value as any)}><option value="minutes">دقائق</option><option value="hours">ساعات</option><option value="days">أيام</option></select></label></>}<label className="wide"><span>السبب</span><textarea required minLength={5} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="wide"><span>الأدلة أو الملاحظات (اختياري)</span><textarea maxLength={4000} value={evidence} onChange={event=>setEvidence(event.target.value)}/></label><label className="wide precaution"><input type="checkbox" checked={precaution} onChange={event=>setPrecaution(event.target.checked)}/><span>تعليق احترازي فوري (24 ساعة كحد أقصى، ويلغى تلقائيًا إن لم يعتمد الطلب)</span></label></div><button className="solid" disabled={busy||!studentId||reason.length<5}>رفع الطلب للمراجعة</button></form>}
    <section className="panel banList"><header><h3>طلبات الحظر ورفع الحظر</h3><small>لا يستطيع مقدم الطلب اعتماد طلبه بنفسه.</small></header>{data.requests.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.studentEmail} • {item.requestNumber}</small><p>{typeLabel(item.requestType)} — {item.reason}</p><em>{statusLabel(item.status)} • {formatDate(item.createdAt)}{item.precautionExpiresAt?` • تعليق حتى ${formatDate(item.precautionExpiresAt)}`:''}</em></div>{canReview&&item.status==='pending'&&item.requestedBy!==currentUserId&&<div className="banActions"><button disabled={busy} onClick={()=>void review(item.id,'approve')}><CheckCircle2/> اعتماد</button><button className="reject" disabled={busy} onClick={()=>void review(item.id,'reject')}><XCircle/> رفض</button></div>}</article>)}{!data.requests.length&&<div className="banEmpty">لا توجد طلبات ضمن نطاقك.</div>}</section>
    <section className="panel banList"><header><h3>الحظر الفعال</h3><small>الحظر المؤقت ينتهي تلقائيًا؛ والرفع المبكر يمر بمراجع مستقل.</small></header>{active.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.studentEmail} • {item.requestNumber}</small><p>{typeLabel(item.banType)} — {item.reason}</p><em>{statusLabel(item.status)} • النهاية: {item.banType==='permanent'?'نهائي':formatDate(item.endsAt)}</em></div>{canRequest&&item.status==='active'&&<div className="banActions"><button disabled={busy} onClick={()=>void requestLift(item.id)}><Clock3/> طلب رفع مبكر</button></div>}</article>)}{!active.length&&<div className="banEmpty">لا توجد حالات حظر فعالة ضمن نطاقك.</div>}</section>
    {canReview&&<section className="panel banList"><header><h3>استئنافات الطلاب</h3><small>لكل طالب زر استئناف واحد لكل طلب حظر.</small></header>{data.appeals.map(item=><article key={item.id}><div><b>{item.studentName}</b><small>{item.requestNumber} • {typeLabel(item.banType)}</small><p>{item.reason}</p><em>{statusLabel(item.status)} • {formatDate(item.createdAt)}</em></div>{item.status==='pending'&&<div className="banActions"><button disabled={busy} onClick={()=>void reviewAppeal(item.id,'approve')}><CheckCircle2/> قبول</button><button className="reject" disabled={busy} onClick={()=>void reviewAppeal(item.id,'reject')}><XCircle/> رفض</button></div>}</article>)}{!data.appeals.length&&<div className="banEmpty">لا توجد استئنافات.</div>}</section>}
    {canLog&&<section className="panel banLog"><header><History/><div><h3>سجل استعمال أداة الحظر</h3><small>سجل دائم وغير قابل للتعديل.</small></div></header><div className="tableWrap"><table><thead><tr><th>الوقت</th><th>الطالب</th><th>الإجراء</th><th>المنفذ</th><th>الحالة</th><th>معرف الجهاز المجزأ</th></tr></thead><tbody>{data.logs.map(item=><tr key={item.id}><td>{formatDate(item.at)}</td><td>{item.student_name_snapshot}<small>{item.student_email_snapshot}</small></td><td>{item.action}</td><td>{item.actor_name_snapshot}<small>{item.actor_email_snapshot}</small></td><td>{statusLabel(item.status_snapshot)}</td><td><code>{String(item.device_hash).slice(0,16)}…</code></td></tr>)}</tbody></table></div></section>}
  </section>;
}

export function BannedStudentScreen({user,onLogout}:{user:any;onLogout:()=>void}){const restriction=user.restriction||{};const [reason,setReason]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{await api('/api/me/ban/appeal',{method:'POST',body:JSON.stringify({reason})});setSent(true)}catch(error){alert((error as Error).message)}finally{setBusy(false)}};return <main className="blockedPage"><section className="blockedCard"><span><Ban/></span><small>وصول محدود إلى منصة KIUR</small><h1>{restriction.banType==='precaution'?'تعليق احترازي مؤقت':'الحساب محظور حاليًا'}</h1><p>{restriction.reason||'تم تقييد الحساب بقرار إداري.'}</p><dl><div><dt>نوع الحظر</dt><dd>{typeLabel(restriction.banType)}</dd></div><div><dt>رقم الطلب</dt><dd>{restriction.requestNumber||'—'}</dd></div><div><dt>وقت الانتهاء</dt><dd>{restriction.banType==='permanent'?'نهائي':formatDate(restriction.endsAt)}</dd></div></dl>{sent?<div className="appealSent"><CheckCircle2/> تم إرسال استئنافك، ولا يمكن إرسال استئناف ثانٍ لهذا الطلب.</div>:<div className="appealBox"><label><span>سبب الاستئناف</span><textarea minLength={5} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)} placeholder="اكتب توضيحك للمراجع..."/></label><button className="solid" disabled={busy||reason.trim().length<5} onClick={()=>void submit()}>إرسال الاستئناف الوحيد</button></div>}<button className="logoutBlocked" onClick={onLogout}>تسجيل الخروج</button></section></main>}
